### ISSUE TITLE
SVG inline images not rendering

### ISSUE THREAD

**Issue by enipro** [vvvv/SVG#107]
Hello! 

There is a problem when an image is within svg file as a absoult uri of data type. 
I.e. - data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAYABgAAD/4QBaRXhpZgAATU....(100KB of data)

If Image data is too long, Uri SvgImage Href property setting fails with exception, due to .Net limitations for Uri size.

I have a resolution which is quite ugly and I made it working for me, but to let you guys know. Issue is in SvgElementFactory.cs, function SetPropertyValue.

I resolved by adding one more property called HrefRaw in SvgImage and forcing population of this property with full URI data (over 100K in my case), while cutting uri to minimum length for it to be acceptable for Uri constructor. Like I sad - ugly, I know, but quick and dirty fix. 

If someone else already reported feel free to remove the post..

Great work on the lib though anyway - thank you so much for it!

**Comment by mrbean-bremen** [comment]
Has been fixed with #226 - closing.
