### ISSUE TITLE
SVG : Overlapping the Text

### ISSUE THREAD

**Issue by anup24goswami** [vvvv/SVG#113]
Hi All,
We are using SVG.dll of **version (1.5.2.33180)** to render the images but in case of large text the image(s) are generated with overlapped text.

**Imgae with overlapped text:**
![overlapped text](https://cloud.githubusercontent.com/assets/5030470/5375078/310b0378-808c-11e4-8562-09ccbd35b588.png)

**Real Data:**
![real data](https://cloud.githubusercontent.com/assets/5030470/5375104/66cd5696-808c-11e4-89ad-9dc5445006f2.png)

Please help us to resolve this issue.

**Comment by mrbean-bremen** [comment]
@anup24goswami - this is quite old. Do you know if this is still an issue, and if yes, do you have an example for the problem?

**Comment by mrbean-bremen** [comment]
Closing the issue. Please reopen if this is still an issue and you have more information.
