### ISSUE TITLE
It might make sense to refactor SvgElementCollection.LogIDChange

### ISSUE THREAD

**Issue by haykpetros** [vvvv/SVG#115]
Following code will slow down when running in Visual Studio, so it might make sense to re-factor it to use "System.Diagnostics.Debug.WriteLine()" instead, so it will run in Debug mode only.

**Comment by tebjan** [comment]
in which case have you noticed the slow down? do you have an example?

**Comment by haykpetros** [comment]
If you look at SvgElementCollection.cs Line 59 you will see following code:

    private void LogIDChange(SvgElement elem, string oldId, string newID) 
    { 
	Console.WriteLine("ID of SVG element " + elem.ToString() + " changed from " + oldId + " to " + newID); 
    } 

So when running in Visual Studio what happens it starts to output in Debug Console line for every element that has ID. If SVG has, for example, 10 or 20 thousands element it might take an hour to finish generating an image.

**Comment by tebjan** [comment]
this should only happen if the ID was duplicated, it does not log all IDs... do you have a case which logs all IDs?

**Comment by Stardraw** [comment]
I agree - there should never be any Console.WriteLine in a library.
This could could be running on a server and there is no Console to see.
Any Debug Output should be through System.Diagnostics.Debug.WriteLine
This way, it will be compiled out in a release version

**Comment by tebjan** [comment]
agreed!

**Comment by haykpetros** [comment]
I do have several SVG that when "Draw()" method is called that line is always called, though there are no changes for ID.
