### ISSUE TITLE
Importing Adobe Illustrator 18.0.0, SVG Export, fails

### ISSUE THREAD

**Issue by Stardraw** [vvvv/SVG#116]
The SVG below was generated with Adobe Illustrator.

If I save this to a file and do:

Svg.SvgDocument.Open(file).Draw();

Then, it will fail
A first chance exception of type 'System.ArgumentException' occurred in System.Drawing.dll

Additional information: Value of '765' is not valid for 'alpha'. 'alpha' should be greater than or equal to 0 and less than or equal to 255.

at

var renderColor = System.Drawing.Color.FromArgb((int)(opacity \* stop.GetOpacity() \* 255), origColor);

This is because of the stop-opacity in:

stop  offset="1" style="stop-color:#FFFFFF;stop-opacity:3.000000e-002"

The code is incorrectly converting it to 3 rather than 0.03

I understand that the svg spec doesn't support exponent numbers, but should this library deal with real world svg's or should it only deal with perfect svg files?

One easy solution is to Max & Min it:

var renderColor = System.Drawing.Color.FromArgb((int)(Math.Max(0, Math.Min(1, opacity \* stop.GetOpacity())) \* 255), origColor);

If I fix this, then it fails in a similar location in SvgGradientServer:

colour = System.Drawing.Color.FromArgb((int)(mergedOpacity \* 255), currentStop.GetColor(this));

If I change this to:

colour = System.Drawing.Color.FromArgb((int)(Math.Max(0, Math.Min(1, mergedOpacity)) \* 255), currentStop.GetColor(this));

The SVG below is a cut down version of the actual file, but notice the line:

feColorMatrix  type="matrix" values="-1 0 0 0 1  0 -1 0 0 1  0 0 -1 0 1  0 0 0 1 0" color-interpolation-filters="sRGB" result="source"

Those matrix values have an additional space between each of the 4 values, which causes the following to fail in SvgColourMatrix:

var parts = this.Values.Split(new char[] { ' ', '\t', '\n', '\r', ',' });
...
colorMatrixElements[i] = parts.Skip(i \* 5).Take(5).Select(v => float.Parse(v)).ToArray();

I've fixed this by changing the first line to:

var parts = this.Values.Replace("  ", " ").Split(new char[] { ' ', '\t', '\n', '\r', ',' });

I'm sure I could keep patching the code to deal with rogue svg files, but I don't know if this is the right thing to do or somehow manually patch the svg files. What is the goal of this project? Perfection only? or real-world usage?
```
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 18.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
     viewBox="0 0 1627.1 2429.3" enable-background="new 0 0 1627.1 2429.3" xml:space="preserve">
<g id="_x31_4RR23">
    <g id="Front_Wheels">
        <g>
            <g>
                <circle cx="309" cy="2285.1" r="144.6"/>
                <radialGradient id="SVGID_1_" cx="308.9642" cy="2285.0579" r="144.5669" gradientUnits="userSpaceOnUse">
                    <stop  offset="0" style="stop-color:#FFFFFF;stop-opacity:0.73"/>
                    <stop  offset="1" style="stop-color:#FFFFFF;stop-opacity:3.000000e-002"/>
                </radialGradient>
                <circle fill="url(#SVGID_1_)" cx="309" cy="2285.1" r="144.6"/>
                <g>
                    <g>
                        <circle fill="#222222" cx="309" cy="2285.1" r="79.5"/>
                    </g>
                    <defs>
                        <filter id="Adobe_OpacityMaskFilter" filterUnits="userSpaceOnUse" x="229.4" y="2205.5" width="159.1" height="159.1">
                            <feColorMatrix  type="matrix" values="-1 0 0 0 1  0 -1 0 0 1  0 0 -1 0 1  0 0 0 1 0" color-interpolation-filters="sRGB" result="source"/>
                        </filter>
                    </defs>
                </g>
            </g>
        </g>
    </g>
</g>
</svg>
```
Hmm, I'm not sure how to display the whole svg file here in github. It seems to want to render it. Hopefully, I've provided enough information above to describe the problem.

**Comment by tebjan** [comment]
yes, it appears that you have some strange number values in your svg, like: 3.000000e-002

**Comment by Stardraw** [comment]
Agreed, as well as double spaces in the matrix value. This breaks the SVG Import.
As I presume we want great support for Adobe Illustrator, then the SVG Import code should change to accommodate it.

**Comment by tebjan** [comment]
should be an easy fix here:
https://github.com/vvvv/SVG/blob/master/Source/DataTypes/SvgUnitConverter.cs

and here:
https://github.com/vvvv/SVG/blob/master/Source/Transforms/SvgTransformConverter.cs

if you can fix it, please open a pull request. thanks!

**Comment by mrbean-bremen** [comment]
This has been fixed by @Stardraw long ago and works correctly now. Closing.
