### ISSUE TITLE
Lost resolution on SVG to PNG conversion between 1.6.0 and 1.7.0

### ISSUE THREAD

**Issue by axtens** [vvvv/SVG#117]
Today I updated Svg in my C# project from 1.6.0 to 1.7.0. Under 1.6.0 the PNG images I was generating faithfully reflected the complexity of the SVG images I was giving it to render. Now, in v1.7.0 I'm getting lower resolution images from the same SVG data.

Was there an API change? This is part of the code which I was using. What needs to be changed?

var svgs = document.getElementsByTagName("svg");
....
int svgsLength = svgs.length;
for (var i = 0; i < svgsLength; i++)
{
    var svgText = svgs[i].outerHTML;
    XmlDocument xd = new XmlDocument();
    xd.LoadXml(svgText);
    var sampleDoc = SvgDocument.Open(xd);
    ....
    var bitmap = sampleDoc.Draw();
    bitmap.Save(pngFile);
}

Sample SVG at http://pastebin.com/download.php?i=2HEWPg6E

**Comment by tebjan** [comment]
hello axtens, the pastebin appears to be private, i cannot see the code.

but what is the change exactly? how big was the resolution before and how bit is it now?

**Comment by mrbean-bremen** [comment]
Outdated and missing feedback - closing.
