### ISSUE TITLE
Unable to push modification - Help ?

### ISSUE THREAD

**Issue by EricOuellet2** [vvvv/SVG#119]
Hi,

I tried to apply one suggested modification but I'm unable to "push" from VS2013 to the repository. I always have this error message: "An error occurred. Detailed message: Response status code does not indicate success: 403 (Forbidden)".

I tried to change address
from : https://github.com/vvvv/SVG.git
to: https://EricOuellet2:myPassword@github.com/vvvv/SVG.git
Without success.

Anybody has a hint. That drives me crazy for a while now.

**Comment by EricOuellet2** [comment]
Please note that i'm new to git and that chnaging the address worked fine to do a "Clone".

**Comment by tebjan** [comment]
hello, you have to fork the repository. then you can push to your own fork and make a pull request from the fork to our repository. this page should guide you thru it: https://help.github.com/articles/using-pull-requests/

**Comment by EricOuellet2** [comment]
Thanks a lot. I found it be calling a collegue in another office. Thanks a lot. My pull request is already there. I hope I will remember this time ;-)
