### ISSUE TITLE
ViewBox with negative values.

### ISSUE THREAD

**Issue by arthek89** [vvvv/SVG#124]
Hello, I do not know whether I understand SVG drawing and transformations well enough, but when I open a SVG file which has negative values (minX,minY) in its ViewBox, the image is not displayed properly - it looks as if it was moved in upper left direction ( I can see a quarter of the image).

At the same time the SVG file which is very small is not sharp enough.

Is it my fault or the library one ? 

I would be grateful for your piece of advice.

**Comment by tebjan** [comment]
should be fixed now
