### ISSUE TITLE
handling events

### ISSUE THREAD

**Issue by ravjak** [vvvv/SVG#126]
Hi,
Could some provide a simple example code how to handle events from svg eg
```xml
<rect
       style="fill:#0fff00;fill-opacity:1;stroke:#001fff;stroke-width:3;stroke-linejoin:miter;stroke-miterlimit:4;stroke-opacity:1;stroke-dasharray:3, 3;stroke-dashoffset:0"
       id="rect3005"
       width="179.41844"
       height="63.248226"
       x="42.595745"
       y="35.97163"
       onmouseover="onMouseOver" />
```
C# handling events is sort of magic for me ;)

**Comment by tebjan** [comment]
this is not trivial, the svg render side has to call the events in c#. so you need to implement the ISvgCaller interface and register it. The project Posh is using it, you can have a look into the sources:

https://github.com/vvvv/Posh/blob/master/Source/PoshServer.cs#L315

**Comment by ravjak** [comment]
Thanks Tebjan. I was trying to do so, but without luck. Now I can see where the problem is.

**Comment by tebjan** [comment]
hope it works now. closing this for now.
