### ISSUE TITLE
SVG save/write functionality produces invalid SVG.

### ISSUE THREAD

**Issue by JoshMcCullough** [vvvv/SVG#129]
Test with this SVG: https://gist.github.com/JoshMcCullough/e01ab100147eba629875

Note that this SVG has some custom style properties. But there appears to be some weird issue where style attribute are broken out as "real" attributes.

Have a look at this source node:

```
<g class="highcharts-data-labels highcharts-tracker" visibility="visible" zIndex="6" transform="translate(10,10) scale(1 1)" opacity="1" clip-path="url(#highcharts-3)" style="">
    <g zIndex="1" style="cursor:default;" transform="translate(714,391)">
        <text x="0" zIndex="1" style="font-size:11px;font-weight:normal;color:#000;-hc-text-stroke:4px rgba(255,255,255,0.3);fill:#000;" y="12">
            <tspan x="0" stroke="rgba(255,255,255,0.3)" stroke-width="4px" stroke-linejoin="round" y="12">AL</tspan>
            <tspan x="0" y="12">AL</tspan>
        </text>
    </g>
    <!-- ... -->
</g>
```

After loaded and writen back out, it looks like this:

```
<g clip-path="url(#highcharts-3)" transform="translate(10, 10) scale(1)" xml:space="default" class="highcharts-data-labels highcharts-tracker" zIndex="6">
    <g clip-path="url(#highcharts-3)" transform="translate(714, 391)" xml:space="default" zIndex="1" cursor="default">
        <text xml:space="default" x="0 " y="12 " clip-path="url(#highcharts-3)" font-size="11px" font-weight="400" color="#000000" zIndex="1" -hc-text-stroke="4px rgba(255, 255, 255, 0.3)" style="fill:#000000;">
            <tspan xml:space="default" x="0 " y="12 " clip-path="url(#highcharts-3)" stroke="#FFFFFF" stroke-width="4px" stroke-linejoin="round">AL</tspan>
            <tspan xml:space="default" x="0 " y="12 " clip-path="url(#highcharts-3)">AL</tspan>
        </text>
    </g>
    <!-- ... -->
</g>
```

I would expect the output to be near-equal to the input, barring some clean up or removal of invalid SVG attributes, etc. But the output is very different...
1. `clip-path="url(#highcharts-3)"` is included not only in the outer group (correct), but also in the inner group and on every child within.
2. In the inner group, `cursor="default"` was pulled out of the `style` attribute and appears as its own attribute.
3. Almost all style attributes were pulled out of the style attribute on the text element.
4. In the first text span element, the stroke is no longer defines an opacity.
#1 I haven't looked into so I'm not sure why it's happening.
#2 and #3 can be fixed by cleaning up the SvgElement.WriteAttributes function.
#4 simply needs to consider opacity when writing colors out.

**Comment by mrbean-bremen** [comment]
2, 3 and 4 are still true.
