### ISSUE TITLE
When calling SvgDocument.Draw() it does not apply defined CSS styles

### ISSUE THREAD

**Issue by haykpetros** [vvvv/SVG#131]
SVG specification allows to use styling with CSS as it is describe in following link:

[Styling – SVG 1.1 (Second Edition)](http://www.w3.org/TR/SVG/styling.html)

So if we use following SVG as an example it will render properly everywhere (IE, Chrome, Firefox), but when `SvgDocument.Draw()` is called it will output black rectangle without applying CSS that is defined:

``` SVG
<svg version="1.1" xmlns="http://www.w3.org/2000/svg">
    <defs>
        <style type="text/css">
            <![CDATA[rect {
                fill: silver;
                stroke: red;
                stroke-width:1;
            }
            ]]>
        </style>
    </defs>
    <rect x="100" y="100" width="50" height="50" />
</svg>
```

**Comment by mrbean-bremen** [comment]
This works ok now - closing.
