### ISSUE TITLE
SVG file with non-integer gaussian blur not spported

### ISSUE THREAD

**Issue by Weakegg** [vvvv/SVG#134]
When reading a SVG file with a gaussian blur of non integer std-deviation, for example:

```
<feGaussianBlur
         stdDeviation="2.67857143"
         id="feGaussianBlur3814" />
```

the SvgDocument.Open call will result in an exception (because only integer values seem to be supported here.)

This can be tested with the svg example file from http://dev.w3.org/SVG/tools/svgweb/samples/svg-files/ with the file "car".

**Comment by mrbean-bremen** [comment]
Works fine now - closing.
