### ISSUE TITLE
Conversation Issue

### ISSUE THREAD

**Issue by yessource** [vvvv/SVG#136]
Hi, 
I tried to conversation some text over the svg which is working perfectly. But once i tried to convert svg to png, Generating different images then what actually having in svg. 

Can someone look over the files. 

![pngfile](https://cloud.githubusercontent.com/assets/11401422/6569150/bb74ee86-c70c-11e4-9743-ea6ddedb1d6f.png)

SVG File link found in : https://www.dropbox.com/s/39anx7zswz2xnac/svgFile.svg?dl=0

Regards
Yes

**Comment by yessource** [comment]
I wasn't able to upload SVG so please here is the text. 
<svg width="360.0000286102295" height="216.0000171661377" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 360.0000286102295 216.0000171661377"><g><title>background</title><rect x="0" y="0" width="336.00003" height="192.00002" stroke-width="0" id="canvas_background" fill="#FFFFFF"/></g><defs><path fill="#FFFFFF" stroke="#FFFFFF" d="m97.47272,36.96559q118.65001,-0.1 237.34952,0.01" id="svg_9"/><path fill="#0000FF" stroke="#0000FF" d="m101.3102,64.95473q115.94999,-0.1 231.8964,0.01" id="svg_12"/></defs><g transform="translate(12.000000953674316,12.000000953674316)"><title>Layer 1</title><g id="svg_4" display="null" stroke="null"><g id="svg_5" stroke="null"><path fill-rule="evenodd" fill="#0000FF" d="m56.18613,12.16012c-24.42952,0 -44.25507,19.8264 -44.25507,44.25423c0,24.42951 19.82555,44.25423 44.25507,44.25423c24.42616,0 44.25087,-19.82471 44.25087,-44.25423c0.00085,-24.42784 -19.82388,-44.25423 -44.25087,-44.25423zm0,88.2958l-44.04324,-44.04156l44.04324,-44.04156l44.03989,44.04156l-44.03989,44.04156zm0.03445,-54.09599l-10.12502,10.05442l10.12502,10.05441l10.05274,-10.05441l-10.05274,-10.05442z" id="svg_6" stroke="#FFFFFF"/></g></g><text fill="#0000FF" stroke-width="0" x="0" y="0" id="svg_7" font-size="24" font-family="Arial" text-anchor="middle" xml:space="preserve" font-weight="bold" curveVal="0.04" multiLine="false" pathX="97.47272" pathY="36.96559" stroke="#0000FF" display="null" transform="matrix(0.698836, 0, 0, 0.698836, 97.3434, 3.74706)"><textPath id="svg_8" startOffset="48%" xlink:href="#svg_9">Your Company Here</textPath></text><text fill="#0000FF" stroke-width="0" x="0" y="0" id="svg_10" font-size="24" font-family="Arial" text-anchor="middle" xml:space="preserve" font-weight="bold" curveVal="0.04" multiLine="false" pathX="101.31956" pathY="64.94364" transform="matrix(0.517614, 0, 0, 0.517614, 156.703, 14.5589)" stroke="#FFFFFF" display="null"><textPath id="svg_11" startOffset="48%" xlink:href="#svg_12">Your Message Here</textPath></text><text fill="#0000FF" stroke-width="0" x="7.19765" y="112.72507" id="svg_13" font-size="24" font-family="Arial" text-anchor="start" xml:space="preserve" font-weight="normal" multiLine="true" transform="matrix(0.551938, 0, 0, 0.551938, 9.08292, 82.3192)" stroke="#0000FF" lineHeight="0.8" display="null"><tspan id="svg_31" x="7.19765" y="112.72507">Your Name Here</tspan><tspan id="svg_32" x="7.19765" y="139.58529">Your Title Here</tspan><tspan id="svg_33" x="7.19765" y="166.44552">email: name@company.com</tspan></text><text fill="#0000FF" stroke-width="0" x="185.4345" y="19.91278" id="svg_34" font-size="24" font-family="Arial" text-anchor="start" xml:space="preserve" font-weight="normal" multiLine="true" transform="rotate(-90, 292.056, 129.284) matrix(0.437153, 0, 0, 0.437153, 166.656, 105.712)" stroke="#FFFFFF" lineHeight="0.8" display="null"><tspan id="svg_75" x="185.4345" y="19.91278">Address</tspan><tspan id="svg_76" x="185.4345" y="46.78724">City, State, Zip</tspan><tspan id="svg_77" x="185.4345" y="73.66171">ph: 000-000-0000</tspan><tspan id="svg_78" x="185.4345" y="100.53617">fx: 000-000-0000</tspan><tspan id="svg_79" x="185.4345" y="127.41063">www.company.com</tspan></text></g><g><title>Border</title><rect x="6" y="6" width="336.00003" height="192.00002" stroke="#FFFFFF" stroke-width="0" id="canvas_border" fill="none"/></g></svg>

**Comment by mrbean-bremen** [comment]
Closing the issue. Please reopen if this is still an issue and you can provide the example file.
