### ISSUE TITLE
linearGradient not exported correctly if id begins with number

### ISSUE THREAD

**Issue by epuig-ssinergie** [vvvv/SVG#138]
When saving SvgDocument to PNG, the gradient area is rendered as solid black.

After several tests, it seems to be directly related to the linearGradient which is beginning with a number, eg:
<linearGradient id="41cb5de8-82e7-4ab5-94d7-87e10775c848"

![ko2](https://cloud.githubusercontent.com/assets/7677220/6708440/8bb2f62e-cd70-11e4-9107-c9e15233c195.png)

As a workaround i'm just adding a letter at the beginning of id and it works perfectly.

![ok1](https://cloud.githubusercontent.com/assets/7677220/6708439/8a4c96e6-cd70-11e4-8700-d4310b15a53e.png)

Thanks

**Comment by epuig-ssinergie** [comment]
same issue with <radialGradient> elements

**Comment by mrbean-bremen** [comment]
According to W3C, an id name cannot start with a number, so this is not a valid SVG - not supporting this is not a bug.
Is there any standard application that generates this kind of ids? In this case, it may make sense to support this nonetheless.

**Comment by epuig-ssinergie** [comment]
svg was generated using ASP.net Telerik library with getSVGString()
https://www.telerik.com/support/code-library/exporting-radhtmlchart-to-png-and-pdf

**Comment by mrbean-bremen** [comment]
Ok, thanks - while this is basically a bug in the converter, it would make sense to handle this in that case.
