### ISSUE TITLE
Can someone who has access to NuGet API Key update the package

### ISSUE THREAD

**Issue by haykpetros** [vvvv/SVG#139]
It seems that there were several important fixes since version 1.7.0 but NuGet package is still old. So can some one who has access to NuGet API Key actually update the package?

**Comment by tebjan** [comment]
sure, wanted to do that a while ago but i fear it will not be completely backwards compatible... but let's just do it.

**Comment by tebjan** [comment]
version 2.0.0 is now on nuget
