### ISSUE TITLE
System.Drawing abstraction

### ISSUE THREAD

**Issue by paulpatarinski** [vvvv/SVG#141]
I know this is probably a silly question, but I am trying to make a Cross Platform SVG Library and I am wondering how much work would it be to Abstract the System.Drawing dependency, so that the drawing is done through an interface (adding the ability to inject an instance per platform)? Cheers

**Comment by tebjan** [comment]
The hope is that mono already did an abstraction for system.drawing and you can use it with the mono runtime. but never tried it.

**Comment by jonthysell** [comment]
I've tried it - the Mono implementation of System.Drawing leaves a lot to be desired and made for a poor solution when using SVG.NET.

From http://chordious.com/2015/02/22/chordious-and-winform-woes/ 

"Of the two, SVG.NET is both the more robust and actively maintained. For Windows, it represents as fairly solid replacement for librsvg. However, on Mono, it just doesn’t want to cooperate. Text won’t render. Basic shapes, if they render at all, render as solidly filled with black every time, no matter what I do."

Sorry if it sounds like I was slamming SVG.NET back then. I was spoiled by librsvg and was frustrated that my UI plans weren't working out. I totally love this lib - it's the default option in my Chordious app and works beautifully. I loathe the work I'll have to do to find a replacement to run on Windows Phone, which also doesn't have System.Drawing.

**Comment by ds1709** [comment]
I don't know how much hard is this enhancement, but fist of all it could be like this. Intead of using System.Drawing.Graphics it will be an interface (e.g. `ISvgRenderer`) with basic methods, such as `RenderLine`, `RenderRectangle`, `RenderText` and others. And there will be an implementation of this interface in external assembly, referenced to System.Drawing and aggregating Graphics functionality. It will be enough for a first time, and another implementations can be make in future.

**Comment by mrbean-bremen** [comment]
I think this is something we will not do ourselves - supporting [NetStandard](https://github.com/vvvv/SVG/issues/346) or [SkiaSharp](https://github.com/vvvv/SVG/issues/291) is the way to go.
Closing.

**Comment by chucker** [comment]
The System.Drawing lacks some of the features currently used by this lib, but I haven’t found anything significant. Rendering on macOS mostly works (in the Branch where that porting work has been done); I haven’t tried on Linux but am guessing it does.
