### ISSUE TITLE
SVG titles are currupted

### ISSUE THREAD

**Issue by aamirhabibkhan** [vvvv/SVG#149]
Generated Image:
https://dl.dropboxusercontent.com/u/70688512/e5bdc642-3855-452e-85bb-d68ec77a2ae8.jpeg

SVG used for this:
https://dl.dropboxusercontent.com/u/70688512/svg.svg

Can you please fix it?

**Comment by mrbean-bremen** [comment]
@aamirhabibkhan - is this still an issue? If yes (yes, it was a long time ago...), can you re-attach the failing svg? The link is no longer valid.

**Comment by mrbean-bremen** [comment]
Closing the issue. Please reopen if this is still an issue and you can provide the failing file.
