### ISSUE TITLE
Changing Text property of SvgText doesn't have an effect

### ISSUE THREAD

**Issue by constantable** [vvvv/SVG#151]
Just updated library to 2.0.0

Sample code:

``` csharp
XmlDocument xml = new XmlDocument();
xml.LoadXml(
    "<svg xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" width=\"400\" height=\"400\" font-size=\"20\">" +
    "<text id=\"id1\" x=\"100\" y=\"100\">Test</text></svg>");

var sampleDoc = SvgDocument.Open(xml);
sampleDoc.GetElementById<SvgText>("id1").Text = "Test Output";
sampleDoc.Write(@"c:\output.svg");
```

**Comment by MoeHamdan** [comment]
Hello may you please fix this is? It is critical in the project I am working on.
Thank you in advance.

**Comment by hwndmaster** [comment]
Faced the same problem. Fixed through the SvgContentNode element inside a SvgTextSpan, as follows:

```c#
SvgText node = ...
node.Children.Clear();
node.Children.Add(new SvgTextSpan {
    Nodes = {
        new SvgContentNode { Content = text }
    }
});
```

**Comment by Threetwosevensixseven** [comment]
Nice one, hwndmaster :)

**Comment by MoeHamdan** [comment]
Thanks for your reply, but unfortunately it did not work. When I use the GetXML() method it returns the data that has been loaded initially. (Same when I use the Draw() method)

**Comment by pushasha** [comment]
For me, changing the `Text` property setter in `SvgTextBase` to the following fixed the issue (changes start after comment):
```csharp
set
{
	base.Content = value; 
	this.IsPathDirty = true; 
	this.Content = value;

	// get this element's SvgContentNode and set its Content value
	SvgContentNode contentNode = GetContentNodes().FirstOrDefault() as SvgContentNode;
	if (contentNode == null)
		return;

	contentNode.Content = value;
}
```
I haven't put up a pull request for this, however, because I'm not sure if `SvgTextBase` can have multiple content nodes. Anyone know of a situation where that might happen? Multiple spans?
