### ISSUE TITLE
SVG load corrupts thread current culture

### ISSUE THREAD

**Issue by hujerhoe** [vvvv/SVG#152]
When changing current culture to invariant please use try {} finally {};

Im guessing the cause of the issue is SvgColourConverter and method ConvertFrom. At the start it changes thread culture to invariant but in many cases doesnt restore the original culture and just returns.

If needed i can provide a patch.

**Comment by tebjan** [comment]
hope this is closed now with the mentioned pull request. otherwise please reopen it.
