### ISSUE TITLE
Line endings problem

### ISSUE THREAD

**Issue by ikolev21** [vvvv/SVG#155]
I tried loading an .svg file with Windows line endings on OS X and SvgDocument.Open hanged. Converting the line endings to Unix style fixed it.

**Comment by ikolev21** [comment]
Follow up: Loading a file with Unix line endings on Windows works fine. This simplifies the workaround for me, all svg files will be kept with Unix line endings.

**Comment by mrbean-bremen** [comment]
I don't have a Mac, so I can't test this - is this still an issue? I'm also not sure if this an SVG bug or a Mono problem. Has oneone more information about this?

**Comment by ikolev21** [comment]
Could not reproduce it.
It was probably a Mono problem, Mono has changed a lot for the past 3 years. And we never upgraded Svg.NET, we're still at 2.0.0 (I see there's 2.3.0 at NuGet).
