### ISSUE TITLE
shape-rendering attribute not supported

### ISSUE THREAD

**Issue by invinctus** [vvvv/SVG#161]
Circle, Ellipse, Polygon, Rectangle (with corner rads) and paths all force anti aliasing on This is the case even if you create the graphics object manually and specify a different smoothing mode.

They don't honour the [shape-rendering](http://www.w3.org/1999/07/06/WD-SVG-19990706/render.html#ShapeRenderingProperty) attribute.

**Comment by tebjan** [comment]
hope this is closed now with the mentioned pull request. otherwise please reopen it.
