### ISSUE TITLE
Entities

### ISSUE THREAD

**Issue by ada3m0n666** [vvvv/SVG#162]
Hello,

Entities written like this &entity1; is now crashing with the new version (2.0).

What is the new way to write entity ?

Thank you

**Comment by mrbean-bremen** [comment]
Is this still an issue? Can you clarify what do mean by entities - something like `&amp;` or `&quote;` seems to work.

**Comment by mrbean-bremen** [comment]
Closing the issue. Please reopen if this is still an issue and you have more information.
