### ISSUE TITLE
Infinite loop in SvgRadialGradientServer CalcScale

### ISSUE THREAD

**Issue by durlandd** [vvvv/SVG#163]
CalcScale will fall into an infinite loop if transform.TransformPoints(points) fails to produce points that are visible in the Path. There is a known issue with Path.IsVisible as demonstrated by the following test. Also a raw svg document is below that will expose the issue.

public void TestGraphicsPath() {
    using (var gp = new GraphicsPath()) {
        gp.AddLines
        (
            new PointF[]
            {
                new PointF(0f,0f),
                new PointF(1f,0f),
                new PointF(1f,1f),
                new PointF(0f,1f),
                new PointF(0f,0f),
            }
        );

```
    Assert.True(gp.IsVisible(new PointF(-.2f, -.2f)));
    Assert.True(gp.IsVisible(new PointF(.2f, .2f)));
    Assert.False(gp.IsVisible(new PointF(.7f, .7f)));
}
```

}

<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
     viewBox="0 0 504.6 649.1" enable-background="new 0 0 504.6 649.1" xml:space="preserve">
<desc>3DVIA Composer Export</desc>
    <g opacity="0.25">

```
    <radialGradient id="SVGID_5_" cx="-5.000145e-003" cy="7.518895e-002" r="8.4726" gradientTransform="matrix(1.000000e-004 0 0 -1.000000e-004 9.843900e-003 6.090040e-003)" gradientUnits="userSpaceOnUse">
        <stop  offset="0" style="stop-color:#E3E1DE"/>
        <stop  offset="0" style="stop-color:#F0EEED"/>
        <stop  offset="0" style="stop-color:#FFFFFF"/>
        <stop  offset="0.1403" style="stop-color:#F0F0F0"/>
        <stop  offset="0.4082" style="stop-color:#C9C9C9"/>
        <stop  offset="0.5225" style="stop-color:#B7B7B7"/>
        <stop  offset="0.5782" style="stop-color:#ADADAD"/>
        <stop  offset="0.672" style="stop-color:#939393"/>
        <stop  offset="0.7924" style="stop-color:#686868"/>
        <stop  offset="0.9333" style="stop-color:#2E2E2E"/>
        <stop  offset="1" style="stop-color:#0F0F0F"/>
    </radialGradient>
    <circle fill="url(#SVGID_5_)" stroke="#A7A7A7" stroke-width="0.2904" cx="0" cy="0" r="8.5"/>
</g>
```

</svg>

**Comment by mrbean-bremen** [comment]
Fixed with #164.
