### ISSUE TITLE
A Wiki page is too much to ask?

### ISSUE THREAD

**Issue by Leon-O** [vvvv/SVG#165]
Please we need a wiki page where we can see some examples. 

Thanks you.

**Comment by tebjan** [comment]
what kind of examples are you thinking of?

**Comment by Leon-O** [comment]
*Create SVG from code, from other image.
*Create image from SVG code, for SVG Files
*How to use the library (methods, objects, properties, configurations,...)

**Comment by danielwalls** [comment]
I second this suggestion. It would save a lot of time for a newcomer to the library and for those who wish to contribute it would go some way towards explaining your design philosophy and approach.

Another example that would be helpful:
* What's the recommended way to spit out the SVG as a string.

**Comment by mmmeff** [comment]
Agreed, I recently picked this library up for a project and was surprised at the lack of documentation. I ended up learning it with nothing but the library's source.

Make it publicly editable and I'm sure enough people would pitch in with their experiences to make it worthwhile.

**Comment by mmmeff** [comment]
First example I'd add is how to tell if an element is a polygon, rectangle, circle, etc. I think I spent an entire day scratching my head before realizing it was a type check.

**Comment by tebjan** [comment]
please refer in this matter to https://svg.codeplex.com/ we just made a fork of this library and developed it further. we do not claim to have made any major design decisions neither do we plan to own any money from it which would enable us to invest manpower into documentation.

**Comment by mmmeff** [comment]
A wiki doesn't require YOU to document it, it lets US document it. That's kind of the whole point of Github.

**Comment by tebjan** [comment]
if that's an integrated feature i am of course glad to enable it right away!

**Comment by tebjan** [comment]
does this help in some way? https://github.com/vvvv/SVG/wiki

**Comment by mmmeff** [comment]
:+1:

**Comment by mmmeff** [comment]
I'll be sure to contribute a few examples of things I got stuck on in the coming days
