### ISSUE TITLE
Sub elements in group element are not rendered

### ISSUE THREAD

**Issue by ubbn** [vvvv/SVG#173]
Transformed element's original position is considered for boundary. It should not consider transformed element's original position for boundary and position. 

For example, below transform attribute move the original element to new position which is only to be considered for boundary
 < g transform="matrix(1.0001333,0,0,1.0001333,-56.728562,46.406995)" >
... any element
< / g >

**Comment by Sonorpearl** [comment]
Hey ubbn,

can you explain a bit more, what do you mean by that Problem?
Which attributes are considered and which not?
And how should the final consideration look like?

**Comment by ubbn** [comment]
Simple SVG text example to show the problem. Both SVG are correct and render same rotated text. But this SVG lib can not render first SVG because of group element. 


```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg version="1.1" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg">
<defs>
<symbol id="text" overflow="visible">
<g transform="translate(60,20) rotate(-90)">
<text style=" font-family: Arial; font-size: 100px;fill: #000000; fill-opacity: 1; text-anchor: middle;" >Vertical</text>
</g>
</symbol>
</defs>
<use xlink:href="#text" />
</svg>
```

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg version="1.1" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg">
<defs>
<symbol id="text" overflow="visible">
<text transform="translate(60,20) rotate(-90)" style=" font-family: Arial; font-size: 100px;fill: #000000; fill-opacity: 1; text-anchor: middle;">Vertical</text>
</symbol>
</defs>
<use xlink:href="#text" />
</svg>
```

![new rotated](https://cloud.githubusercontent.com/assets/1505531/8956106/f3cf63ce-35f2-11e5-8a3b-9a9860c13c35.png)

**Comment by Sonorpearl** [comment]
Yea thats probably the Problem I am facing. ( #169 )
It would be very nice if anyone could fix this.

**Comment by ubbn** [comment]
After some tests, it was revealed that it is not only about transform attribute in group element, but sub elements in group element were not considered for rendering.
