### ISSUE TITLE
Help managing events

### ISSUE THREAD

**Issue by Bukran** [vvvv/SVG#177]
I've seen there are some events inside SvgElement class: Click, MouseOver, etc. 
How are they triggered if the user sees the SVG through a Bitmap/Graphics object? 
Is there any other way to display the SVG and make it user-responsive? 

I need to know which SvgElement does the user click on. Get the ID attribute. 

Thanks in advance.

**Comment by tebjan** [comment]
please have a look here: https://github.com/vvvv/SVG/issues/126
