### ISSUE TITLE
Cannot convert SVG to image

### ISSUE THREAD

**Issue by AyrA** [vvvv/SVG#178]
I havetrouble converting [this image](https://upload.wikimedia.org/wikipedia/commons/3/32/Telefunken_FuBK_test_pattern.svg) into a png. Some elements seem to be off-place.

According to the W3 validator it seems to be a valid SVG. [Link](https://validator.w3.org/check?uri=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2F3%2F32%2FTelefunken_FuBK_test_pattern.svg&charset=%28detect+automatically%29&doctype=Inline&group=0)

The image shows fine in browsers and opens in inkscape. I tried saving it again in inkScape just to regenerate the SVG source, but it did not help.

For other SVG images ([example](https://upload.wikimedia.org/wikipedia/commons/6/60/SMPTE_Color_Bars_16x9.svg)) drawing works fine.

Code used to draw:

    Svg.SvgDocument Doc = Svg.SvgDocument.Open(getXml(bytes));
    Doc.Draw(B);

`B` is a bitmap (this is definitely initialized).
`bytes` is an array of bytes representing the SVG content

The function to get an XML out of it (`getXml`) is as below:

    private static System.Xml.XmlDocument getXml(byte[] p)
    {
        string s = Encoding.UTF8.GetString(p);
        XmlDocument D = new XmlDocument();
        D.LoadXml(Encoding.UTF8.GetString(p));
        return D;
    }

I have also tried other "Draw" overloads, with Graphics and the SvgRenderer class, but both yield the same result.

**Comment by tebjan** [comment]
works with latest code base, thanks for reporting
