### ISSUE TITLE
Any way to convert matrixes?

### ISSUE THREAD

**Issue by mmmeff** [vvvv/SVG#184]
How can you take an SvgMatrix and convert/break it into SvgShear, SvgRotate, and SvgTranslate values?

**Comment by tebjan** [comment]
hi @mmmeff the Shear/Rotate/... are specialized transforms which all result in a SvgMatrix that is applied to the transformation chain. however, there are mathematical ways to decompose a 2D matrix into its transformation elements. have a look here for example:
http://stackoverflow.com/questions/20422392/given-a-2d-transformation-matrix-how-to-calculate-the-scalings-skews-rotation

or here:
http://www.maths-informatique-jeux.com/blog/frederic/?post/2013/12/01/Decomposition-of-2D-transform-matrices

as far as i know, the decomposition does not work if you have shear applied in the matrix.

**Comment by mmmeff** [comment]
Ah, yeah it's definitely a very tough problem.I'm using Illustrator to generate my SVG then doing processing with this library, but Illustrator outputs pure matrixes on every simple transformation, making the x,y coords and other things impossible to work with. I opted instead with the following solution to make everything more workable.

1. Take every element with a transform, copy the matrix, then remove it from the element.
2. Take the element, and convert it to a polygon if it isn't already a polygon.
3. Apply the matrix to the path of the element, updating the actual point x,y values for the element.

Example: applying a rotation matrix to an element's path:
```
            var path = element.Path(null);

            var matrix = new SvgRotate(angle, centerX, centerY).Matrix;
            path.Transform(matrix);

            element.Points = new SvgPointCollection();
            foreach (var point in path.PathPoints)
            {
                element.Points.Add(new SvgUnit(point.X));
                element.Points.Add(new SvgUnit(point.Y));
            }
```
