### ISSUE TITLE
Current nuget package v2.0 is not strong name signed

### ISSUE THREAD

**Issue by erdmenchen** [vvvv/SVG#193]
Same issue as https://github.com/vvvv/SVG/issues/49
But since there is no comment from the author in the old ticket, this issue is submitted again.

Please sign the current version 2.0 and any following with a strong name key file.
Otherwise this dll is not usable in projects with strong names :-(

**Comment by tebjan** [comment]
my bad, forgot to compile it with the key. will upload a new version. thanks!

**Comment by erdmenchen** [comment]
Perfect! Thank you very much for your work!

**Comment by erdmenchen** [comment]
@tebjan Can you tell me, from when it is available via nuget?

**Comment by tebjan** [comment]
its up now, please test and close this issue if it works for you.

**Comment by erdmenchen** [comment]
Works for me, thank you for the quick response. Keep the good work up!
