### ISSUE TITLE
Please update NuGet pacakge

### ISSUE THREAD

**Issue by haykpetros** [vvvv/SVG#194]
Hi,

I recently ran into an issue with specific SVG. But before submitting a bug decided to test it with latest version to discover that it works just fine.

I guess a lot has been fixed/updated/improved since NuGet Package 2.0.0 was released back in March 23 2015, so I was wondering if it can be updated?

Thanks

**Comment by tebjan** [comment]
should be up now, please test and close this issue afterwards.

**Comment by haykpetros** [comment]
SVG Rendering Library 2.1.0 addressed this problem. Thanks you!
