### ISSUE TITLE
Culture possibly not restored due to exception

### ISSUE THREAD

**Issue by Moolie** [vvvv/SVG#200]
In this package, the Thread.CurrentThread.CurrentCulture is frequently changed to InvariantCulture and restored later on (in the same function). However, in the meanwhile an exception can occur, and in such cases the old culture is not restored. If your CurrentCulture and the InvariantCulture don't overlap much, this bug will be more obvious. E.g. with my culture, nl-NL, the decimal separator and thousand separator change.

Fix by using try ... finally:

    var oldCulture = Thread.CurrentThread.CurrentCulture;
    Thread.CurrentThread.CurrentCulture = System.Globalization.CultureInfo.InvariantCulture;
    try {
        // All code between setting and resetting the CurrentCulture should be in the try block
        ...
    } finally {
        Thread.CurrentThread.CurrentCulture = oldCulture;
    }

**Comment by tebjan** [comment]
hope this is closed now with the mentioned pull request. otherwise please reopen it.
