### ISSUE TITLE
Wikipedia US flag shows only one star at the center of blue field. Stripes are OK.

### ISSUE THREAD

**Issue by yschkatula** [vvvv/SVG#202]
https://en.wikipedia.org/wiki/File:Flag_of_the_United_States.svg
SVGViewer example renders the following:
![output](https://cloud.githubusercontent.com/assets/1890043/10315318/3ffac59a-6c62-11e5-9dfd-14ab17ca1863.png)

Inkscape renders the same file correctly.

**Comment by mrbean-bremen** [comment]
@tebjan - this one can be closed. I don't know when it was fixed, but I already added the respective test which is passing.

**Comment by mrbean-bremen** [comment]
see above
