### ISSUE TITLE
bug with Thread.CurrentThread.CurrentCulture

### ISSUE THREAD

**Issue by DevilPF** [vvvv/SVG#203]
In SvgPathBuilder.cs, SvgExtentions.cs, SvgDocument.cs and SvgColourConverter.cs you use construction when you change CultureInfo of current thread, do some work and return it back ... but unfortunately it's not even in try-finally clausule, so on many occasions it is not returned!
In SvgColourConverter.cs/ConvertFrom it is even skipped because of the return before - so the calling thread ends up with changed CultureInfo. I'm not even sure why do you need to change it this way - all converts have CultureInfo parameter to override that of the calling thread.

**Comment by tebjan** [comment]
looks like an error, could you provide a pull request with the fixes?

**Comment by DevilPF** [comment]
Hi, I'm quite new to GIT and not sure how to make branches, pull requests and all that stuff. It will be faster if I'll just give you the new versions: https://dl.dropboxusercontent.com/u/591980/Source.zip

**Comment by tebjan** [comment]
hope this is closed now with the mentioned pull request. otherwise please reopen it.
