### ISSUE TITLE
Any way to load custom fonts when calling SvgDocument.Draw?

### ISSUE THREAD

**Issue by mmmeff** [vvvv/SVG#204]
We need to load custom fonts for rendering images, but I can't find any way to pass a System.Drawing PrivateFontCollection into the rendering - it looks like there's a hardcoded reference to System.Drawing.FontFamily.Families here, blocking out the ability to load custom fonts from disk/memory.

Given our deployment scenario, we cannot simply install the font into Windows to add the custom font to the drawing context and it seems like a PrivateFontCollection is the only exposed interface that would allow us to do so.

Is there some other way I'm missing? Or will this require a refactoring of SvgElementStyle's ValidateFontFamily method? https://github.com/vvvv/SVG/blob/44173b47e29429f98db60413f5058b016d1024f4/Source/SvgElementStyle.cs#L386

**Comment by tebjan** [comment]
hope this is closed now with the mentioned pull request. otherwise please reopen it.
