### ISSUE TITLE
Save as SVG file

### ISSUE THREAD

**Issue by seekM** [vvvv/SVG#205]
We would like to do read a SVG from a SVG file, manipulate it and then save it again as a SVG file. Is the latter possible? We tried 'mySvgDoc.Write("c:/temp/meineSvg.svg")' but it does not seem to do anything. We also found https://github.com/vvvv/SVG/blob/master/Samples/RuntimeUpdates/Program.cs as an example for saving a SVG as a PNG, but simply substituting '.png' by '.svg' does not work. Is there something obvious we are missing?

**Comment by tebjan** [comment]
you know that windows uses backslash as path path delimiter, right?

and you need to escape the backslash, so try:
mySvgDoc.Write(@"c:\temp\meineSvg.svg")

**Comment by imbecile1** [comment]
HI tebjan,

ich arbeite am mit seekM zusammen an dem Project, das Problem liegt nicht an den backslash ( das wissen wir eigentlich. Evtl. kann ich dir das Problem an dem Samples Project Entities zeigen.

Wenn ich da versuche da Bild nicht nur als png abzuspeichern sondern, dann auch als ein neues SVG nachdem es verändert wird, erhalte ich aber keine neue SVG datei mit dem Namen "sampleNew.svg".

Wir würde jetzt gern wissen, sind irgend welche Attribute falsch übergeben oder müssen wir irgend was anderes beachten.

Denn wir benötigen halt eine neue SVG.

namespace Entities
{
    class Program
    {
        static void Main(string[] args)
        {
            string filePath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, @"..\..\sample.svg");

            var sampleDoc = SvgDocument.Open(filePath, new Dictionary<string, string> 
                {
                    {"entity1", "fill:red" },
                    {"entity2", "fill:yellow" }
                });
            sampleDoc.Draw().Save(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, @"..\..\sample.svg"));
            
            sampleDoc.Write(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, @"..\..\sampleNew.svg"));
        }
    }
}

Danke für die Hilfe.
Bye

**Comment by tebjan** [comment]
any exception when writing the file? should just work... does it work if you pass no entities?

**Comment by imbecile1** [comment]
there is no exception and we have try it without entities, but it works not

**Comment by tebjan** [comment]
Can you make a pastebin with the svg code you are trying to load? Would be interesting what goes wrong...

**Comment by seekM** [comment]
imbecile1 told me that the problem occurred due to using an old DLL from codplex.com. He resolved the issue now. Thanks a lot for your help!
