### ISSUE TITLE
Text placed incorrectly - possible fix

### ISSUE THREAD

**Issue by phissionmailed** [vvvv/SVG#206]
I ran into a problem where text was being placed incorrectly when using SvgDocument.Draw(Graphics). 

It all boiled down on resolution. If you change the resolution of the output image, text will be rendered in the wrong places.

In my case, I changed class GdiFontDefn, method Ascent. I changed the return statement from

``` c#
return renderer.DpiY / 72f * baselineOffset;
```

to

``` c#
return 96f / 72f * baselineOffset;
```

Interestingly, 96 is the default resolution. I know it's a hardcoded solution, but it works regardless of the resolution you set your output image to.

I didn't test the other overloads after this change, but hopefully it can give the devs a starting point to debug the problem.

Quick example to replicate the problem.

``` c#
//Ensure the SVG has at least one text node.
//This is the one I tested with:
//<text stroke="black" y="300" x="396" text-anchor="middle" font-family="Arial" font-weight="bold" font-size="36" font-style="italic" >TEST</text>
var svg = SvgDocument.FromSvg<SvgDocument>(File.ReadAllText("SVG file path"));

using (var bmp = new Bitmap(6600, 5100))
{
    svg.Height = new SvgUnit(SvgUnitType.Pixel, bmp.Height);
    svg.Width = new SvgUnit(SvgUnitType.Pixel, bmp.Width);

    bmp.SetResolution(600, 600);

    using (var graphics = Graphics.FromImage(bmp))
    {
        svg.Draw(graphics);
    }

    bmp.Save("PNG file path", ImageFormat.Png);
}
```

**Comment by mrbean-bremen** [comment]
Shall be fixed in the current version - closing.
Please reopen if there are still problems.
