### ISSUE TITLE
Poor performance with big files - Possible fix

### ISSUE THREAD

**Issue by phissionmailed** [vvvv/SVG#208]
One of the SVG files I'm working with is 5MB and has a lot paths to draw. I noticed the library was basically hanging when processing this file.

I had to change method AddToPath in class SvgClosePathSegment to the following.

``` c#
        public override void AddToPath(System.Drawing.Drawing2D.GraphicsPath graphicsPath)
        {
            // Important for custom line caps.  Force the path the close with an explicit line, not just an implicit close of the figure.
            //if (graphicsPath.PointCount > 0 && !graphicsPath.PathPoints[0].Equals(graphicsPath.PathPoints[graphicsPath.PathPoints.Length - 1]))
            //{
            //    int i = graphicsPath.PathTypes.Length - 1;
            //    while (i >= 0 && graphicsPath.PathTypes[i] > 0) i--;
            //    if (i < 0) i = 0;
            //    graphicsPath.AddLine(graphicsPath.PathPoints[graphicsPath.PathPoints.Length - 1], graphicsPath.PathPoints[i]);
            //}
            graphicsPath.CloseFigure();
        }
```

I noticed the code was doing some extra processing to close the figure, it seems. However, the code was already calling method CloseFigure, which should take care of closing the figure automatically.

I did notice the comment about "custom line caps". Not entirely sure what that means. If the code I commented is necessary, maybe another approach can be found that does not affect performance when working with big files?

Tested with my other images and the processing is fast again, even with big files.

**Comment by mrbean-bremen** [comment]
This has been fixed by @LightningDragon some time ago - closing.
