### ISSUE TITLE
Orientation reversed for marker-end marker

### ISSUE THREAD

**Issue by bamboovn** [vvvv/SVG#215]
Hello everyone,
I use SVG to convert SVG to PNG. but text quality inside SVG is bad... How to increase text quality ?
Thank you :)

![image](https://cloud.githubusercontent.com/assets/4629813/12715293/1d248f86-c90c-11e5-9ea9-cae6be7242fa.png)

**Comment by jarrettv** [comment]
I also see this problem. Any fix?

**Comment by Sudnik** [comment]
![error](https://cloud.githubusercontent.com/assets/15186126/15429383/65f8900c-1ea9-11e6-9502-581acb564e37.png)
Same problem + arrow tips have the wrong direction. Must be:
![mustbe](https://cloud.githubusercontent.com/assets/15186126/15429494/dad59906-1ea9-11e6-8014-2687a95c53a8.png)
Current svg:
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" height="300" version="1.1" width="400" style="overflow: hidden; position: relative;">
    <path fill="none" stroke="#000000" d="M161,97C177.5,97,194,154,194,211" marker-end="url(#raphael-marker-endopen55-obj18)" style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0);" />
    <path fill="none" stroke="#000000" d="M161,97C223,97,223,107,285,107" marker-end="url(#raphael-marker-endopen55-obj13)" style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0);" />
    <desc style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0);">Created with Raphaël 2.2.0</desc>
    <defs style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0);">
        <path stroke-linecap="round" d="M6,1 1,3.5 6,6" id="raphael-marker-open" style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0);" />
        <marker id="raphael-marker-endopen55-obj13" markerHeight="5" markerWidth="5" orient="auto" refX="4" refY="2.5" style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0);">
            <use xlink:href="#raphael-marker-open" transform="rotate(180 2.5 2.5) scale(0.7142857142857143,0.7142857142857143)" stroke-width="1.4000" fill="none" stroke="#000" style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0);" />
        </marker>
        <marker id="raphael-marker-endopen55-obj18" markerHeight="5" markerWidth="5" orient="auto" refX="4" refY="2.5" style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0);">
            <use xlink:href="#raphael-marker-open" transform="rotate(180 2.5 2.5) scale(0.7142857142857143,0.7142857142857143)" stroke-width="1.4000" fill="none" stroke="#000" style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0);" />
        </marker>
    </defs>
    <rect x="90" y="82" width="70" height="30" rx="5" ry="5" fill="#00b050" stroke="none" style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0); cursor: move;" />
    <text x="125" y="97" text-anchor="middle" font-family="&quot;Arial&quot;" font-size="12px" stroke="none" fill="#000000" style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0); text-anchor: middle; font-family: Arial; font-size: 12px;">
        <tspan dy="4" style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0);">Main</tspan>
    </text>
    <rect x="153" y="90" width="14" height="14" rx="3" ry="3" fill="#ffffff" stroke="#000000" style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0); cursor: pointer;" />
    <text x="160" y="97" text-anchor="middle" font-family="&quot;Arial&quot;" font-size="10px" stroke="none" fill="#000000" style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0); text-anchor: middle; font-family: Arial; font-size: 10px; cursor: pointer;">
        <tspan dy="3.5" style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0);">+</tspan>
    </text>
    <rect x="286" y="92" width="70" height="30" rx="5" ry="5" fill="#00b050" stroke="none" style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0); cursor: move;" />
    <text x="321" y="107" text-anchor="middle" font-family="&quot;Arial&quot;" font-size="12px" stroke="none" fill="#000000" style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0); text-anchor: middle; font-family: Arial; font-size: 12px;">
        <tspan dy="4" style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0);">Child</tspan>
    </text>
    <rect x="349" y="100" width="14" height="14" rx="3" ry="3" fill="#ffffff" stroke="#000000" style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0); cursor: pointer;" />
    <text x="356" y="107" text-anchor="middle" font-family="&quot;Arial&quot;" font-size="10px" stroke="none" fill="#000000" style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0); text-anchor: middle; font-family: Arial; font-size: 10px; cursor: pointer;">
        <tspan dy="3.5" style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0);">+</tspan>
    </text>
    <rect x="159" y="212" width="70" height="30" rx="5" ry="5" fill="#ff0000" stroke="none" style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0); cursor: move;" />
    <text x="194" y="227" text-anchor="middle" font-family="&quot;Arial&quot;" font-size="12px" stroke="none" fill="#000000" style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0); text-anchor: middle; font-family: Arial; font-size: 12px;">
        <tspan dy="4" style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0);">Child</tspan>
    </text>
    <rect x="222" y="220" width="14" height="14" rx="3" ry="3" fill="#ffffff" stroke="#000000" style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0); cursor: pointer;" />
    <text x="229" y="227" text-anchor="middle" font-family="&quot;Arial&quot;" font-size="10px" stroke="none" fill="#000000" style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0); text-anchor: middle; font-family: Arial; font-size: 10px; cursor: pointer;">
        <tspan dy="3.5" style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0);">+</tspan>
    </text>
</svg>

**Comment by mrbean-bremen** [comment]
Just re-tested with the test image: the white border seems to be gone, but the arrows are still wrong.

**Comment by mrbean-bremen** [comment]
Adapted title to refer to the last mentioned problem - the orioginal problem seems to be gone.
