### ISSUE TITLE
Adding transforms does not update Bounds property

### ISSUE THREAD

**Issue by jcvandan** [vvvv/SVG#216]
Maybe I am confused about how the library works, but I would assume that after a transform has been applied to an element, the `Bounds` property would be updated? In the following code the Bounds property does not get updated.

```
var circle = SvgDocument.FromSvg<SvgDocument>("<svg height=\"100\" width=\"100\">  <circle cx=\"50\" cy=\"50\" r=\"40\" stroke=\"black\" stroke-width=\"3\" fill=\"red\" /></svg>");
// Bounds: X=8.5 Y=8.5 Width=83 Height=83
circle.Transforms.Add(new SvgTranslate(50, 50));
// Bounds still: X=8.5 Y=8.5 Width=83 Height=83
```

Am I totally missing something here or is this intended functionality?

**Comment by tebjan** [comment]
i think you need to add the transform to the actual circle, not the whole svg document...

**Comment by mrbean-bremen** [comment]
@jcvandan - is this still an issue, or can this be closed?

**Comment by jcvandan** [comment]
> @jcvandan - is this still an issue, or can this be closed?

Could still be an issue, but I have no idea. T'was a long time ago I created this.

**Comment by mrbean-bremen** [comment]
Yeah, cleaning up old issues - thanks!
