### ISSUE TITLE
SvgPointCollect is a collection of SvgUnit

### ISSUE THREAD

**Issue by devinlyons** [vvvv/SVG#217]
SvgPointCollection.cs has the following class:

``` csharp
public class SvgPointCollection : List<SvgUnit>
{
```

I think it should be:

``` csharp
public class SvgPointCollection : List<SvgPoint>
{
```

Notice that I change the inheritance from `List<SvgUnit>` to `List<SvgPoint>`.

**Comment by mrbean-bremen** [comment]
This seems to have been a design decision, see also #335. I guess changing this would break compatibility.
