### ISSUE TITLE
Howto implement mouse event handling

### ISSUE THREAD

**Issue by osstekz** [vvvv/SVG#218]
Trying to find an example or at least code snippets illustrating mouse event handling. In my Winforms app, I can render nicely using Svg.ISvgRenderer, but how do you integrate mouse click & hover events. Looking into source for SvgElement I've seen all the OnMouseXXX events can be raised. It also supports Actions, however I can find no source implementations to learn from. Has anyone implemented mouse events that can share some code snippets?

**Comment by tebjan** [comment]
you can find an implementation of ISvgEventCaller in this project: https://github.com/vvvv/Posh/blob/master/Source/PoshServer.cs#L314

it uses sockets and RPC to transfer the browser events back to the C# code, but in your case it should be less complicated.

**Comment by tratak** [comment]
Yes, but is a very complicated for us. A little simple functional sample, not only code, in C# or VB.NET it will be very useful for many !

**Comment by akema-trebla** [comment]
> ou can find an implementation of ISvgEventCaller in this project: https://github.com/vvvv/Posh/blob/master/Source/PoshServer.cs#L314
> 
> it uses sockets and RPC to transfer the browser events back to the C# code, but in your case it should be less complicated. however, you have to generate the events yourself on Winforms level...

Is this still viable?

Trying to implement in Blazor.
