### ISSUE TITLE
SVG DLL for .Net 3.5

### ISSUE THREAD

**Issue by Baddy247** [vvvv/SVG#221]
Hi,

Is there a version of the dll compatible with .Net framework 3.5? I need to use this dll in one of projects built on v3.5.

**Comment by tebjan** [comment]
hi, you can always fork the code and compile it on your own... maybe you have to fix a few details before.
but as far as i remember there is an older version on the nuget server that is compatible with .NET 3.5.

**Comment by Baddy247** [comment]
Ok. I will check nuget.

**Comment by tebjan** [comment]
actually, the dll should be .net 3.5 compatible. just checked the solution... if you have a problem referencing, it might be related to something else.

**Comment by Baddy247** [comment]
I got the below error. Do I have to install this dll in the gac as well?

Could not load file or assembly 'Svg, Version=2.1.0.36771, Culture=neutral, PublicKeyToken=af2bbbd0525b67ac' or one of its dependencies. This assembly is built by a runtime newer than the currently loaded runtime and cannot be loaded.

**Comment by tebjan** [comment]
are you sure that you are on .NET 3.5?

**Comment by tebjan** [comment]
does the problem still exist? you can try the nuget, it should be .NET 3.5

**Comment by tebjan** [comment]
closing this because of no answer.
