### ISSUE TITLE
Image tag fails to be recognized if data URI is too large. 

### ISSUE THREAD

**Issue by AnkHansen** [vvvv/SVG#225]
Hi 

I have encountered a problem with rendering the attached SVG Image, speedometer.svg.

It fails to render the background image. 

I've debugged and found that the reason is that SvgImage uses c# Uri class to hold the data in href attribute. 

But it seems the c# Uri has a size limitiation, which causes the PropertyDescriptor converter to fail with an exception. 

I have tried changing the Href attribute on SvgImage to a String object instead. This causes the parsing to go well, and in the SvgImage.GetImage(string uriString) method I have changed it to create a Uri object of smaller size (my example is 200 - should be Uri maxsize I suppose). 

The Uri object can be used to test against to keep rest of the code intact, but the UriString on object can be used to parse image data.

This fix seems to do the trick, and my Image is now rendered correctly.

I am new to GitHub, so not really sure how (or if ) I can make a pull request with the code, so I have just supplied it in the issue here. 

I you want me to do it in another way - please let me know.

Best regards
/Anders

[Speedometer.zip](https://github.com/vvvv/SVG/files/208081/Speedometer.zip)
[SvgImage.zip](https://github.com/vvvv/SVG/files/208086/SvgImage.zip)

**Comment by AnkHansen** [comment]
Hi again

Attempted to make my first ever pull request on GitHub with the proposed changes. 

https://github.com/vvvv/SVG/pull/226

Let me know if I've done something wrong - or the change can be accepted. 

Within the next four weeks I need the fix in production, so hoping that the change can be merge before that, so I can include an official release in our product.

**Comment by tebjan** [comment]
fixed by https://github.com/vvvv/SVG/pull/226
