### ISSUE TITLE
Retrieve image svg from url and convert it into iTextSharp.text image

### ISSUE THREAD

**Issue by cristo1985** [vvvv/SVG#231]
Hi,
if i have a link as: 

https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/gaussian1.svg

And i wanna convert it to object as iTextSharp.text image with this 

 iTextSharp.text.Image jpg = iTextSharp.text.Image...(continue function... but how?).

If i wanna use this svg library how can i do it?

Thank, please
Cris

**Comment by HeinrichAD** [comment]
Hi Cris,

I am not quite familiar to iTextSharp but does the following not work for you?

```csharp
var imgSvg = svgDoc.Draw();
var imgTextSharp = iTextSharp.text.Image.GetInstance(imgSvg, null);
```
The null here is for the color base. Null should be possible here.


There are also other overloads. Just try them and choose the best one for you.


Regards
HeinrichAD

**Comment by mrbean-bremen** [comment]
Closing as answered - please reopen if you still have issues.
