### ISSUE TITLE
Simple SVG that is not rendered properly

### ISSUE THREAD

**Issue by haykpetros** [vvvv/SVG#239]
Attached is a simple SVG that is not rendered properly. Based on research problem is caused by elements with IDs "rect4" and "rect6". This is a very simple document that contains no grouping (G) or complex transforms so not clear what happens. Removing these two elements will render properly.

Here is the SVG that can be used for testing:
[Simple SVG that is not rendered properly.svg](https://gist.github.com/haykpetros/bb0fd291fe73077f8c3813b05c9d58bb#file-simple-svg-that-is-not-rendered-properly-svg)

And this is the PNG that is produced:
![test - wrong png](https://cloud.githubusercontent.com/assets/10164386/16223842/37dcf348-3754-11e6-84ed-d80d990df908.png)

**Comment by mrbean-bremen** [comment]
Looks good with the current version. Closing as fixed.
