### ISSUE TITLE
Part of the SVG is not on the produced image

### ISSUE THREAD

**Issue by haykpetros** [vvvv/SVG#242]
When rendering image from attached SVG at least one element (first "rect") is not rendered:

https://gist.github.com/haykpetros/f795d80eca04a92595b0c4629a20d165

![part of the stage is missing](https://cloud.githubusercontent.com/assets/10164386/16464167/c763e586-3ded-11e6-8edd-b1e21c26aee8.png)

``

**Comment by mrbean-bremen** [comment]
Looks good with the current version - must have been fixed meanwhile. Closing.
