### ISSUE TITLE
Crash with svg file

### ISSUE THREAD

**Issue by d2phap** [vvvv/SVG#245]
It seems related to a specific svg file. Strange that this file is not very heavy and is loading well in web browsers.

[shanghai.zip](https://github.com/vvvv/SVG/files/355626/shanghai.zip)

**Comment by mrbean-bremen** [comment]
@d2phap - I see other problems with this file (text rendering), but don't see any crash.
Is this still an issue for you?

**Comment by d2phap** [comment]
Hi @mrbean-bremen 
Sorry, after long time, I decided not using this lib anymore.

**Comment by mrbean-bremen** [comment]
Ok, closing this in this case.
