### ISSUE TITLE
Support for .NET Core?

### ISSUE THREAD

**Issue by UweKeim** [vvvv/SVG#248]
Do you any plans to support your library running on [.NET Core](https://www.microsoft.com/net/core) in the near future?

**Comment by mmosca** [comment]
I just submited a pull request to add support for .Netstandard 2.0 ( #326 )

This should allow you to use it with .Net Core once .Net core 2.0 is released in a few months.

**Comment by ljcorreia** [comment]
Thanks @mmosca,

I've tested your pull request and it worked mostly well, however, I'm having issues with one project that I tested exactly the same code used to change the fill colour and it does not seem to be doing the same if comparing the net45 vs netcore. I still haven't found the issue, but if you don't mind clarifying to me, please, where does that pull request #326 stands in regards to the use of ZKWeb.System.Drawing as opposed .Net Compatibility Pack?

Thanks
Leo

**Comment by mrbean-bremen** [comment]
@UweKeim - can you please if current master works for you?

**Comment by mrbean-bremen** [comment]
Closing this one too in favor of the [duplicate with the nicer number](https://github.com/vvvv/SVG/issues/400) - please add comments regarding .NET Core support on that issue.
