### ISSUE TITLE
why all background is black ??

### ISSUE THREAD

**Issue by yaronmil** [vvvv/SVG#249]
<?xml version='1.0' ?><svg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' version='1.1'><defs><radialGradient id='kdef2'  cx='237.5'  cy='230'  r='177'  gradientUnits='userSpaceOnUse' ><stop  offset='0.33'   style='stop-color:#fff;stop-opacity:0.06;'  /><stop  offset='0.83'   style='stop-color:#fff;stop-opacity:0.2;'  /><stop  offset='0.95'   style='stop-color:#fff;stop-opacity:0;'  /></radialGradient></defs><g transform='matrix(1,0,0,1,30.746257,0)' ><g><g><path    d='M0 0 L 475 0 475 412 0 412Z'   stroke='none'   fill='#fff'   ></path><path    d='M5 53 L 470 53 470 407 5 407Z'   stroke='none'   fill='#fff'  fill-opacity='0'   ></path><g><g></g></g><g><g><text  style='font:20px Arial;'   x='128.5' y='33'  stroke='none'     fill='#8e8e8e'  fill-opacity='1' >test</text></g></g><g><g><path    d='M316.033 66.925 L 328.999 40 343.877 40'   stroke='#939393'  stroke-width='1'   fill='none'   ></path><path    d='M379.011 342.852 L 400.728 363 404.728 363'   stroke='#939393'  stroke-width='1'   fill='none'   ></path><path    d='M61.038 189.724 L 36.754 184 32.754 184'   stroke='#939393'  stroke-width='1'   fill='none'   ></path><g transform='matrix(1,0,0,1,0,0)' ><path    d='M237.5 53 C 263.979 53 290.441 59.04 314.297 70.529 338.154 82.017 359.375 98.94 375.884 119.642 L 237.5 230Z'   stroke='none'   fill='#ff6800'   ></path><path    d='M237.5 53 C 263.979 53 290.441 59.04 314.297 70.529 338.154 82.017 359.375 98.94 375.884 119.642 L 237.5 230Z'   stroke='none'    fill='url(http://localhost:49268/%D7%A0%D7%99%D7%94%D7%95%D7%9C-%D7%AA%D7%A7%D7%9C%D7%95%D7%AA#kdef2)'  ></path></g><g transform='matrix(1,0,0,1,0,0)' ><path    d='M375.884 119.642 C 400.648 150.696 414.5 190.281 414.5 230 414.5 269.719 400.648 309.304 375.884 340.358 351.12 371.411 315.609 393.724 276.886 402.562 238.163 411.4 196.488 406.705 160.703 389.471 L 237.5 230Z'   stroke='none'   fill='#a0a700'   ></path><path    d='M375.884 119.642 C 400.648 150.696 414.5 190.281 414.5 230 414.5 269.719 400.648 309.304 375.884 340.358 351.12 371.411 315.609 393.724 276.886 402.562 238.163 411.4 196.488 406.705 160.703 389.471 L 237.5 230Z'   stroke='none'    fill='url(http://localhost:49268/%D7%A0%D7%99%D7%94%D7%95%D7%9C-%D7%AA%D7%A7%D7%9C%D7%95%D7%AA#kdef2)'  ></path></g><g transform='matrix(1,0,0,1,0,0)' ><path    d='M160.703 389.471 C 124.917 372.238 95.262 342.583 78.029 306.797 60.795 271.012 56.1 229.337 64.938 190.614 73.776 151.891 96.089 116.38 127.142 91.616 158.196 66.852 197.781 53 237.5 53 L 237.5 230Z'   stroke='none'   fill='#ff8d00'   ></path><path    d='M160.703 389.471 C 124.917 372.238 95.262 342.583 78.029 306.797 60.795 271.012 56.1 229.337 64.938 190.614 73.776 151.891 96.089 116.38 127.142 91.616 158.196 66.852 197.781 53 237.5 53 L 237.5 230Z'   stroke='none'    fill='url(http://localhost:49268/%D7%A0%D7%99%D7%94%D7%95%D7%9C-%D7%AA%D7%A7%D7%9C%D7%95%D7%AA#kdef2)'  ></path></g></g></g><g opacity='1' ><path    d='M348.377 32 L 415.377 32 415.377 48 348.377 48Z'   stroke='#000'  stroke-width='0'  stroke-opacity='0.5'   fill='#fff'  fill-opacity='0.5'   ></path><text  style='font:11pt Arial;'   x='348.37662796081423' y='45'  stroke='none'     fill='#000'  fill-opacity='1' >(3) מאסטרו</text></g><g opacity='1' ><path    d='M409.228 355 L 501.228 355 501.228 371 409.228 371Z'   stroke='#000'  stroke-width='0'  stroke-opacity='0.5'   fill='#fff'  fill-opacity='0.5'   ></path><text  style='font:11pt Arial;'   x='409.22791828437323' y='368'  stroke='none'     fill='#000'  fill-opacity='1' >(9) aabb</text></g><g opacity='1' ><path    d='M-30.746 176 L 28.254 176 28.254 192 -30.746 192Z'   stroke='#000'  stroke-width='0'  stroke-opacity='0.5'   fill='#fff'  fill-opacity='0.5'   ></path><text  style='font:11pt Arial;'   x='-30.74625745148103' y='189'  stroke='none'     fill='#000'  fill-opacity='1' >(9) pak</text></g></g></g></g></svg>

**Comment by southernangel** [comment]
I had an issue like this where a shape was filling for some reason, I had to add a fill of None and that cleared it up
