### ISSUE TITLE
Edit and update text 

### ISSUE THREAD

**Issue by bobbymale** [vvvv/SVG#254]
Hello,

I've search but could not find any answer. Also checked the sample code but found nothing. How can I edit and update the text in the svg file? This is the svg file and I wanted to update from 10 to 20.

<svg xmlns="http://www.w3.org/2000/svg">
<g>
  <path fill="red" stroke="white" stroke-width="0.5" d="M1.8 1.8h15v15h-15z" ></path>
  <text id="text1" x="3" y="14" font-size="12" fill="white" >10</text>
</g>
</svg>

**Comment by pushasha** [comment]
@bobbymale: There's [an open issue related to this](https://github.com/vvvv/SVG/issues/151). If it were working properly, you would do it like this (as far as I know):
```csharp
// read in the SVG
SvgDocument doc = SvgDocument.Open(_filePath);

// Get text element
SvgText myText = doc.GetElementById<SvgText>("text1");

// Set text
myText.Text = "20";

// write updated contents back out to SVG
doc.Write(_filePath);
```
