### ISSUE TITLE
Font is bolder than intended?

### ISSUE THREAD

**Issue by leviathan25** [vvvv/SVG#257]
I recently upgraded from 2.0 to 2.2.1. I have a few elements that look like this:

`<rect scale="6" x="238.16px" y="264px" width="63.68px" height="12px" fill="White" fill-opacity="1" stroke="White" stroke-width="0" />`

`<text class=" FL Dimensions" x="270px" y="276px" fill="Green" stroke-width="0.1" lengthAdjust="spacingAndGlyphs" textLength="63.68" text-anchor="middle" font-family="Arial" font-size="12px">60.00 (FL)</text>`

When I "Draw()" the image, the font is displaying very thick (bold) compared to previously.

Before:
![image](https://cloud.githubusercontent.com/assets/23318875/20068482/8d84195a-a4de-11e6-8dc4-6f13bcfbcf2d.png)

After:
![image](https://cloud.githubusercontent.com/assets/23318875/20068571/d6a53a2e-a4de-11e6-9f5f-1fa5f5976d67.png)

I'm also getting some other weird issues. The rectangles that I drew to go behind the text to prevent bleed through from the line had a stroke-width of 0, and the rectangle did not draw at all. (Removing the stroke-width solved the issue, but I still think this might be a bug.)

The other issue is that the green lines in my drawings are occasionally lighter than previously. You can see this in the pictures as well.

I'm not sure what is going on, but I had to drop back to 2.0 in order to see the image as it's shown in my browser.

**Comment by tebjan** [comment]
please try with latest nuget 2.3.0, there was a problem with text rendering that might now be fixed.

**Comment by tebjan** [comment]
closing this since there is no response.
