### ISSUE TITLE
Objects sometimes misaligned in rendered SVG.

### ISSUE THREAD

**Issue by DustinEwan** [vvvv/SVG#26]
Sometimes when rendering charts from highcharts, elements from highcharts' SVG  are rendered in the wrong position.

When the SVG is rendered in browser, everything appears to be in the correct position, but once rendered with SVG.NET, items will sometimes be misaligned as per the following image:

![chart label off](https://f.cloud.github.com/assets/1225064/1382371/bd93c690-3b2d-11e3-8eee-029ebf14c0c7.PNG)

**Comment by mrbean-bremen** [comment]
Cleaning up old issues:
Closing as outdated and missing example data.
Please reopen if this is still an issue and you can provide a failing svg.
