### ISSUE TITLE
Problem to convert SVG from Visio to any other format

### ISSUE THREAD

**Issue by rabbiwan** [vvvv/SVG#264]
Hello,
I have created SVG images from Visio and there images can't be convert with the tool.
I have a problem outofmemory at the draw.
The problem occurs when the points in the calculation are close to zero (midpoint, dy and dx).
The calcul create a float with an exhibitor very high and I think the method LinearGradientBrush can't run correctly.
Maybe I'm wrong...

This is the stack : 
`   à System.Drawing.Drawing2D.LinearGradientBrush..ctor(PointF point1, PointF point2, Color color1, Color color2) à Svg.SvgLinearGradientServer.GetBrush(SvgVisualElement renderingElement, ISvgRenderer renderer, Single opacity, Boolean forStroke) dans C:\Dev\vvvv\SVG\Source\Painting\SvgLinearGradientServer.cs:ligne 164
   à Svg.SvgVisualElement.RenderFill(ISvgRenderer renderer) dans C:\Dev\vvvv\SVG\Source\Basic Shapes\SvgVisualElement.cs:ligne 201
   à Svg.SvgVisualElement.Render(ISvgRenderer renderer, Boolean renderFilter) dans C:\Dev\vvvv\SVG\Source\Basic Shapes\SvgVisualElement.cs:ligne 172
   à Svg.SvgVisualElement.Render(ISvgRenderer renderer) dans C:\Dev\vvvv\SVG\Source\Basic Shapes\SvgVisualElement.cs:ligne 129
   à Svg.SvgElement.RenderChildren(ISvgRenderer renderer) dans C:\Dev\vvvv\SVG\Source\SvgElement.cs:ligne 726
   à Svg.SvgVisualElement.Render(ISvgRenderer renderer, Boolean renderFilter) dans C:\Dev\vvvv\SVG\Source\Basic Shapes\SvgVisualElement.cs:ligne 183
   à Svg.SvgVisualElement.Render(ISvgRenderer renderer) dans C:\Dev\vvvv\SVG\Source\Basic Shapes\SvgVisualElement.cs:ligne 129
   à Svg.SvgElement.RenderChildren(ISvgRenderer renderer) dans C:\Dev\vvvv\SVG\Source\SvgElement.cs:ligne 726
   à Svg.SvgVisualElement.Render(ISvgRenderer renderer, Boolean renderFilter) dans C:\Dev\vvvv\SVG\Source\Basic Shapes\SvgVisualElement.cs:ligne 183
   à Svg.SvgVisualElement.Render(ISvgRenderer renderer) dans C:\Dev\vvvv\SVG\Source\Basic Shapes\SvgVisualElement.cs:ligne 129
   à Svg.SvgElement.RenderChildren(ISvgRenderer renderer) dans C:\Dev\vvvv\SVG\Source\SvgElement.cs:ligne 726
   à Svg.SvgVisualElement.Render(ISvgRenderer renderer, Boolean renderFilter) dans C:\Dev\vvvv\SVG\Source\Basic Shapes\SvgVisualElement.cs:ligne 183
   à Svg.SvgVisualElement.Render(ISvgRenderer renderer) dans C:\Dev\vvvv\SVG\Source\Basic Shapes\SvgVisualElement.cs:ligne 129
   à Svg.SvgElement.RenderChildren(ISvgRenderer renderer) dans C:\Dev\vvvv\SVG\Source\SvgElement.cs:ligne 726
   à Svg.SvgElement.Render(ISvgRenderer renderer) dans C:\Dev\vvvv\SVG\Source\SvgElement.cs:ligne 714
   à Svg.SvgFragment.Render(ISvgRenderer renderer) dans C:\Dev\vvvv\SVG\Source\Document Structure\SvgFragment.cs:ligne 169
   à Svg.SvgDocument.Draw(Bitmap bitmap) dans C:\Dev\vvvv\SVG\Source\SvgDocument.cs:ligne 501
   à Svg.SvgDocument.Draw() dans C:\Dev\vvvv\SVG\Source\SvgDocument.cs:ligne 466`

**Comment by mrbean-bremen** [comment]
This is the same problem as #278. Closing this one as duplicate, as the newer one has a bit more information.
