### ISSUE TITLE
emf ungroup in powerpoint is ugly

### ISSUE THREAD

**Issue by ph1lolog1st** [vvvv/SVG#265]
I convert svg to emf. It's very cool, scalar property not disappeared, transparency available, but
when I try ungroup emf in Power Point, transparent circle becomes square. Every letter in text become separate, so to edit one word i should edit every letter. Are there some ways to prevent it on ungroup.

**Comment by ph1lolog1st** [comment]
After some investigation, question is following: can I draw string direct into Drawing object, not in DrawingPath instance?

**Comment by mrbean-bremen** [comment]
I don't really understand the question (what is DrawingPath?). I'm closing this now as outdated and due to missing information - please reopen if this is still an issue and you have more information.
