### ISSUE TITLE
SVG with linked images?

### ISSUE THREAD

**Issue by pkmccaffrey** [vvvv/SVG#27]
I am trying to use this library to to take a SVG, and generate a rasterized image from it.  My SVG files have images (linked to using absolute URLs) and text.

When I use the library to try to create/save the rasterized image, none of the SVG's linked images are rendered.  On CodePlex, this issue is mentioned in the "Discussion" tab by some other users.

Are embedded images able to be rendered?

**Comment by mrbean-bremen** [comment]
Most of the problems in this issue should have been resolved meanwhile - closing this now.
Please write new issues for any remaining stuff.
