### ISSUE TITLE
Attribute shape-rendering not allowed on SVG element STYLE

### ISSUE THREAD

**Issue by nixprosoft** [vvvv/SVG#273]
Incorrect codestyle in resulting file:
```
<style shape-rendering="geometricPrecision" xml:space="preserve" type="text/css">
```
https://validator.nu/

**Comment by nixprosoft** [comment]
It's hard to remember. 2 years past sinse I'm asking. All I remember - file was creating via C# app, from two template SVG, merged together. It's all I know. Sorry

**Comment by mrbean-bremen** [comment]
Thank you, I understand that this was long ago - I'm cleaning up old issues, trying to check if they are still valid. I'm closing this now in this case - you can always reopen it if that comes up again.
