### ISSUE TITLE
SVG Master failing to convert arabic text present in the SVG?

### ISSUE THREAD

**Issue by SaddamBInSyed** [vvvv/SVG#274]
Hi there,

I have downloaded the library and its working perfectly for English font text. but when I load the S VG which contains arabic font text in it then the output image contains only the Symbols.

How do i resolve this issue ?  Highly appreciated your PROMPT help.

**Comment by mrbean-bremen** [comment]
Generally, arabic text can be displayed, as is shown in some of the test files (like `text-intro-07-t.svg`).
I'm closing this because of insufficient information, please reopen if you have an example for the problem.
