### ISSUE TITLE
help: rendering referenced image with relative path

### ISSUE THREAD

**Issue by zaus** [vvvv/SVG#276]
I have an SVG (created by FabricJS) that rather than embedding an image via dataurl it references a "local" (i.e. in same folder as the SVG) relative path.  When rendering it quietly fails with the following trace, and the image isn't part of the result:

> Error: 0 : Error loading image: 'F3CFD546-9A7A-11E6-B77D-3F565C1445DF.png', error: Invalid URI: The format of the URI could not be determined.

What's the best way to include the image?  Do I need to parse the XML first and "correct" the image path to a full filepath?

	<?xml version='1.0' encoding='utf-8' standalone='no'?>
	<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="3200" height="3200" viewBox="0 0 3200 3200" xml:space="preserve" preserveAspectRatio="xMidYMid meet" zoomAndPan="magnify" contentScriptType="application/ecmascript" contentStyleType="text/css">
	<desc>Created with Fabric.js 1.6.0</desc>
	<defs></defs>
	<g transform="translate(1424 1492) scale(8 8)">
		<image xlink:href="F3CFD546-9A7A-11E6-B77D-3F565C1445DF.png" x="-48.074921956295526" y="-47.72727272727273" style="stroke: none; stroke-width: 0; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(0,0,0); fill-rule: nonzero; opacity: 1;" width="96.14984391259105" height="95.45454545454545" preserveAspectRatio="none" xlink:type="simple" xlink:show="embed" xlink:actuate="onLoad"></image>
	</g>
	</svg>

**Comment by zaus** [comment]
It seems if you can alter the XML (i.e. after reading it from a file) to change the HREF to a full filepath (e.g. `Path.Combine(Path.GetDirectoryName(svgPath), theRegexMatch)`) it will render.  Any better ideas?

**Comment by mrbean-bremen** [comment]
Relative path shall work after  PR #287 is merged - only just noticed that there is an issue for this.
