### ISSUE TITLE
Some visio images open black

### ISSUE THREAD

**Issue by the8thavatar** [vvvv/SVG#280]
e.g. the desktop, screen and plotter from Visio 2016's network components - 3d
in comparison the mainframe symbol from the same category is ok

**Comment by the8thavatar** [comment]
I worked around the issue by also supporting the use of an alternative rendering library.
File attached. 
[files.zip](https://github.com/vvvv/SVG/files/2694675/files.zip)

**Comment by mrbean-bremen** [comment]
Thanks!

**Comment by mrbean-bremen** [comment]
I had another look at this one, and it seems to be the same problem as #391 (at least with the second image, the first one renders more or less correctly now) - the global class style is not taken into account. If adding `fill="none"` to the svg element (which is part of the referenced style class), it works.
