### ISSUE TITLE
how to set dominant-baseline to hanging?

### ISSUE THREAD

**Issue by amiralarab** [vvvv/SVG#284]
Hi
I use many fonts to write text element in svg.
when I change font-size, the baseline of text is incorrect for positioning!
cause I have 3 text element with different size dynamically
have you support dominant-baseline to hanging and convert this svg to png?
thanks advance

**Comment by amiralarab** [comment]
dominant-baseline not support with this library!

**Comment by cantax** [comment]
Same as #298

**Comment by mrbean-bremen** [comment]
Closing as duplicate of @298.
