### ISSUE TITLE
How do i get a click event 

### ISSUE THREAD

**Issue by handena** [vvvv/SVG#289]
Hi,
I'm using SVG 2.3.0 and I want to handle a click on a SVG element in my Winforms code.
I added a click event handler, but this handler is not called:
_element.Click += MySvgClickHandler;_

**Comment by tebjan** [comment]
please see this issue: https://github.com/vvvv/SVG/issues/218

**Comment by tratak** [comment]
Sorry, I saw the Posh project, downloaded it, but is not functional, and his code is not understandable for me ( or for many ?...). It would be useful a simple svg.dll only using sample...
