### ISSUE TITLE
Wpf/Xaml example

### ISSUE THREAD

**Issue by bbeardsley** [vvvv/SVG#299]
Trying to use this in a wpf app but not having success.  Is there any example anywhere?

I have  xmlns:s="clr-namespace:Svg;assembly=Svg" on my window and have referenced the assembly in my project.  Was trying to use <s:SvgViewBox> in my xaml but it says not found. Tried using SvgVisualElement but it said it couldn't add it to the UICollection.

Thanks for any help.

**Comment by mrbean-bremen** [comment]
@bbeardsley - did you have any success building that? Is this still an issue for you?

**Comment by bbeardsley** [comment]
I didn't have any success but ended up going in a different direction so not using this.

**Comment by mrbean-bremen** [comment]
Ok, thanks!
