### ISSUE TITLE
Setting Text cleans child nodes since 05b4d6e (released with 2.3.0)

### ISSUE THREAD

**Issue by dittodhole** [vvvv/SVG#301]
Please see my comment on the commit for more information (https://github.com/vvvv/SVG/commit/05b4d6ed353132aaeae9775d75f3bd1b0c0a6ba9):

```csharp
var textInfoLine = svgDocument.GetElementById<SvgTextBase>("textInfoLine");
textInfoLine.Text = null;

var infoLine = svgDocument.GetElementById<SvgTextBase>("InfoLine");
// infoLine is now null ...
```

**Comment by tebjan** [comment]
hell, can you make a pull request with this? thanks!

**Comment by mrbean-bremen** [comment]
On second glance, I do not consider this a bug. As far as I understand, this has already been fixed in the using code - closing.

**Comment by dittodhole** [comment]
reconsider: in every using code?

**Comment by mrbean-bremen** [comment]
I just saw the fix you made in your using code - do you have more problems with that? If yes, do you have a suggestion how to change the behavior without reintroducing the fixed problem?

And feel free to reopen the issue of course if this is still an issue for you.
