### ISSUE TITLE
Default parameter specifiers

### ISSUE THREAD

**Issue by Fr33dan** [vvvv/SVG#303]
Perhaps this is my own confusion but I downloaded the project and attempted to compile it only to be confronted with slew of "Default Parameter Specifiers are not permitted" errors. According to the Svg.csproj file the project is created in the almost same version of Visual Studio as I am using and is a .NET 3.5 project:

```
    <ProductVersion>9.0.30729</ProductVersion>
    ...
    <TargetFrameworkVersion>v3.5</TargetFrameworkVersion>
```
![vs version](https://cloud.githubusercontent.com/assets/4670572/24250724/3be6e9ac-0fae-11e7-94e7-1ce6f97f691c.png)

But according to a quick google search [optional/default parameters](http://stackoverflow.com/a/6398438/1111886) weren't added until .NET 4.0.  Am I doing something wrong or missing something?

**Comment by Fr33dan** [comment]
I created #309 which solves this issue

**Comment by mrbean-bremen** [comment]
@tebjan - do you want to support Visual Studio 2008?
@Fr33dan - is this still an issue for you?

**Comment by mrbean-bremen** [comment]
@Fr33dan - given that you newest PR now uses default parameters, I guess that this is not an issue anymore. I think that we can skip support for VS 2008 - closing.
