### ISSUE TITLE
Text does not render,svg to png

### ISSUE THREAD

**Issue by smallBlacks** [vvvv/SVG#321]

**Comment by smallBlacks** [comment]
Please provide the latest DLL,thank u

**Comment by smallBlacks** [comment]
<svg xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" class="highcharts-root" style="font-family:&quot;lucida grande&quot;, &quot;lucida sans unicode&quot;, arial, helvetica, sans-serif;font-size:12px;" xmlns="http://www.w3.org/2000/svg" width="1294" height="400">
<desc>Created with Highcharts 5.0.7
</desc>
<defs>
<clipPath id="highcharts-km8n5on-16">
<rect x="1" y="0" width="1038" height="269" fill="none">
</rect>
</clipPath>
</defs>
<rect fill="#ffffff" class="highcharts-background" x="0" y="0" width="1294" height="400" rx="0" ry="0">
</rect>
<rect fill="none" class="highcharts-plot-background" x="105" y="53" width="1039" height="269">
</rect>
<g class="highcharts-grid highcharts-xaxis-grid ">
<path fill="none" class="highcharts-grid-line" d="M 114.5 53 L 114.5 322" opacity="1">
</path>
<path fill="none" class="highcharts-grid-line" d="M 1133.5 53 L 1133.5 322" opacity="1">
</path>
</g>
<g class="highcharts-grid highcharts-yaxis-grid ">
<path fill="none" stroke="#e6e6e6" stroke-width="1" class="highcharts-grid-line" d="M 105 322.5 L 1144 322.5" opacity="1">
</path>
<path fill="none" stroke="#e6e6e6" stroke-width="1" class="highcharts-grid-line" d="M 105 298.5 L 1144 298.5" opacity="1">
</path>
<path fill="none" stroke="#e6e6e6" stroke-width="1" class="highcharts-grid-line" d="M 105 273.5 L 1144 273.5" opacity="1">
</path>
<path fill="none" stroke="#e6e6e6" stroke-width="1" class="highcharts-grid-line" d="M 105 249.5 L 1144 249.5" opacity="1">
</path>
<path fill="none" stroke="#e6e6e6" stroke-width="1" class="highcharts-grid-line" d="M 105 224.5 L 1144 224.5" opacity="1">
</path>
<path fill="none" stroke="#e6e6e6" stroke-width="1" class="highcharts-grid-line" d="M 105 200.5 L 1144 200.5" opacity="1">
</path>
<path fill="none" stroke="#e6e6e6" stroke-width="1" class="highcharts-grid-line" d="M 105 175.5 L 1144 175.5" opacity="1">
</path>
<path fill="none" stroke="#e6e6e6" stroke-width="1" class="highcharts-grid-line" d="M 105 151.5 L 1144 151.5" opacity="1">
</path>
<path fill="none" stroke="#e6e6e6" stroke-width="1" class="highcharts-grid-line" d="M 105 126.5 L 1144 126.5" opacity="1">
</path>
<path fill="none" stroke="#e6e6e6" stroke-width="1" class="highcharts-grid-line" d="M 105 102.5 L 1144 102.5" opacity="1">
</path>
<path fill="none" stroke="#e6e6e6" stroke-width="1" class="highcharts-grid-line" d="M 105 77.5 L 1144 77.5" opacity="1">
</path>
<path fill="none" stroke="#e6e6e6" stroke-width="1" class="highcharts-grid-line" d="M 105 52.5 L 1144 52.5" opacity="1">
</path>
</g>
<g class="highcharts-grid highcharts-yaxis-grid ">
<path fill="none" stroke="#e6e6e6" stroke-width="1" class="highcharts-grid-line" d="M 105 322.5 L 1144 322.5" opacity="1">
</path>
<path fill="none" stroke="#e6e6e6" stroke-width="1" class="highcharts-grid-line" d="M 105 298.5 L 1144 298.5" opacity="1">
</path>
<path fill="none" stroke="#e6e6e6" stroke-width="1" class="highcharts-grid-line" d="M 105 273.5 L 1144 273.5" opacity="1">
</path>
<path fill="none" stroke="#e6e6e6" stroke-width="1" class="highcharts-grid-line" d="M 105 249.5 L 1144 249.5" opacity="1">
</path>
<path fill="none" stroke="#e6e6e6" stroke-width="1" class="highcharts-grid-line" d="M 105 224.5 L 1144 224.5" opacity="1">
</path>
<path fill="none" stroke="#e6e6e6" stroke-width="1" class="highcharts-grid-line" d="M 105 200.5 L 1144 200.5" opacity="1">
</path>
<path fill="none" stroke="#e6e6e6" stroke-width="1" class="highcharts-grid-line" d="M 105 175.5 L 1144 175.5" opacity="1">
</path>
<path fill="none" stroke="#e6e6e6" stroke-width="1" class="highcharts-grid-line" d="M 105 151.5 L 1144 151.5" opacity="1">
</path>
<path fill="none" stroke="#e6e6e6" stroke-width="1" class="highcharts-grid-line" d="M 105 126.5 L 1144 126.5" opacity="1">
</path>
<path fill="none" stroke="#e6e6e6" stroke-width="1" class="highcharts-grid-line" d="M 105 102.5 L 1144 102.5" opacity="1">
</path>
<path fill="none" stroke="#e6e6e6" stroke-width="1" class="highcharts-grid-line" d="M 105 77.5 L 1144 77.5" opacity="1">
</path>
<path fill="none" stroke="#e6e6e6" stroke-width="1" class="highcharts-grid-line" d="M 105 52.5 L 1144 52.5" opacity="1">
</path>
</g>
<rect fill="none" class="highcharts-plot-border" x="105" y="53" width="1039" height="269">
</rect>
<g class="highcharts-axis highcharts-xaxis ">
<path fill="none" class="highcharts-tick" stroke="#ccd6eb" stroke-width="1" d="M 114.5 322 L 114.5 332" opacity="1">
</path>
<path fill="none" class="highcharts-tick" stroke="#ccd6eb" stroke-width="1" d="M 1133.5 322 L 1133.5 332" opacity="1">
</path>
<path fill="none" class="highcharts-axis-line" stroke="#ccd6eb" stroke-width="1" d="M 105 322.5 L 1144 322.5">
</path>
</g>
<g class="highcharts-axis highcharts-yaxis ">
<text x="27.84375" text-anchor="middle" transform="translate(0,0) rotate(270 27.84375 187.5)" class="highcharts-axis-title" style="color:#666666;font-weight:bold;fill:#666666;" y="187.5">累计净值
</text>
<path fill="none" class="highcharts-axis-line" stroke="#ccd6eb" stroke-width="2" d="M 105 53 L 105 322">
</path>
</g>
<g class="highcharts-axis highcharts-yaxis ">
<text x="1255.984375" text-anchor="middle" transform="translate(0,0) rotate(90 1255.984375 187.5)" class="highcharts-axis-title" style="color:red;font-weight:bold;fill:red;" y="187.5">份额
</text>
<path fill="none" class="highcharts-axis-line" stroke="red" stroke-width="1" d="M 1144.5 53 L 1144.5 322">
</path>
</g>
<g class="highcharts-series-group">
<g class="highcharts-series highcharts-series-0 highcharts-line-series highcharts-color-0 " transform="translate(105,53) scale(1 1)" clip-path="url(#highcharts-km8n5on-16)">
<path fill="none" d="M 10.186274509804 244.5454545455138 L 1028.8137254902 48.909090908972445" class="highcharts-graph" stroke="#7cb5ec" stroke-width="2" stroke-linejoin="round" stroke-linecap="round">
</path>
</g>
<g class="highcharts-markers highcharts-series-0 highcharts-line-series highcharts-color-0 " transform="translate(105,53) scale(1 1)" clip-path="none">
<path fill="#7cb5ec" d="M 12 245 A 2 2 0 1 1 11.999999000000084 244.99800000033332 Z" class="highcharts-point highcharts-color-0">
</path>
<path fill="#7cb5ec" d="M 1030 49 A 2 2 0 1 1 1029.9999990000001 48.998000000333334 Z" class="highcharts-point highcharts-color-0">
</path>
</g>
<g class="highcharts-series highcharts-series-1 highcharts-line-series highcharts-color-1 " transform="translate(105,53) scale(1 1)" clip-path="url(#highcharts-km8n5on-16)">
<path fill="none" d="M 10.186274509804 269 L 1028.8137254902 269" class="highcharts-graph" stroke="#434348" stroke-width="2" stroke-linejoin="round" stroke-linecap="round">
</path>
</g>
<g class="highcharts-markers highcharts-series-1 highcharts-line-series highcharts-color-1 " transform="translate(105,53) scale(1 1)" clip-path="none">
<path fill="#434348" d="M 10 267 L 12 269 10 271 8 269 Z" class="highcharts-point highcharts-color-1">
</path>
<path fill="#434348" d="M 1028 267 L 1030 269 1028 271 1026 269 Z" class="highcharts-point highcharts-color-1">
</path>
</g>
</g>
<text x="647" text-anchor="middle" class="highcharts-title" style="color:blue;font-size:18px;font-weight:bold;fill:blue;" y="24">
<tspan>累计净值与份额图表
</tspan>
</text>
<g class="highcharts-legend" transform="translate(494,356)">
<rect fill="none" class="highcharts-legend-box" rx="0" ry="0" x="0" y="0" width="305" height="29" visibility="visible">
</rect>
<g>
<g>
<g class="highcharts-legend-item highcharts-line-series highcharts-color-0 highcharts-series-0" transform="translate(8,3)">
<path fill="none" d="M 0 11 L 16 11" class="highcharts-graph" stroke="#7cb5ec" stroke-width="2">
</path>
<path fill="#7cb5ec" d="M 10 11 A 2 2 0 1 1 9.999999000000084 10.998000000333333 Z" class="highcharts-point">
</path>
<text x="21" style="color:#333333;font-size:12px;font-weight:bold;cursor:pointer;fill:#333333;" text-anchor="start" y="15">盛世鸿瑞1号(累计净值)
</text>
</g>
<g class="highcharts-legend-item highcharts-line-series highcharts-color-1 highcharts-series-1" transform="translate(174.96875,3)">
<path fill="none" d="M 0 11 L 16 11" class="highcharts-graph" stroke="#434348" stroke-width="2">
</path>
<path fill="#434348" d="M 8 9 L 10 11 8 13 6 11 Z" class="highcharts-point">
</path>
<text x="21" y="15" style="color:#333333;font-size:12px;font-weight:bold;cursor:pointer;fill:#333333;" text-anchor="start">盛世鸿瑞1号(份额)
</text>
</g>
</g>
</g>
</g>
<g class="highcharts-axis-labels highcharts-xaxis-labels ">
<text x="115.18627450980392" style="color:#666666;cursor:default;font-size:11px;fill:#666666;" text-anchor="middle" transform="translate(0,0)" y="341" opacity="1">2016/11/23
</text>
<text x="0" style="color:#666666;cursor:default;font-size:11px;fill:#666666;" text-anchor="middle" transform="translate(0,0)" y="-9999">2016/11/24
</text>
</g>
<g class="highcharts-axis-labels highcharts-yaxis-labels ">
<text x="90" style="color:#666666;cursor:default;font-size:11px;fill:#666666;" text-anchor="end" transform="translate(0,0)" y="326" opacity="1">
<tspan>1.137975
</tspan>
</text>
<text x="90" style="color:#666666;cursor:default;font-size:11px;fill:#666666;" text-anchor="end" transform="translate(0,0)" y="302" opacity="1">
<tspan>1.138
</tspan>
</text>
<text x="90" style="color:#666666;cursor:default;font-size:11px;fill:#666666;" text-anchor="end" transform="translate(0,0)" y="277" opacity="1">
<tspan>1.138025
</tspan>
</text>
<text x="90" style="color:#666666;cursor:default;font-size:11px;fill:#666666;" text-anchor="end" transform="translate(0,0)" y="253" opacity="1">
<tspan>1.13805
</tspan>
</text>
<text x="90" style="color:#666666;cursor:default;font-size:11px;fill:#666666;" text-anchor="end" transform="translate(0,0)" y="228" opacity="1">
<tspan>1.138075
</tspan>
</text>
<text x="90" style="color:#666666;cursor:default;font-size:11px;fill:#666666;" text-anchor="end" transform="translate(0,0)" y="204" opacity="1">
<tspan>1.1381
</tspan>
</text>
<text x="90" style="color:#666666;cursor:default;font-size:11px;fill:#666666;" text-anchor="end" transform="translate(0,0)" y="179" opacity="1">
<tspan>1.138125
</tspan>
</text>
<text x="90" style="color:#666666;cursor:default;font-size:11px;fill:#666666;" text-anchor="end" transform="translate(0,0)" y="155" opacity="1">
<tspan>1.13815
</tspan>
</text>
<text x="90" style="color:#666666;cursor:default;font-size:11px;fill:#666666;" text-anchor="end" transform="translate(0,0)" y="130" opacity="1">
<tspan>1.138175
</tspan>
</text>
<text x="90" style="color:#666666;cursor:default;font-size:11px;fill:#666666;" text-anchor="end" transform="translate(0,0)" y="106" opacity="1">
<tspan>1.1382
</tspan>
</text>
<text x="90" style="color:#666666;cursor:default;font-size:11px;fill:#666666;" text-anchor="end" transform="translate(0,0)" y="81" opacity="1">
<tspan>1.138225
</tspan>
</text>
<text x="90" style="color:#666666;cursor:default;font-size:11px;fill:#666666;" text-anchor="end" transform="translate(0,0)" y="57" opacity="1">
<tspan>1.13825
</tspan>
</text>
</g>
<g class="highcharts-axis-labels highcharts-yaxis-labels ">
<text x="1159" style="color:red;cursor:default;font-size:11px;fill:red;" text-anchor="start" transform="translate(0,0)" y="326" opacity="1">
<tspan>803,229,414.60
</tspan>
</text>
<text x="1159" style="color:red;cursor:default;font-size:11px;fill:red;" text-anchor="start" transform="translate(0,0)" y="302" opacity="1">
<tspan>803,229,415.60
</tspan>
</text>
<text x="1159" style="color:red;cursor:default;font-size:11px;fill:red;" text-anchor="start" transform="translate(0,0)" y="277" opacity="1">
<tspan>803,229,416.60
</tspan>
</text>
<text x="1159" style="color:red;cursor:default;font-size:11px;fill:red;" text-anchor="start" transform="translate(0,0)" y="253" opacity="1">
<tspan>803,229,417.60
</tspan>
</text>
<text x="1159" style="color:red;cursor:default;font-size:11px;fill:red;" text-anchor="start" transform="translate(0,0)" y="228" opacity="1">
<tspan>803,229,418.60
</tspan>
</text>
<text x="1159" style="color:red;cursor:default;font-size:11px;fill:red;" text-anchor="start" transform="translate(0,0)" y="204" opacity="1">
<tspan>803,229,419.60
</tspan>
</text>
<text x="1159" style="color:red;cursor:default;font-size:11px;fill:red;" text-anchor="start" transform="translate(0,0)" y="179" opacity="1">
<tspan>803,229,420.60
</tspan>
</text>
<text x="1159" style="color:red;cursor:default;font-size:11px;fill:red;" text-anchor="start" transform="translate(0,0)" y="155" opacity="1">
<tspan>803,229,421.60
</tspan>
</text>
<text x="1159" style="color:red;cursor:default;font-size:11px;fill:red;" text-anchor="start" transform="translate(0,0)" y="130" opacity="1">
<tspan>803,229,422.60
</tspan>
</text>
<text x="1159" style="color:red;cursor:default;font-size:11px;fill:red;" text-anchor="start" transform="translate(0,0)" y="106" opacity="1">
<tspan>803,229,423.60
</tspan>
</text>
<text x="1159" style="color:red;cursor:default;font-size:11px;fill:red;" text-anchor="start" transform="translate(0,0)" y="81" opacity="1">
<tspan>803,229,424.60
</tspan>
</text>
<text x="1159" style="color:red;cursor:default;font-size:11px;fill:red;" text-anchor="start" transform="translate(0,0)" y="57" opacity="1">
<tspan>803,229,425.60
</tspan>
</text>
</g>
</svg>

**Comment by mrbean-bremen** [comment]
No information here, and outdated - closing.
