### ISSUE TITLE
NullReferenceException when parsing specific SVG (Bounds property throws exception)

### ISSUE THREAD

**Issue by JD-Robbs** [vvvv/SVG#323]
Great library and works like a charm!

Although, I have come across an exception when rendering [this flag icon (Bolivia)](https://github.com/lipis/flag-icon-css/blob/master/flags/4x3/bo.svg) using the following code:

           var svgDoc = SvgDocument.Open<SvgDocument>(s, null);
                            svgDoc.Width = 50;
                            svgDoc.Height = 50;
                            var myImg = svgDoc.Draw(); // throws exception from `Bounds` property of `svgDoc` object

Likewise, [this](https://github.com/lipis/flag-icon-css/blob/master/flags/4x3/eu.svg) flag renders rather strangely - with the flag's stars in the wrong positions.  [This one](https://github.com/lipis/flag-icon-css/blob/master/flags/4x3/tj.svg) renders as one big red square.

Just thought I'd post this - perhaps it helps improve the renderer with additional test cases.

**Comment by mrbean-bremen** [comment]
The exception for the Bolivian flag is still there, while the other two flags (eu and tajikistan) render fine(tested in the SVGViewer).

**Comment by mrbean-bremen** [comment]
The problem was a useless use element with no reference. Note that the flag is still not completely correct due to the strokes in the paths drawn too thick - this is handled in #338.
