### ISSUE TITLE
Build Error: The type 'System.Xml.XmlDocument' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Xml, Version=2.0.0.0, Culture=neutral ...

### ISSUE THREAD

**Issue by mounir01** [vvvv/SVG#325]
I work in a project in visual studio 2008  with .NET 3.5 and i need to manipulate Svg files but i have this  errors when i use SvgDocument.Open() method

Error 29	The type 'System.Xml.XmlDocument' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Xml, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.	

Error	30	The type 'System.ComponentModel.ITypeDescriptorContext' is defined in an assembly that is not referenced. You must add a reference to assembly 'System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.	

thanks for your help

**Comment by mrbean-bremen** [comment]
@mounir01 - is this still an issue?

**Comment by mrbean-bremen** [comment]
Closing this - probably outdated. Please reopen if you still have the issue.
