### ISSUE TITLE
Performance Question

### ISSUE THREAD

**Issue by flemingtech** [vvvv/SVG#327]
I absolutely love this library, and I'm trying to incorporate it into my software. I have reasonably large SVG files (~300KB) and have noticed that 're-render' times are in the 150ms range. I have to 're-render' the SVG multiple times a second as part of some animation elements. 

Is there a way to have a re-render only render a smaller invalid region? I.e., can I tell it which components where modified (color, text, etc) and only draw the modifications and anything else in a region?

When I run performance analysis, it shows that Svg.SvgRenderer.FillPath is the worst offender of time, but since that is a direct GDI call... Are there any tricks to speeding it up? Do different render targets (graphics, canvas, bmp) have difference performance?

**Comment by flemingtech** [comment]
I've come up with one solution so far, but figured I'd report back findings for other folks.

The rendering type plays a significant roll on rendering speeds. For example, it anti-aliasing is off for the SvgDocument render times are notably faster.

Because of the huge reduction in image quality, this wasn't a viable solution for my needs. Instead what I've come up with so far seems to work since I can't figure out how to get clipping regions to work.

After I load the SVG, I make new SVG with the same initial SvgDocument properties (basically a deep copy followed by deleting all children). As I walk the first document tree I'm looking for elements I know are going to be modified. For each one that I find, I remove it from the first SVG and put it into the 2nd SVG. When I'm doing this, I also apply any parent transforms to the new child since it doesn't need/have all of it's parents.

Once I'm done, I render the first SVG to an Image. When any of the 'animating' elements are changed, the 2nd SVG is rendered on top of a copy of the first SVG's rendering to form a complete composite. This prevents all the non-moving elements for having to re-render, unless of course the target graphics width/height changes. This is giving huge performance gains.

There is still one problem I'm working on, and that is of occlusion. It's possible based on the drawing order, that the moving components should be underneath non-moving components. So my next step is to detect any static elements that would be physically in the same bounds as a modifying element, and move those to a 3rd layer that is also an static SVG image.

**Comment by mrbean-bremen** [comment]
@flemingtech - did you get that last issue solved? 
Your post can actually be helpful to others, but I'm not sure where to put this kind of information. It will probably show up on Google searches even if close the issue, but I actually would like a place to collect helpful information - maybe in the Wiki, or in GitHub pages. Probably will create a separate issue to discuss this.

**Comment by tebjan** [comment]
wiki sounds good...

**Comment by flemingtech** [comment]
I did not get any further on this project unfortunately. The application I needed to use it on got shelved temporarily, so I haven't had time to revisit.

**Comment by mrbean-bremen** [comment]
Ok, thanks - maybe you will revisit later...

**Comment by mrbean-bremen** [comment]
I created a preliminary [Wiki page](https://github.com/vvvv/SVG/wiki/Q&A) to collect this kind of information (we can improve the format later), so we can put more information there later. I'm closing this issue now.
