### ISSUE TITLE
Invalid character when drawing special characters from html code

### ISSUE THREAD

**Issue by mhcgolds** [vvvv/SVG#328]
Hi everyone.

I'm having an issue when I try to draw a document from the svg html code. It throws an exception of invalid character when it finds an special character like "ç". I need to render these characters as the default language of my application is pt-br. Here is how I'm doing it:
```
using (var xmlStream = new MemoryStream(UTF8Encoding.Default.GetBytes(svg)))
{
    var svgDocument = SvgDocument.Open<Svg.SvgDocument>(xmlStream).Draw();
```
Where `svg` is a string that holds the html code. The code I'm sending as:
```
<input type="hidden" id="svg" name="svg" />

$("#svg").val($("#container").get(0).innerHTML);
```
Where `#container` is a `<div>` which contains the `<svg>` element. 

For now I'm replacing those characters prior to drawing and everything works well.

**Comment by mhcgolds** [comment]
Sure I can!!

    <svg style="width: 100%; height: 100%; display: block; min-width: 724px; min-height: 284px;"><g><g></g><g><g transform="translate(0.5,0.5)" style="visibility: visible;"><path d="M 25 3 L 3 3 L 3 203 L 25 203 Z" fill="white" stroke="black" stroke-miterlimit="10" pointer-events="all"></path><path d="M 25 3 L 643 3 L 643 203 L 25 203" fill="white" stroke="white" stroke-miterlimit="10" pointer-events="stroke" visibility="hidden" stroke-width="9"></path><path d="M 25 3 L 643 3 L 643 203 L 25 203" fill="white" stroke="black" stroke-miterlimit="10" pointer-events="none"></path></g><g style=""><g fill="black" font-family="Arial,Helvetica" text-anchor="middle" font-size="11px" transform="rotate(-90,15,103)"><rect fill="white" stroke="none" x="-23" y="96" width="75" height="12" stroke-width="0"></rect><text x="15" y="106.5">Fluxo Principal</text></g></g><g style="cursor: pointer; visibility: visible;"><image x="8" y="8" width="9" height="9" xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="http://localhost:3001/Content/js/mxgraph/images/expanded.gif" preserveAspectRatio="none"></image></g><g transform="translate(0.5,0.5)" style="visibility: visible; cursor: move;"><path d="M 47 3 L 25 3 L 25 103 L 47 103 Z" fill="white" stroke="black" stroke-miterlimit="10" pointer-events="all"></path><path d="M 47 3 L 643 3 L 643 103 L 47 103" fill="white" stroke="white" stroke-miterlimit="10" pointer-events="stroke" visibility="hidden" stroke-width="9"></path><path d="M 47 3 L 643 3 L 643 103 L 47 103" fill="white" stroke="black" stroke-miterlimit="10" pointer-events="none"></path></g><g style="cursor: move;"><g fill="black" font-family="Arial,Helvetica" text-anchor="middle" font-size="11px" transform="rotate(-90,37,53)"><rect fill="white" stroke="none" x="16" y="46" width="42" height="12" stroke-width="0"></rect><text x="37" y="56.5">Grupo 1</text></g></g><g style="cursor: pointer; visibility: visible;"><image x="30" y="8" width="9" height="9" xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="http://localhost:3001/Content/js/mxgraph/images/expanded.gif" preserveAspectRatio="none"></image></g><g style="visibility: visible;"><rect x="175" y="28" width="80" height="50" rx="7.5" ry="7.5" fill="#f2f4ff" stroke="#00468c" stroke-width="2" pointer-events="all"></rect></g><g style=""><clipPath id="mx-clip-176-29-77-47-0"><rect x="176" y="29" width="77" height="47"></rect></clipPath><g fill="#333333" font-family="Arial" clip-path="url(http://localhost:3001/#mx-clip-176-29-77-47-0)" text-anchor="middle" font-size="11px"><text x="214.5" y="56">Item 1</text></g></g><g transform="translate(0.5,0.5)" style="visibility: visible;"><rect x="303" y="23" width="92" height="60" fill="#eeeeee" stroke="#aaaaaa" pointer-events="all"></rect></g><g style=""><clipPath id="mx-clip-304-24-90-58-0"><rect x="304" y="24" width="90" height="58"></rect></clipPath><g fill="#333333" font-family="Arial" clip-path="url(http://localhost:3001/#mx-clip-304-24-90-58-0)" text-anchor="middle" font-size="11px"><text x="349" y="56.5">Descrição do Item 1</text></g></g><g transform="translate(0.5,0.5)" style="visibility: visible;"><path d="M 303 53 L 279 53 L 279 53 L 255 53" fill="white" stroke="white" stroke-miterlimit="10" pointer-events="stroke" visibility="hidden" stroke-width="9"></path><path d="M 303 53 L 279 53 L 279 53 L 255 53" fill="white" stroke="gray" stroke-miterlimit="10" stroke-dasharray="3 3"></path></g><g transform="translate(0.5,0.5)" style="visibility: visible;"><rect x="303" y="23" width="92" height="60" fill="#eeeeee" stroke="#aaaaaa" pointer-events="all"></rect></g><g style=""><clipPath id="mx-clip-304-24-90-58-1"><rect x="304" y="24" width="90" height="58"></rect></clipPath><g fill="#333333" font-family="Arial" clip-path="url(http://localhost:3001/#mx-clip-304-24-90-58-1)" text-anchor="middle" font-size="11px"><text x="349" y="56.5">Descrição do Item 1</text></g></g><g transform="translate(0.5,0.5)" style="visibility: visible;"><path d="M 47 103 L 25 103 L 25 203 L 47 203 Z" fill="white" stroke="black" stroke-miterlimit="10" pointer-events="all"></path><path d="M 47 103 L 643 103 L 643 203 L 47 203" fill="white" stroke="white" stroke-miterlimit="10" pointer-events="stroke" visibility="hidden" stroke-width="9"></path><path d="M 47 103 L 643 103 L 643 203 L 47 203" fill="white" stroke="black" stroke-miterlimit="10" pointer-events="none"></path></g><g style=""><g fill="black" font-family="Arial,Helvetica" text-anchor="middle" font-size="11px" transform="rotate(-90,37,153)"><rect fill="white" stroke="none" x="16" y="146" width="42" height="12" stroke-width="0"></rect><text x="37" y="156.5">Grupo 2</text></g></g><g style="cursor: pointer; visibility: visible;"><image x="30" y="108" width="9" height="9" xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="http://localhost:3001/Content/js/mxgraph/images/expanded.gif" preserveAspectRatio="none"></image></g><g style="visibility: visible;"><rect x="303" y="133" width="80" height="50" rx="7.5" ry="7.5" fill="#f2f4ff" stroke="#00468c" stroke-width="2" pointer-events="all"></rect></g><g style=""><clipPath id="mx-clip-304-134-77-47-0"><rect x="304" y="134" width="77" height="47"></rect></clipPath><g fill="#333333" font-family="Arial" clip-path="url(http://localhost:3001/#mx-clip-304-134-77-47-0)" text-anchor="middle" font-size="11px"><text x="342.5" y="161">tvdtevrt</text></g></g><g transform="translate(0.5,0.5)" style="visibility: visible;"><path d="M 255 53 L 279 53 L 279 158 L 296.63 158" fill="white" stroke="white" stroke-miterlimit="10" pointer-events="stroke" visibility="hidden" stroke-width="9"></path><path d="M 255 53 L 279 53 L 279 158 L 296.63 158" fill="white" stroke="black" stroke-miterlimit="10"></path><path d="M 301.88 158 L 294.88 161.5 L 296.63 158 L 294.88 154.5 Z" fill="black" stroke="black" stroke-miterlimit="10" pointer-events="all"></path></g></g><g></g><g></g></g></svg>

This one gives an exception with says "Invalid character at line 1, position 3037", which is the "ç" in text  "Descrição do Item 1".

Again, the code:

    using (var xmlStream = new MemoryStream(UTF8Encoding.Default.GetBytes(svg)))
    {
        var svgDocument = SvgDocument.Open<Svg.SvgDocument>(xmlStream).Draw();

Where `svg` is a string with the svg content. 
Cheers.

**Comment by haykpetros** [comment]
Hi @mhcgolds,

Actually when you use `UTF8Encoding.Default` you are still initializing ANSI encoder, as `Default` property is not overridden in `UTF8Encoding` and returns ANSI encoder.

So you have two options and both will work:

1st option:
````
using (var xmlStream = new MemoryStream(Encoding.UTF8.GetBytes(svg)))
{
    var svgDocument = SvgDocument.Open<Svg.SvgDocument>(xmlStream).Draw();
}
````

2nd option:
````
var utf8 = new UTF8Encoding();
using (var xmlStream = new MemoryStream(utf8.GetBytes(svg)))
{
    var svgDocument = SvgDocument.Open<Svg.SvgDocument>(xmlStream).Draw();
}
````

I guess you took your code from the SVGViewer sample app that is not correct and should be fixed:

````
private void textBox1_TextChanged(object sender, EventArgs e)
{
    using(var s = new MemoryStream(UTF8Encoding.Default.GetBytes(textBox1.Text)))
    {
        SvgDocument svgDoc = SvgDocument.Open<SvgDocument>(s, null);
       	RenderSvg(svgDoc);
    }
}
````

Hopefully above helps.

Thanks

**Comment by mhcgolds** [comment]
Thanks @haykpetros !! It works now with the first option.
