### ISSUE TITLE
Transform bounds to rendered coordinate system?

### ISSUE THREAD

**Issue by flemingtech** [vvvv/SVG#330]
I'm trying to implement click detection, but I'm having a heck of a time going from an SVGElement.Bounds to the rendered coordinate system, or vis-a-versa. Do I have to apply all the transforms up-hill of an element to do this, or is there something that already does this?

I've tried to follow the Posh mouse events, but I've seen nothing that actually converts mouse coordinates to Svg Element coordinates in order to determine if the mouse was over a specific element or not.

**Comment by tebjan** [comment]
hello, in posh we did not face this problem since the browser did all the work and even gave us the right events. i am afraid that you have to calculate the whole transform chain in order to get the global bounds for a svg element.

**Comment by flemingtech** [comment]
I was about the reply back with how I did it, so I'm glad to know it wasn't something simple I missed.

Step 1 - For each element that I know I want to be clickable: Find the total transform matrix by getting a list starting from the root down. In my case, I walk up the tree and insert at 0 index the parent's transforms.

`
SvgTransformCollection transforms = new SvgTransformCollection();
SvgElement el = element;
while (el != null) {
	foreach (SvgTransform t in el.Transforms) {
		transforms.Insert(0, t);
	}
	el = el.Parent;
}
TransformMatrix = transforms.GetMatrix();
`
Now I have a matrix representing the element. The harder part is getting the transform for the display. In my case it's an Image on a WinForm. There is no direct way to get the transform, so you have to jump through a few hoops to get it.

`
ISvgRenderer renderer = SvgRenderer.FromImage(svgImage.Image);
renderer.SetBoundable(new GenericBoundable(0, 0, svgImage.Image.Width, svgImage.Image.Height));
mySvg.ViewBox.AddViewBoxTransform(mySvg.AspectRatio, renderer, mySvg);
Matrix rootMatrix = renderer.Transform;
`
The above will change anytime the rendering area changes, so I do it during the mouse click (not optimal).

Finally, I can loop over all my elements that I want to respond to click events and see if they are within bounds as follows.

`
rootMatrix.Multiply(TransformMatrix);
rootMatrix.Invert();

//The following is the mouse coordinates x,y transformed into the specific elements coordinates
//Element is one of our SvgVisualElements
var points = new PointF[] { new PointF(x, y) };
rootMatrix.TransformPoints(points);
result = Element.Bounds.Contains(points[0]);
`

**Comment by mrbean-bremen** [comment]
Closing as solved. Still can be found by Googling...

**Comment by dolanor** [comment]
Thanks for this description. I’m facing the same problem. Tried to find another simpler way, but didn’t exist and finally decided to abandon. Someone suggested me to display in a WebBrowser widget and handle the events directly from there.
I’m glad you shared this. I had the logic for this, but couldn’t figure out how to use the library to achieve it!
