### ISSUE TITLE
ValidateFontFamily fails for Elements that don't have OwnerDocument

### ISSUE THREAD

**Issue by haykpetros** [vvvv/SVG#332]
Hi,

If one creates SvgText element at runtime it's OwnerDocument property will be Null. Afterwards trying to access Bounds property will throw "Object reference not set to an instance of an object.", because ValidateFontFamily expects "SvgDocument doc" not to be null.

`var svgText = new SvgText("Hello World!");`
`// This line will throw "Object reference not set to an instance of an object." exception.`
`var textWidth = svgText.Bounds.Width;`

So we need to modify ValidateFontFamily method (line 436 of SvgElementStyle.cs) to check for doc not being null:

`if (doc != null && doc.FontDefns().TryGetValue(f, out sFaces)) return sFaces;`

I created a Pull Request #333 to resolve this issue.

Thanks

**Comment by mrbean-bremen** [comment]
Fixed with #333.
