### ISSUE TITLE
SvgText.X and SvgText.Y are SvgUnitCollections

### ISSUE THREAD

**Issue by HughPH** [vvvv/SVG#335]
How can a block of text have many positions? And even if it could, under what circumstances would I want all the X coordinates in one collection and all the Y coordinates in another?

**Comment by dittodhole** [comment]
SVG 1.1 spec

x-Attribute: https://www.w3.org/TR/SVG/text.html#TextElementXAttribute
y-Attribute: https://www.w3.org/TR/SVG/text.html#TextElementYAttribute

in contrast, MDN

x-Attribute: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/x
y-Attribute: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/y

**Comment by Tulonium** [comment]
I think, you can close this issue.

**Comment by mrbean-bremen** [comment]
Closing as answered.
