### ISSUE TITLE
Rendering with antialiasing?

### ISSUE THREAD

**Issue by sk-zk** [vvvv/SVG#339]
I want to render images with antialiasing and according to the images on this page, that's what `shape-rendering:optimizeSpeed` is supposed to do:

https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/shape-rendering

But when I set `ShapeRendering` to `SvgShapeRendering.GeometricPrecision`, nothing happens:

http://i.imgur.com/3zdpLvF.png

Am I doing it wrong?

**Edit: Nevermind**, I figured it out. Code for Google:
```
svgDoc.ShapeRendering = SvgShapeRendering.GeometricPrecision;
using (ISvgRenderer r = SvgRenderer.FromImage(image)) 
{
    float scale = image.Height / svgDoc.Height;
    r.ScaleTransform(scale, scale);
    r.SmoothingMode = SmoothingMode.AntiAlias;
    svgDoc.Draw(r);
}
```

**Comment by mrbean-bremen** [comment]
Closing - solution is there.
