### ISSUE TITLE
Odd rendering with no fill?

### ISSUE THREAD

**Issue by robhol** [vvvv/SVG#342]
So, I decided to try using SVG in my otherwise System.Drawing based program.

![image](https://user-images.githubusercontent.com/163772/31574698-e5f28876-b0d4-11e7-82f1-4dd2e67ac3cf.png)

As you can see, it looks a little... uh, off.

I was unable to find any information at all on how to use it, so I'm not sure why it looks like it does.

This is the relevant part of my code:
```
        private static Image GetPieceImage(Piece piece, int size)
        {
            var svg = SvgDocument.Open<SvgDocument>(new MemoryStream(Properties.Resources.BlackQueen1)); //.svg file as byte[]
            return svg.Draw(size, size);
        }

//later:
var pieceImage = GetPieceImage(piece, squareSize);
g.DrawImage(pieceImage, sx + pieceOffsetX, sy + pieceOffsetY, squareSize, squareSize);
```

Any ideas?

**Comment by mrbean-bremen** [comment]
@robhol - If this is still an issue, can you provide the failing SVG?

**Comment by robhol** [comment]
I actually managed to track it down - still seems to fail. This is on 2.3.0 (nuget)

SVG (github is being an idiot and not accepting the file type for upload, so I'm posting it as code)
`<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="45" height="45">
  <g style="opacity:1; fill:000000; fill-opacity:1; fill-rule:evenodd; stroke:#000000; stroke-width:1.5; stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:4; stroke-dasharray:none; stroke-opacity:1;">
    <g style="fill:#000000; stroke:none;">
      <circle cx="6"    cy="12" r="2.75" />
      <circle cx="14"   cy="9"  r="2.75" />
      <circle cx="22.5" cy="8"  r="2.75" />
      <circle cx="31"   cy="9"  r="2.75" />
      <circle cx="39"   cy="12" r="2.75" />
    </g>
    <path
       d="M 9,26 C 17.5,24.5 30,24.5 36,26 L 38.5,13.5 L 31,25 L 30.7,10.9 L 25.5,24.5 L 22.5,10 L 19.5,24.5 L 14.3,10.9 L 14,25 L 6.5,13.5 L 9,26 z"
       style="stroke-linecap:butt; stroke:#000000;" />
    <path
       d="M 9,26 C 9,28 10.5,28 11.5,30 C 12.5,31.5 12.5,31 12,33.5 C 10.5,34.5 10.5,36 10.5,36 C 9,37.5 11,38.5 11,38.5 C 17.5,39.5 27.5,39.5 34,38.5 C 34,38.5 35.5,37.5 34,36 C 34,36 34.5,34.5 33,33.5 C 32.5,31 32.5,31.5 33.5,30 C 34.5,28 36,28 36,26 C 27.5,24.5 17.5,24.5 9,26 z"
       style="stroke-linecap:butt;" />
    <path
       d="M 11,38.5 A 35,35 1 0 0 34,38.5"
       style="fill:none; stroke:#000000; stroke-linecap:butt;" />
    <path
       d="M 11,29 A 35,35 1 0 1 34,29"
       style="fill:none; stroke:#ffffff;" />
    <path
       d="M 12.5,31.5 L 32.5,31.5"
       style="fill:none; stroke:#ffffff;" />
    <path
       d="M 11.5,34.5 A 35,35 1 0 0 33.5,34.5"
       style="fill:none; stroke:#ffffff;" />
    <path
       d="M 10.5,37.5 A 35,35 1 0 0 34.5,37.5"
       style="fill:none; stroke:#ffffff;" />
  </g>
</svg>
`

**Comment by mrbean-bremen** [comment]
Ok, thanks!

**Comment by mrbean-bremen** [comment]
@robhol - I had another look, and kind of found the cause: there is "fill:000000" in the SVG, which is actually invalid (should be "fill:#000000" instead). In a browser, this is ignored (which it probably should be), in SVG.NET, it is set to "none" instead. Replacing this with the correct value (or removing it, as this is the default anyway) fixes the image.
