### ISSUE TITLE
Still Active?

### ISSUE THREAD

**Issue by erslater** [vvvv/SVG#343]
What is the status of this project? I see there are several pull requests that havent been merged and no commits for many months.

I am looking for a library like this but am looking for something that is still being maintained.  If you could provide an update that would be great.

**Comment by tebjan** [comment]
sure, its maintained. but some pull requests do not meet the standards or are mere changes for personal projects. it takes time to review each one. but a nuget update with the best PR's can be expected soon.

**Comment by erslater** [comment]
Glad to hear. Looking forward to the update.

**Comment by mrbean-bremen** [comment]
Closing as answered :)
