### ISSUE TITLE
Text does not render properly, but it's worse if "renderer.SmoothingMode" is set.

### ISSUE THREAD

**Issue by fuzzlog** [vvvv/SVG#344]
Text rendering breaks when "renderer.SmoothingMode" is set to anything other than None or Default when in SvgTextBase.Render method.  

The text elements come from the browser in this format:

```
<text dy=".32em" x="-9" y="0" font-family="arial" font-size="11px" style="text-anchor: end;">84000</text>
```

or this

```
<text x="0" y="0" transform="translate(176.0546875, 0)" style="font-family:Helvetica;font-size: 12px;">United States Average COL</text>
```
 (Neither text outputs correctly)

The line below forces "renderer.SmoothingMode" to be bet to AntiAlias since RequiredSmoothRendering is on by default when rendering a text element:

```
if (this.RequiresSmoothRendering)
{
   renderer.SmoothingMode = SmoothingMode.AntiAlias; // SmoothingMode.HighQuality; 
}
```
and the result is this:

![antialiason](https://user-images.githubusercontent.com/8751788/32027938-bb1ab400-b9a0-11e7-9f6c-4778f671f330.PNG)

If renderer.SmoothingMode is forced to be "SmoothingMode.None" the result is this:

![antialiasoff](https://user-images.githubusercontent.com/8751788/32027957-d35e161a-b9a0-11e7-995f-c125965faa11.PNG)

Neither result is acceptable for the reports we are trying to create.

Anyone how the fonts can be made to look good?

Thanks,

fuzzlog

**Comment by mrbean-bremen** [comment]
@fuzzlog - is this still an issue? I have to tried to reproduce this without success, but maybe I've used the wrong data (I just made some SVG that include your lines above). Do you have any test data that shows that behavior?

**Comment by fuzzlog** [comment]
We've upgraded at least once since my error submission.  The issue no longer shows up.

**Comment by mrbean-bremen** [comment]
Ok, thanks! Closing the issue in this case.
