### ISSUE TITLE
external image opacity

### ISSUE THREAD

**Issue by ondator** [vvvv/SVG#347]
if svg contains external image wit provided opacity, then opacity ignores

example:
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="499" height="396" viewBox="0 0 499 396" xml:space="preserve">
<desc>Created with Fabric.js 2.0.0-rc.1</desc>
<defs>
</defs>
<g transform="translate(249.5 198)">
	<image xlink:href="https://cdn.pixabay.com/photo/2016/03/28/12/35/cat-1285634_960_720.png" x="-249.5" y="-198" style="stroke: none; stroke-width: 0; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(0,0,0); fill-rule: nonzero; opacity: 1;" width="499" height="396"></image>
</g>
<g transform="translate(439.5 190.5)">
	<image xlink:href="http://www.gettyimages.ca/gi-resources/images/Homepage/Hero/UK/CMS_Creative_164657191_Kingfisher.jpg" x="-500" y="-184.5" style="stroke: none; stroke-width: 0; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(0,0,0); fill-rule: nonzero; opacity: 0.52;" width="1000" height="369"></image>
</g>
</svg>

**Comment by mrbean-bremen** [comment]
Fixed in #348.
