### ISSUE TITLE
DeepCopy on SvgGradientStop doesn't copy StopColor

### ISSUE THREAD

**Issue by robertvo** [vvvv/SVG#350]
DeepCopy in SvgGradientStop 
The stop-color is not copied 

		public override SvgElement DeepCopy<T>()
		{
			var newObj = base.DeepCopy<T>() as SvgGradientStop;
			newObj.Offset = this.Offset;
                        _newObj.StopColor = this.StopColor;_
			return newObj;
		}

**Comment by mrbean-bremen** [comment]
Actually, this is not a bug - the stop color is not a separate member, but read from an attribute which is copied by the base class. Closing.

**Comment by robertvo** [comment]
well, when I did a deep copy of a document, lots of gradient surfaces were black. So that appeared as a bug

**Comment by mrbean-bremen** [comment]
Ok, that sounds indeed like a bug - do you have an example file to reproduce this?
