### ISSUE TITLE
Clipping

### ISSUE THREAD

**Issue by Zefugi** [vvvv/SVG#353]
Is there a way to set up clipping, so that only part of a SvgGroup is rendered?

**Comment by Zefugi** [comment]
Allow me to specify:

I have this structure (created programmatically)
SvgDocument
--SvgGroup
----SvgRectangle (I call this R1)
----SvgGroup
------SvgRectangle (I call this R2)

What I want to achieve is this: When R2 can't be contained inside R1, I want the outer parts to not be rendered.
How di I do this? Is it even possible?

**Comment by tebjan** [comment]
i don't know whether svg supports this, but a quick google brought up this: https://stackoverflow.com/questions/39193276/how-can-i-merge-two-shapes-in-svg
