### ISSUE TITLE
erro in asp.net core 2

### ISSUE THREAD

**Issue by javadmjt** [vvvv/SVG#357]
Unfortunately, it does not work in asp.net core 2 and the following error occurs

Reference to type 'Bitmap' claims it is defined in 'System.Drawing', but it could not be found  

And

Reference to type 'Graphics' claims it is defined in 'System.Drawing', but it could not be found

**Comment by toolgood** [comment]
You can try ZKWeb.System.Drawing
 https://github.com/zkweb-framework/ZKWeb.System.Drawing

**Comment by Devvox93** [comment]
@toolgood It is no longer maintained. [System.Drawing.Common](https://www.nuget.org/packages/System.Drawing.Common) is the official now.

Anyway, that still doesn't work. I have that package and it works for other stuff, but not with Svg.
When trying to call SvgDocument.Draw() I get the errors the reporter mentioned.

This seems like an easy fix concerning references.
Please keep us updated on this issue.

**Comment by mrbean-bremen** [comment]
@javadmjt , @Devvox93 - if this is still an issue for you, can you please check with current master?

**Comment by mrbean-bremen** [comment]
I'm closing this one in favor of #400, which is basically a duplicate, but with a nicer issue number ;)
