### ISSUE TITLE
How to render SVG image to single-color bitmap image?

### ISSUE THREAD

**Issue by UweKeim** [vvvv/SVG#366]
I'm trying to change the color of an SVG image during rendering to a bitmap image.

E.g. I have this source SVG image:

![image](https://user-images.githubusercontent.com/415439/44666115-fcf9d000-aa17-11e8-96af-1392bdd3955d.png)

and want to render it e.g. as a green bitmap image:

![image](https://user-images.githubusercontent.com/415439/44666130-03884780-aa18-11e8-83d7-2083ee2e4e3a.png)

(In my scenario, all source SVG images are single-colored only).

My current, _unsuccessful_ code looks like this:

```csharp
var svgDoc = SvgDocument.Open<SvgDocument>(svgFilePath, null);

// Tried several things, all without any changes in the resulting bitmap:
svgDoc.Color = new SvgColourServer(Color.DarkGreen);
svgDoc.StopColor = new SvgColourServer(Color.DarkGreen);
svgDoc.Stroke = new SvgColourServer(Color.DarkGreen);
svgDoc.Fill = new SvgColourServer(Color.DarkGreen);

var bitmap = svgDoc.Draw();
```

I've also checked-out the source code and looked through it, but I still found no way to change the color.

**My question:**

How to change the color during rendering an SVG image to a bitmap image with SVG.NET?

  [1]: https://github.com/vvvv/SVG
  [2]: https://i.stack.imgur.com/f3JF8.png
  [3]: https://i.stack.imgur.com/s0Tn6.png
  [4]: https://github.com/vvvv/SVG/issues

**Comment by UweKeim** [comment]
I was able to find a solution with the following fragment:

```csharp
var svgDoc = SvgDocument.Open<SvgDocument>(svgFilePath, null);

// Recursively change all nodes.
processNodes(svgDoc.Descendants(), new SvgColourServer(Color.DarkGreen));

var bitmap = svgDoc.Draw();
```

together with this function:

```csharp
private void processNodes(IEnumerable<SvgElement> nodes, SvgPaintServer colorServer)
{
    foreach (var node in nodes)
    {
        node.Fill = colorServer;
        node.Color = colorServer;
        node.StopColor = colorServer;
        node.Stroke = colorServer;

        processNodes(node.Descendants(), colorServer);
    }
}
```

Although I am unsure about the costs of this recursive iteration of all nodes and whether there is a faster way.

**Comment by mrbean-bremen** [comment]
If you have no control over the svg itself, this should be the correct approach, as you can't know where the color is defined. The approach with setting the color top-level would only work, if no color was set in the elements themselves.

**Comment by mrbean-bremen** [comment]
Ok, I think we can close this one.

**Comment by APerricone** [comment]
This code does not works on VisualBasic with the versione 3.1.1
