### ISSUE TITLE
SVG to Postscript

### ISSUE THREAD

**Issue by mlgoff59** [vvvv/SVG#368]
Does the SVG Rendering Engine support ouputting to Postscript?

**Comment by mrbean-bremen** [comment]
There is no such support, as far as I know. You have to rely on other image conversion tools for this.

**Comment by mrbean-bremen** [comment]
Closing this as answered.

**Comment by mlgoff59** [comment]
I ran out of time waiting for a response, so I wrote my own library to convert SVg to PostScript.

**Comment by mrbean-bremen** [comment]
Understandable...
