### ISSUE TITLE
How to show a svg image on winform in design time?

### ISSUE THREAD

**Issue by 0x7d9** [vvvv/SVG#371]
Just like PictureBox can load a png file in design time, how to load a svg image on winform in design time?
Thanks!
![image](https://user-images.githubusercontent.com/37729896/47921793-6c94ab80-def0-11e8-8c83-382b824bc9a1.png)

**Comment by mwbowers** [comment]
Think this is really a Visual Studio question, but I had a similar issue in the designer when creating a Web Control; I think you may be able to follow similar logic for WinForms.  For the design-time render, I used the SVG library to generate a PNG in a temp file then rendered that for my control.  Hope this helps.

**Comment by 0x7d9** [comment]
@mwbowers Thank you for your answer, that is a solution. Even though I have given up using svg in winfrom, I used a png graphic with a high enough pixel instead.
