### ISSUE TITLE
feMerge not working - Possible fix

### ISSUE THREAD

**Issue by yarligayan** [vvvv/SVG#372]
in SvgMerge.cs, line 29, please comment out "result.Save(@"C:\test.png");"

**Comment by mrbean-bremen** [comment]
Thanks - I removed the debug code, and it could indeed have broken the code (depending on permissions), 
and feMerge seems to work (kind of) now, though as filters are generally not working, this may not help much.

**Comment by mrbean-bremen** [comment]
Anyway, I'm closing this, as there is another issue regarding the filters.
