### ISSUE TITLE
Are there any plans to release updated NuGet package?

### ISSUE THREAD

**Issue by haykpetros** [vvvv/SVG#382]
Hi,

I see that @mrbean-bremen is merging some pull requests and updates the project, so I was wondering if  there is an ETA on when we can expect NuGet package to be updated?

Thanks

**Comment by mrbean-bremen** [comment]
@tebjan - from my perspective, this is ready for a NuGet release now (the regression has been fixed). Maybe wait a bit for any more regressions to show up...

**Comment by tebjan** [comment]
yes, we can however release a 2.4 nuget preview. might get some people on bord to test it.

**Comment by tebjan** [comment]
published latest release build: https://www.nuget.org/packages/Svg/

**Comment by haykpetros** [comment]
@tebjan great!

**Comment by tebjan** [comment]
there seems to be a new bugfix commit, i'll make an updated nuget soon.

**Comment by mrbean-bremen** [comment]
@tebjan - feel free to make the release without integrating the latest fixes - they are not that important, I think, and you can always make a new release (not sure how much effort is a nuget release, though).

**Comment by mrbean-bremen** [comment]
Ok, thanks, I hoped for that!

**Comment by tebjan** [comment]
it's up: https://www.nuget.org/packages/Svg/2.4.0

**Comment by mrbean-bremen** [comment]
I added a [release notes](https://github.com/vvvv/SVG/wiki/Release-Notes) page to the Wiki (or should that better be a file?) for reference.
Closing this one too as answered...
