### ISSUE TITLE
text with "text-anchor=middle" is not on the middle line compared to Chrome

### ISSUE THREAD

**Issue by heindlalex** [vvvv/SVG#385]
It seems that there is some additional spacing from characters included when calculating the length of the text.

SVG-png-output:
![output](https://user-images.githubusercontent.com/38215829/50291534-26c77e80-046f-11e9-964a-d3f7aba1c3e3.png)

Chrome:
![chrome](https://user-images.githubusercontent.com/38215829/50291542-2c24c900-046f-11e9-8450-cef9536c0bd6.png)

TestSVG:
[Test_text-anchor-middle.zip](https://github.com/vvvv/SVG/files/2699293/Test_text-anchor-middle.zip)

**Comment by heindlalex** [comment]
@mrbean-bremen - added a pull request with a new commit to fix the issue,
test files also included,  please merge if ok. Thx.

**Comment by mrbean-bremen** [comment]
Fixed by @heindlalex.
