### ISSUE TITLE
Property "stroke-dashoffset" not working

### ISSUE THREAD

**Issue by heindlalex** [vvvv/SVG#388]
Property "stroke-dashoffset" is not working, tested on path element. 
TestSVG: 
[DashTest.zip](https://github.com/vvvv/SVG/files/2713184/DashTest.zip)

Chrome output:
![dash_chrome](https://user-images.githubusercontent.com/38215829/50492284-16874480-0a17-11e9-984b-b548325aae2f.png)

SVGViewer Output:
![output](https://user-images.githubusercontent.com/38215829/50492298-24d56080-0a17-11e9-9918-c92a5286a373.png)

This is not working in the latest released version (2.2.1) and master from 26/12/2018, I do not know if it ever worked.

**Comment by mrbean-bremen** [comment]
No, it didn't work before. You may check the svgW3CTestRunner - all tests that are in the "failing" tab do not work, including this one (painting-stroke-04.svg).
I'm not sure how to handle this issue-wise - basically, we could write an issue for each of the failing tests, which would be a bit overkill in my opinion.
Or maybe some issues that collect related stuff... 
@tebjan - what do you think?
