### ISSUE TITLE
Svg not rendered properly

### ISSUE THREAD

**Issue by tom-2015** [vvvv/SVG#391]
I have a simple svg that is not rendered properly:
SVG file:
[test.zip](https://github.com/vvvv/SVG/files/2714652/test.zip)
Output:
![output](https://user-images.githubusercontent.com/9294742/50512936-33faf380-0a95-11e9-9c72-76d1e521fe24.png)
Expected output:
![expected](https://user-images.githubusercontent.com/9294742/50513009-7290ae00-0a95-11e9-8ecd-af5fec96b84d.png)

I have no idea what the problem can be...

**Comment by mrbean-bremen** [comment]
Ok, I played around a bit, and it looks like the fill color is the problem - if adding "fill:none" to the `st2` style, it works correctly. The default fill color is indeed black, but there is a global style set that has `fill:none` (`st3`), so I guess, this global style is not taken into account.

**Comment by tom-2015** [comment]
ok thank you for the fast response!
