### ISSUE TITLE
Wrong default value for cx, cy on radial gradient

### ISSUE THREAD

**Issue by pablojmp** [vvvv/SVG#397]
If you use a radial gradient server with cx = 0 or cy = 0 the library won't persist the attributes when writing to a file because SvgDefaults.IsDefault will return true.
I'm guessing that these defaults where intended for SvgCircle, and this happens because the SvgRadialGradientServer attributes have the same name (the defaults for SvgRadialGradientServer are 50% for both cx and cy).
Perhaps the Dictionary in SvgDefaults could be something like Dictionary<Type,Dictionary<string,string>>, so the Type could be taken into account when searching for defaults? Or any class with default values could handle it's own defaults...

**Comment by pablojmp** [comment]
Thanks for the awesome work, btw!

**Comment by mrbean-bremen** [comment]
Thanks for the report!
