### ISSUE TITLE
Where I can find the documentation of this library?

### ISSUE THREAD

**Issue by nitinjs** [vvvv/SVG#401]
Where I can find the documentation of this library?

**Comment by joreg** [comment]
also whoever wants to work on documentation, here is a great introduction on how to best do so: https://www.divio.com/blog/documentation/

**Comment by mrbean-bremen** [comment]
So, there is a number of documenation tasks that any volunteer can have a go at:
**Usage documentation**
- [ ] Getting started
- [ ] Tutorials
- [ ] Q&A Pages
- [ ] Generated API documentation

**Project documentation**
- [ ] Contributing guide
- [ ] Issue and PR templates
- [ ] Style guide

**Comment by dsafa** [comment]
How about [docfx](https://github.com/dotnet/docfx) for documentation? It can handle normal markdown pages as well as generated api documentation.

**Comment by tebjan** [comment]
can docfx be hosted on github?

**Comment by mrbean-bremen** [comment]
I had a quick glance, and noticed that the project has an example where it is integrated with AppVeyor and creates GitHub pages (via the gh-pages branch), so this should not be too complicated (hopefully). I have done something like this before, but with Travis.CI instead of AppVeyor, and for Python only (using Sphinx). 
@dsafa - do you have experience with docfx?

**Comment by tebjan** [comment]
auto doc via gh-pages sound great!

**Comment by dsafa** [comment]
@mrbean-bremen I've use it recently, it was easy to use although I did not do anything too complex.

**Comment by mrbean-bremen** [comment]
@dsafa - thanks! I think I will wait for the .Net Core merge, as that changes the AppVeyor config, and try to put something together afterwards. I may come back to you then...

**Comment by wieslawsoltes** [comment]
The documentation (at least Getting started and API) would be much appreciated.

I am currently exploring SVG library myself by debugging stuff by hand: https://github.com/wieslawsoltes/Draw2D/blob/SVG/src/SvgDemo/Program.cs

**Comment by mrbean-bremen** [comment]
I may have a go at the API stuff some time later, but my free time is limited, and I would appreciate any help...

**Comment by mrbean-bremen** [comment]
Getting Started and generated API pages are now existing, the documentation link is in the README, and specific documentation requests can be handled in separate issues - closing this one.
