### ISSUE TITLE
SVG to Bitmap, do not scale correctly.

### ISSUE THREAD

**Issue by georgeemr** [vvvv/SVG#405]
Hi, in the version 2.4.0 when I draw a SvgDocument to a Bitmap, the image don't get scale. The size maintain original.

![image](https://user-images.githubusercontent.com/3822009/51212984-7dde3900-18df-11e9-9c68-f46c9df11e8d.png)

In the version 2.3.0 I get the SVG scaled correctly with the size I want. I just get empty space on the last version.

Image on 2.3.0:
![image](https://user-images.githubusercontent.com/3822009/51213154-e2999380-18df-11e9-8fa4-28877b5306c0.png)

Image on 2.4.0:
![image](https://user-images.githubusercontent.com/3822009/51213177-f34a0980-18df-11e9-8c56-d73d215cc63c.png)

The only change I made was change the library version. Do I missing something in the last version? Or this is a bug?

**Comment by mrbean-bremen** [comment]
Looks like a regression to me - I will have a look in th evening.

**Comment by mrbean-bremen** [comment]
Ok, found the offending commit - it came from PR #308 (from march 2017, so this is quite some time ago...).
I tested this by scaling the image in the image viewer to the picture box - this worked correctly before this commit, but no scaling happened after that change. I cannot reproduce the behavior described in that PR.

@tebjan, @alex-sherman - can you comment on this PR? Can this be reverted, or do I miss something?

**Comment by alex-sherman** [comment]
Is it possible to get a small application that exhibits this behavior? There is probably more going on here, because in the use case that I was observing for PR #308, calling scale there was for sure double scaling the result image which I'm very sure is undesirable. It seems likely that there is another path way to get here *without* scale already being called, which would cause this behavior.

I can try to take a look at this tonight, but I would caution against reverting that PR since there is certainly undesirable behavior without that patch, and I believe a more holistic solution is the right path forward.

**Comment by mrbean-bremen** [comment]
Thank you - that would be very helpful. We will certainly wait for you before reverting anything.

**Comment by mrbean-bremen** [comment]
Ah, just saw your edit - that sounds sensible, will check this.

**Comment by mrbean-bremen** [comment]
@alex-sherman - I created a PR with that changes, can you please check it?

**Comment by alex-sherman** [comment]
This appears to work to me just modifying the SVGViewer to draw both without parameters, and with a fixed height and width. Looks good to me!

**Comment by mrbean-bremen** [comment]
Thanks - I'll merge it in this case!

**Comment by UweKeim** [comment]
I'm having this issue, too.

Any chance to get a Nuget update within a reasonable time-frame?

(No problem if not possible, just being curious whether waiting or downgrading)

**Comment by mrbean-bremen** [comment]
As far as I understood @tebjan, creating a new NuGet release is easy, so I think it makes sense to make a dot release (2.4.1) somewhere soon, as this fixes a regression bug.

**Comment by mrbean-bremen** [comment]
@UweKeim - the release is out now.

**Comment by UweKeim** [comment]
Works perfectly now, thanks a lot!

Grüße aus Stuttgart 😄.
