### ISSUE TITLE
Conflicting types when project also references ExCSS

### ISSUE THREAD

**Issue by helluvamatt** [vvvv/SVG#408]
.NET Framework project that has both SVG and ExCSS as NuGet dependencies: Using some types from ExCSS namespace causes the following compile error:

`The type 'StyleRule' exists in both 'ExCSS, Version=4.0.0.2, Culture=neutral, PublicKeyToken=null' and 'Svg, Version=2.4.0.42491, Culture=neutral, PublicKeyToken=12a0bac221edeae2'`

It appears this is caused by directly including ExCSS code under `External` without changing the namespace.

**Comment by mrbean-bremen** [comment]
Fixed with #409.
