### ISSUE TITLE
How to use the "limitless" quality of vector graphics?

### ISSUE THREAD

**Issue by thedonciuxx** [vvvv/SVG#412]
Hi, I am working on a project and wanted to use vector images (svg's).

I am a fan of making something vector. It's just cool to have something not limited by the size.

My idea was to make a generator which when given an array of strings would generate an image from a tilemap.

Using vector graphics theoretically I can make images of any size.
The thing is... I don't know how to scale my opened svgDocument before drawing it.

I can set the height and width of the document, but exactly as it sounds, it's not scaling.
Scaling it before it's drawn would give an expected result - a blurry image.

Any suggestions or instructions on how I should do this?

**Comment by thedonciuxx** [comment]
Downgrading the version fixed it.
Thank you.

Hope the fix gets released soon. :)

**Comment by tebjan** [comment]
yes, @mrbean-bremen would you say current master is worth a 2.4.1 release?

**Comment by mrbean-bremen** [comment]
Thanks @tebjan!
Closing the issue in this case.
