### ISSUE TITLE
Color Broke 2.4.1

### ISSUE THREAD

**Issue by kbiel** [vvvv/SVG#416]
We have simple SVG icons we're rendering to single color PNGs when requested. In 2.4.0, the following code works the set the color:

```csharp
            svgDocument.ApplyRecursive(e =>
            {
                { if (e.Fill is SvgColourServer colorServer) colorServer.Colour = color; }
                { if (e.Color is SvgColourServer colorServer) colorServer.Colour = color; }
                { if (e.StopColor is SvgColourServer colorServer) colorServer.Colour = color; }
                { if (e.Stroke is SvgColourServer colorServer) colorServer.Colour = color; }
            });
```

After an update to 2.4.1 it will render black regardless of the code above.

**Comment by mrbean-bremen** [comment]
Ok, I understood the problem. Due to a bug fix, unitialized colors are now set to a static color (which did exist before, it just was not set where it should have been).
This means that the code above won't work anymore, because it would just change that static color.
If you instead use:
```c#
                svgDocument.ApplyRecursive(e =>
                {
                    { if (e.Fill is SvgColourServer) e.Fill = new SvgColourServer(color); }
                    { if (e.Color is SvgColourServer) e.Color = new SvgColourServer(color); }
                    { if (e.StopColor is SvgColourServer) e.StopColor = new SvgColourServer(color); }
                    { if (e.Stroke is SvgColourServer) e.Stroke = new SvgColourServer(color); }
                });
```
it should work.

**Comment by mrbean-bremen** [comment]
The code mentioned [here](https://github.com/vvvv/SVG/wiki/Q&A#how-to-render-an-svg-image-to-a-single-color-bitmap-image) should also work, though your usage of `ApplyRecursive` is a bit nicer.

**Comment by kbiel** [comment]
When we first started using the package, we had seen and implemented the code you link to. The problem with replacing the SvgColourServer instance is that it would then render the strokes too thick causing it to overflow the target bitmap. I'll look at the changes made and see if there is a better answer.

**Comment by mrbean-bremen** [comment]
Hm, strange. The changes are in [this commit](https://github.com/vvvv/SVG/commit/36881dd7ad3a36af79b9d0485feea660c88a6ff5) that I made myself. As far as I understood the code, `SvgColourServer` is only responsible for holding the color, not the pen used for drawing, so I don't know why the strokes would render too thick in that case. I haven't seen this in a quick test I made, but that depends on the data - if you have an example image that shows this behavior, it would be nice if you could post it so that I could have a look. I really want to understand this - maybe my change was the wrong way to do it after all.

**Comment by kbiel** [comment]
I'll see if I can get permission to share an SVGs. The ones I saw this behavior on are assets of my employer. 

Tomorrow I'll post PNGs of the different behaviors so you can at least see the results.

**Comment by mrbean-bremen** [comment]
Thanks! Some stripped-down version will do, as long as the problem remains. As of now, I'm just clueless...

**Comment by kbiel** [comment]
Here's is more info:
After loading the SVG, `Fill` and `Color` are `SvgColourServer.NotSet`, `StopColor` and `Stroke` are `null`. The result after setting the `Color` property:
![svgcolourserver_notset_setting_color_property_2_4_0](https://user-images.githubusercontent.com/17048116/52536301-c6dead00-2d26-11e9-83e3-d72f45d956db.png)

This is the result after setting the `Fill` and `Color` properties to `new SvgColourServer(color)` where color is argb `0xFF7F7F7F`;
![svgcolourserver_notset_setting_new_svgcolourserver_2_4_0](https://user-images.githubusercontent.com/17048116/52536414-1d98b680-2d28-11e9-8b4e-c704bafaa6a1.png)

And the result is the same of 2.4.1 using `new SvgColourServer(color)`:
![svgcolourserver_notset_setting_new_svgcolourserver_2_4_1](https://user-images.githubusercontent.com/17048116/52536446-b2031900-2d28-11e9-8dde-46a0831dc457.png)

Here are the results for setting all four properties, including `StopColor` and `Stroke` in 2.4.0:
![svgcolourserver_notset_or_null_setting_new_svgcolourserver_2_4_0](https://user-images.githubusercontent.com/17048116/52536507-7caafb00-2d29-11e9-92ee-64404b7b5946.png)

And the same for 2.4.1:
![svgcolourserver_notset_or_null_setting_new_svgcolourserver_2_4_1](https://user-images.githubusercontent.com/17048116/52536509-86346300-2d29-11e9-98c6-cb57ca867220.png)

Notice that the strokes now overflow the boundaries.

**Comment by mrbean-bremen** [comment]
Hm, I have trouble to see the difference... the one before the last is the correct one, and the last one is incorrect?

**Comment by kbiel** [comment]
Sorry, I should have been more explicit. Only the very first image is correct. I mistyped the property name and left vague my meaning. All colors passed are argb `0xFF7F7F7F`.

Image 1: Using my original code with 2.4.0, setting the `Colour` property of the existing `SvgColourServer` after loading the `SvgDocument`. (I had not realized that those were instances of `SvgColourServer.NotSet` until your previous comments.) Only `Fill` and `Color` are set to `SvgColourServer.NotSet`, `StopColor` and `Stroke` are `null`.

Image 2: Setting only `Color` and `Fill` to `new SvgColourServer(color)`. `StopColor` and `Stroke` remain null. Resulting color is opaque black regardless of the value passed to `SvgColourServer.ctor`.

Image 3: Same code as image 2 but using 2.4.1. Results are the same and always opaque black.

Image 4 & 5: Setting all four properties, `Color`, `Fill`, `Stroke`, and `StopColor` to `new SvgColourServer(color)` for both 2.4.0 and 2.4.1 respectively. Not only are the inside black, but the stroke/brush paints beyond the boundary of the target bitmap. My screenshot might be a bit confusing on that point. I captured more of the window to the left. Where the bottom line ends abruptly without the rounded stop on the left is the left edge of the bitmap created by the `Draw()` routine.

**Comment by mrbean-bremen** [comment]
Ah, ok - thanks - now I get it! I will try to understand this. Do you have by any chance a part of the SVG (say, one of the lines on the left with the respective style)? That would make it less guesswork...

**Comment by kbiel** [comment]
I'll see what I can do tomorrow about getting you the full SVG. What I do feel comfortable sharing at this time is the viewbox is 0, 0, 32, 18 and it contains a single `path` element with `d` attribute and a long list of coordinates(?).

**Comment by mrbean-bremen** [comment]
Ok, thanks!

**Comment by mrbean-bremen** [comment]
Judging by your images, only the fill color is actually relevant - the stroke is not set and shall remain so (setting the stroke color works correctly, as can be seen in the last images, but is not needed). Why the fill color remains black is still unclear to me - I can change it without problems for some test images given the code above, but obviously your svg is different in some way. I will have another look tomorrow evening, if you can get an SVG (or part of it).

**Comment by kbiel** [comment]
Here is the SVG file. Let me know what I can do to help.

[Sent.zip](https://github.com/vvvv/SVG/files/2853983/Sent.zip)

**Comment by mrbean-bremen** [comment]
Ok, I checked this, and I got the same result as before. Maybe we are using different code...
Here is what I use:
```C#
            SvgDocument svgDoc = SvgDocument.Open(openSvgFile.FileName);
            var color = Color.Gray;
            svgDoc.ApplyRecursive(el =>
            {
                { if (e.Fill is SvgColourServer) el.Fill = new SvgColourServer(color); }
            });
            svgImage.Image = svgDoc.Draw(400, 0);
```
This gives the follwing:
![grafik](https://user-images.githubusercontent.com/4623701/52661634-c0a52800-2f02-11e9-96ca-bfced69c11f4.png)
exactly what I would have expected.
Note that I don't set `Stroke`, as you don't want that. If you have other images where you want to change the stroke, you may have to change

**Comment by mrbean-bremen** [comment]
Can you show the code that produced the second image (all black instead of gray) above? Something has to be different there, but I'm now positive can find the problem.

**Comment by kbiel** [comment]
Here is the code that produces all black:
```csharp
        private static Image GetImageFromSVG(SvgDocument svgDocument, int height, Color color)
        {
            svgDocument.ApplyRecursive(e =>
            {
                { if (e.Fill is SvgColourServer) e.Fill = new SvgColourServer(color); }
                //{ if (e.Color is SvgColourServer) e.Color = new SvgColourServer(color); }
                //{ if (e.StopColor is SvgColourServer) e.StopColor = new SvgColourServer(color); }
                //{ if (e.Stroke is SvgColourServer) e.Stroke = new SvgColourServer(color); }
            });
            return svgDocument.Draw(0, height);
        }
```
It does the same, draws black only, with either the e.Color set or not.

**Comment by mrbean-bremen** [comment]
Ok, that is strange... looks indeed like the same code. I have used master so far, as there have been no relevant changes, but I will try again with 2.4.1 release, just in case.

**Comment by mrbean-bremen** [comment]
Ok, no difference.

**Comment by kbiel** [comment]
I'm working for the moment, even if it's not the proper way. ;)

When I have a little more time this week, I'll clone the repo and debug into it.

**Comment by mrbean-bremen** [comment]
Ok, I won't have more time today anyway, and I don't have any ideas - we seem to use the same code with different results... It will be interesting to see what the problem is, if you can find it!

**Comment by mrbean-bremen** [comment]
@kbiel - did you find the time to check this yet?

**Comment by kbiel** [comment]
So, I do know how your `ApplyRecursive` was working because there is a check in there and it stops traversal if the supplied SvgElement parameter is an SvgDocument. That is what had me stymied. After looking though the code, I could not find a reason for `ApplyRecursive` to have that behavior which I find to be counter-intuitive. There is a PR addressing the issue.

**Comment by mrbean-bremen** [comment]
Great that you found that out - I couldn't understand why it worked for me!
I commented on the PR - I don't know the code well enough to make sure this will not break anything (still familiarizing myself with the code, and having a hard time to understand it in some places), but  I will have a closer look in the next days.

**Comment by mrbean-bremen** [comment]
I merged you PR now - does that resolve your problem now?

**Comment by kbiel** [comment]
Take your time. I found `ApplyRecursive` was only called from one place in the code (except for calling itself of course). That call site already guarded against calling `ApplyRecursive` on an `SvgDocument`. The same is mostly true for `ApplyRecursiveDepthFirst` except that there is no explicit guard against calling it on an `SvgDocument`, but the call site is in the `SvgElementCollection` calling it on a member of the collection. I assume an `SvgDocument` being the root will never be a member of a child collection.

**Comment by kbiel** [comment]
And I posted too late. :)
