### ISSUE TITLE
Error in SvgDocument.Draw(), if SVG-file contains line with arrow

### ISSUE THREAD

**Issue by SergeMul** [vvvv/SVG#42]
If SVG-file contains line with arrow (style attribute "marker-end:url(#mrkr13-6);"), raise an exeption in SvgDocument.Draw(): Object reference not set to an instance of the object.

 Look like parser can`t to resolve link url(#mrkr13-6).

**Comment by mrbean-bremen** [comment]
This seems to be fixed. Cannot really verify without the original svg - please reopen if there remain issues.
