### ISSUE TITLE
Consider switching to a different test framework

### ISSUE THREAD

**Issue by gvheertum** [vvvv/SVG#420]
Currently the MSTest framework is used in the unit tests. However, this might be limiting for more complex/extensive tests. 

When writing my testcases for the lexer I missed attributes like [Theory] (XUnit) or [TestCase] (NUnit), that would have allowed us to have testcases instead of asserting multiple smaller elements in 1 test.

This code
```
        [TestMethod]
        public void Lexer_ImportantAfterHex_Success()
        {
            //Important should be valid on 3 digit hex
            GenerateLexerTestFile("border-top: 1px solid #333 !important;");
            //Important should be valid on 6 digit hex
            GenerateLexerTestFile("border-top: 1px solid #009c46 !important;");
            //Whitespace should not break the parser
            GenerateLexerTestFile("border-bottom: 1px solid #009c46  ;");
        }
```
would become
```
        [TestCase("border-top: 1px solid #333 !important;")] //Important should be valid on 3 digit hex
        [TestCase("border-top: 1px solid #009c46 !important;")]  //Important should be valid on 6 digit hex
        [TestCase("border-bottom: 1px solid #009c46  ;")]   //Whitespace should not break the parser
        public void Lexer_ImportantAfterHex_Success(string contentToTest)
        {
            GenerateLexerTestFile(contentToTest);
        }
```
If one of the cases fails, the rest of the cases will still be tested, in the old scenario the first failing Assert/call will stop execution of the other cases.

**Comment by mrbean-bremen** [comment]
Agreed. I'm also not very happy with the testing framework, having used nunit before. 
As always - any help is welcome!

**Comment by gvheertum** [comment]
If you are okay with NUnit, I can try setting up a migration to NUnit. xUnit is a bit quircky if you are not used to it.

**Comment by mrbean-bremen** [comment]
That would be nice! I'm not very proficient with NUnit, even if have used it - currently I'm mostly working with Pytest and Google test...

**Comment by mrbean-bremen** [comment]
And of course we should check with @tebjan if this is OK, as this would be an infrastructure change that may have some impact.

**Comment by mrbean-bremen** [comment]
@gvheertum - are you still planning to work on this? I'm really not very happy with MSTest...
@tebjan - would that be ok (e.g. switching to NUnit)?

**Comment by gvheertum** [comment]
@mrbean-bremen If we have a formal go (or if @tebjan doesn't have a problem), I can give it a try. The conversion from MSTest to NUnit is relatively easy (getting the most out of the framework is a different story, but getting it replaced is easy). I'll try to create a PR this week.

**Comment by tebjan** [comment]
@gvheertum sounds great, i fully support this idea!

**Comment by gvheertum** [comment]
@tebjan Thanks, I'm on it. Locally I already have the test adapter changed to NUnit without too much problems. Only issue is with the image test which uses the CSV, that needs some additional work, but I hope to be able to put in a PR tomorrow.

**Comment by gvheertum** [comment]
PR #493 has a change proposal for the migration to NUnit, including some cleanups on tests since they could be refactored due to the new framework.

**Comment by gvheertum** [comment]
Code was merged, so this issue is resolved :)
