### ISSUE TITLE
Sample code

### ISSUE THREAD

**Issue by MikeRensing** [vvvv/SVG#429]
I looked but didn't see any sample code for creating a new SVG file.  Is there a basic walk through for using this project to create a new SVG file, and write entities to it?

**Comment by mrbean-bremen** [comment]
Looks like you are out of luck here... lack of documentation is a bit of a problem with this project, see also #401. This may need some community effort...

**Comment by mrbean-bremen** [comment]
Closing as answered. Missing documentation is handled in #401.
