### ISSUE TITLE
StackOverflowException when SVG contains image with href

### ISSUE THREAD

**Issue by AnReZa** [vvvv/SVG#436]
I want to render the following SVG using this library. However, this will throw a StackOverflowException. When I delete the image tag, it works:

```svg
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:svgjs="http://svgjs.com/svgjs" id="ap-canvas" class="bg-raster" version="1.1">
    <image xlink:href="http://localhost:51124/Diagnosis/LK-1808081/Photos/7" data-bind="attr: { 'xlink:href': modeData.imgSrc, href: modeData.imgSrc }" x="0" y="0" width="100%" height="100%" href="http://localhost:51124/Diagnosis/LK-1808081/Photos/7" />
    <defs id="SvgjsDefs1006" />
    <rect id="SvgjsRect1008" width="313" height="448" stroke-opacity="1" stroke="#ff0d28" stroke-width="3" fill-opacity="1" fill="rgba(0, 0, 0, 0)" x="360" y="48" />
</svg>
```
```cs
public MemoryStream RenderAs(ImageFormat imgFormat = null) {
    try {
        string s = Shape.Replace(@"""/Diagnosis/", @"""http://localhost:51124/Diagnosis/");

        SvgDocument svg = SvgDocument.FromSvg<SvgDocument>(s);
        Bitmap bitmap = svg.Draw();
        MemoryStream ms = new MemoryStream();

        //bitmap.Save(ms, imgFormat ?? ImageFormat.Jpeg);

        bitmap.Save(@"C:\test\test.jpg", imgFormat ?? ImageFormat.Jpeg);

        return ms;
    } catch(Exception ex) {
        throw ex;
    }
}
```
Is this a bug, or am I doing something wrong here?

**Comment by AnReZa** [comment]
I realized, that it has something to do with the width="100%" and height="100%" settings. When I replace them with absolute units for testing purposes, it works. Is there a way to fix that?

**Comment by AnReZa** [comment]
Have anyone had the chance to reproduce this issue? It's kind of a breaking issue, because you cannot catch the StackOverflowException. It will crash your software anyways, even if you put a try catch block around it.

**Comment by mrbean-bremen** [comment]
I could reproduce this, but last time I checked, I didn't really understand the problem. I will have another go sometime this week.

**Comment by AnReZa** [comment]
@mrbean-bremen Do you think, that it would make sense to make a hotfix release out of that?

**Comment by mrbean-bremen** [comment]
I think it makes sense to wait a few days until possible problems with the .NET Core addition are settled.

**Comment by AnReZa** [comment]
Sure, it's not urgent. ;-)
