### ISSUE TITLE
image line quality issue and could not render text

### ISSUE THREAD

**Issue by zhang16** [vvvv/SVG#44]
Hi, I tried to use your library to render a svg file and convert o png image on fly, however the text was not rendered and the line quality also suffers.
![test](https://f.cloud.github.com/assets/6305344/1834196/2cf54d28-73d8-11e3-913e-5f8ec9c364c2.png)

Below is svg file.
<?xml version="1.0"?>

<!DOCTYPE svg PUBLIC '-//W3C//DTD SVG 1.0//EN' 'http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd'>
<svg fill-opacity="1" xmlns:xlink="http://www.w3.org/1999/xlink" color-rendering="auto" color-interpolation="auto" stroke="black" text-rendering="auto" stroke-linecap="square" width="200" stroke-miterlimit="10" stroke-opacity="1" shape-rendering="auto" fill="black" stroke-dasharray="none" font-weight="normal" stroke-width="1" height="200" xmlns="http://www.w3.org/2000/svg" font-family="&apos;Dialog&apos;" font-style="normal" stroke-linejoin="miter" font-size="12" stroke-dashoffset="0" image-rendering="auto">
  
  <defs id="genericDefs" />
  <g>
    <defs id="defs1">
      <clipPath clipPathUnits="userSpaceOnUse" id="clipPath1">
        <path d="M0 0 L200 0 L200 200 L0 200 L0 0 Z" />
      </clipPath>
    </defs>
    <g font-size="9" stroke-linecap="round" fill="red" text-rendering="optimizeLegibility" font-family="sans-serif" stroke-linejoin="bevel" shape-rendering="geometricPrecision" stroke="red" stroke-width="0.9827786684036255">
      <line clip-path="url(#clipPath1)" fill="none" x1="73.17775972705775" x2="74.4877905697992" y1="134.46340431368876" y2="125.7719175707457" />
      <line clip-path="url(#clipPath1)" fill="none" x1="77.38300842963912" x2="78.69303927238059" y1="135.0972435709658" y2="126.40575682802273" />
      <line clip-path="url(#clipPath1)" fill="none" x1="74.4877905697992" x2="75.79782141254066" y1="125.7719175707457" y2="117.08043082780266" stroke="black" />
      <line clip-path="url(#clipPath1)" fill="none" x1="78.69303927238059" x2="80.00307011512204" y1="126.40575682802273" y2="117.71427008507968" stroke="black" />
      <line clip-path="url(#clipPath1)" fill="none" x1="77.74782531447713" x2="70.90850491583984" y1="118.4099209769094" y2="113.74695128359578" stroke="black" />
      <line clip-path="url(#clipPath1)" fill="none" x1="70.90850491583984" x2="64.06918451720256" y1="113.74695128359578" y2="109.08398159028215" stroke="rgb(51,51,153)" />
      <line clip-path="url(#clipPath1)" fill="none" x1="52.1030697582636" x2="44.934409325031794" y1="108.636241165863" y2="112.77506919671839" stroke="rgb(51,51,153)" />
      <line clip-path="url(#clipPath1)" fill="none" x1="44.934409325031794" x2="37.76574889179999" y1="112.77506919671839" y2="116.91389722757378" stroke="black" />
      <line clip-path="url(#clipPath1)" fill="none" x1="37.76574889179999" x2="37.76574889179996" y1="116.91389722757377" y2="140.54027716286083" stroke="black" />
      <line clip-path="url(#clipPath1)" fill="none" x1="37.76574889179996" x2="58.22679411522154" y1="140.54027716286083" y2="152.35346713050444" stroke="black" />
      <line clip-path="url(#clipPath1)" fill="none" x1="37.76574889179995" x2="53.97404572686986" y1="145.450928016482" y2="154.80879255731503" stroke="black" />
      <line clip-path="url(#clipPath1)" fill="none" x1="58.22679411522154" x2="58.226794115221495" y1="152.35346713050444" y2="175.97984706579152" stroke="black" />
      <line clip-path="url(#clipPath1)" fill="none" x1="58.226794115221495" x2="37.765748891799916" y1="175.97984706579152" y2="187.79303703343504" stroke="black" />
      <line clip-path="url(#clipPath1)" fill="none" x1="53.974045726869825" x2="37.76574889179992" y1="173.52452163898093" y2="182.88238617981386" stroke="black" />
      <line clip-path="url(#clipPath1)" fill="none" x1="37.765748891799916" x2="17.304703668378387" y1="187.79303703343504" y2="175.97984706579146" stroke="black" />
      <line clip-path="url(#clipPath1)" fill="none" x1="17.304703668378387" x2="17.30470366837841" y1="175.97984706579146" y2="152.35346713050438" stroke="black" />
      <line clip-path="url(#clipPath1)" fill="none" x1="21.55745205673006" x2="21.55745205673008" y1="173.52452163898087" y2="154.80879255731497" stroke="black" />
      <line clip-path="url(#clipPath1)" fill="none" x1="37.76574889179996" x2="17.30470366837841" y1="140.54027716286083" y2="152.35346713050438" stroke="black" />
      <line clip-path="url(#clipPath1)" fill="none" x1="57.6983725558849" x2="57.07978254371704" y1="98.0494115878124" y2="89.79490153131457" stroke="rgb(51,51,153)" />
      <line clip-path="url(#clipPath1)" fill="none" x1="57.07978254371704" x2="56.46119253154917" y1="89.79490153131457" y2="81.54039147481673" stroke="black" />
      <line clip-path="url(#clipPath1)" fill="none" x1="56.46119253154917" x2="73.78055456767405" y1="81.54039147481674" y2="65.47037195061665" stroke="black" />
      <line clip-path="url(#clipPath1)" fill="none" x1="73.78055456767405" x2="81.96575605038298" y1="65.47037195061665" y2="66.704092568681" stroke="black" />
      <line clip-path="url(#clipPath1)" fill="none" x1="81.96575605038298" x2="90.15095753309191" y1="66.704092568681" y2="67.93781318674536" stroke="rgb(51,51,153)" />
      <line clip-path="url(#clipPath1)" fill="none" x1="101.12632169014464" x2="105.78929138345826" y1="63.149310755730184" y2="56.30999035709289" stroke="rgb(51,51,153)" />
      <line clip-path="url(#clipPath1)" fill="none" x1="105.78929138345826" x2="110.45226107677189" y1="56.30999035709289" y2="49.4706699584556" stroke="black" />
      <line clip-path="url(#clipPath1)" fill="none" x1="110.45226107677189" x2="100.20115900863752" y1="49.4706699584556" y2="28.184037175527507" stroke="black" />
      <line clip-path="url(#clipPath1)" fill="none" x1="113.21852920076395" x2="105.09807868649955" y1="45.41329981606585" y2="28.551010573388883" stroke="black" />
      <line clip-path="url(#clipPath1)" fill="none" x1="100.20115900863752" x2="113.51037272561666" y1="28.184037175527507" y2="8.663005976271918" stroke="black" />
      <line clip-path="url(#clipPath1)" fill="none" x1="113.51037272561666" x2="121.76488278211448" y1="8.663005976271918" y2="9.281595988439815" stroke="black" />
      <line clip-path="url(#clipPath1)" fill="none" x1="115.64102427948663" x2="122.67130441651895" y1="13.087349516523037" y2="13.614196179225589" stroke="black" />
      <line clip-path="url(#clipPath1)" fill="none" x1="121.76488278211448" x2="130.0193928386123" y1="9.281595988439815" y2="9.90018600060771" stroke="rgb(51,51,153)" />
      <line clip-path="url(#clipPath1)" fill="none" x1="122.67130441651895" x2="129.70158455355127" y1="13.614196179225589" y2="14.14104284192814" stroke="rgb(51,51,153)" />
      <line clip-path="url(#clipPath1)" fill="none" x1="140.13870985249616" x2="143.73025021568037" y1="16.79941952126206" y2="24.257329932067254" stroke="rgb(51,51,153)" />
      <line clip-path="url(#clipPath1)" fill="none" x1="143.73025021568037" x2="147.32179057886458" y1="24.257329932067254" y2="31.71524034287245" stroke="black" />
      <line clip-path="url(#clipPath1)" fill="none" x1="147.32179057886455" x2="163.8308106918602" y1="31.71524034287245" y2="32.95242036720824" stroke="black" />
      <line clip-path="url(#clipPath1)" fill="none" x1="147.32179057886455" x2="134.01257686188544" y1="31.71524034287245" y2="51.23627154212803" stroke="black" />
      <line clip-path="url(#clipPath1)" fill="none" x1="142.42487090100252" x2="131.88192530801547" y1="31.348266945011076" y2="46.811928001876915" stroke="black" />
      <line clip-path="url(#clipPath1)" fill="none" x1="110.45226107677189" x2="134.01257686188544" y1="49.4706699584556" y2="51.23627154212803" stroke="black" />
      <line clip-path="url(#clipPath1)" fill="none" x1="100.67858126572548" x2="104.81740929658088" y1="75.11542551466914" y2="82.28408594790095" stroke="rgb(51,51,153)" />
      <line clip-path="url(#clipPath1)" fill="none" x1="104.81740929658088" x2="108.95623732743627" y1="82.28408594790095" y2="89.45274638113276" stroke="black" />
      <line clip-path="url(#clipPath1)" fill="none" x1="108.95623732743626" x2="100.32455147980879" y1="89.45274638113276" y2="111.44592323838563" stroke="black" />
      <line clip-path="url(#clipPath1)" fill="none" x1="77.74782531447713" x2="100.32455147980879" y1="118.4099209769094" y2="111.44592323838563" stroke="black" />
    </g>
    <g font-size="9" fill="white" text-rendering="optimizeLegibility" font-family="sans-serif" shape-rendering="geometricPrecision" stroke="white">
      <rect x="71" y="136" clip-path="url(#clipPath1)" width="7" rx="2.5" ry="3.5" height="13" stroke="none" />
      <text x="71" y="146" clip-path="url(#clipPath1)" fill="red" stroke="none" xml:space="preserve">O
      </text>
      <text font-size="7" x="79" y="113" clip-path="url(#clipPath1)" fill="red" stroke="none" xml:space="preserve">
      </text>
      <rect x="55" y="99" clip-path="url(#clipPath1)" width="7" rx="2.5" ry="3.5" height="13" stroke="none" />
      <text x="55" y="109" clip-path="url(#clipPath1)" fill="rgb(51,51,153)" stroke="none" xml:space="preserve">N
      </text>
      <text font-size="7" x="38" y="111" clip-path="url(#clipPath1)" fill="rgb(51,51,153)" stroke="none" xml:space="preserve">
      </text>
      <text font-size="7" x="43" y="138" clip-path="url(#clipPath1)" fill="rgb(51,51,153)" stroke="none" xml:space="preserve">
      </text>
      <text font-size="7" x="62" y="148" clip-path="url(#clipPath1)" fill="rgb(51,51,153)" stroke="none" xml:space="preserve">
      </text>
      <text font-size="7" x="63" y="174" clip-path="url(#clipPath1)" fill="rgb(51,51,153)" stroke="none" xml:space="preserve">
      </text>
      <text font-size="7" x="38" y="182" clip-path="url(#clipPath1)" fill="rgb(51,51,153)" stroke="none" xml:space="preserve">
      </text>
      <text font-size="7" x="23" y="174" clip-path="url(#clipPath1)" fill="rgb(51,51,153)" stroke="none" xml:space="preserve">
      </text>
      <text font-size="7" x="18" y="147" clip-path="url(#clipPath1)" fill="rgb(51,51,153)" stroke="none" xml:space="preserve">
      </text>
      <text font-size="7" x="57" y="76" clip-path="url(#clipPath1)" fill="rgb(51,51,153)" stroke="none" xml:space="preserve">
      </text>
      <text font-size="7" x="78" y="61" clip-path="url(#clipPath1)" fill="rgb(51,51,153)" stroke="none" xml:space="preserve">
      </text>
      <rect x="94" y="63" clip-path="url(#clipPath1)" width="7" rx="2.5" ry="3.5" height="13" stroke="none" />
      <text x="94" y="73" clip-path="url(#clipPath1)" fill="rgb(51,51,153)" stroke="none" xml:space="preserve">N
      </text>
      <text font-size="7" x="114" y="45" clip-path="url(#clipPath1)" fill="rgb(51,51,153)" stroke="none" xml:space="preserve">
      </text>
      <text font-size="7" x="106" y="28" clip-path="url(#clipPath1)" fill="rgb(51,51,153)" stroke="none" xml:space="preserve">
      </text>
      <text font-size="7" x="118" y="5" clip-path="url(#clipPath1)" fill="rgb(51,51,153)" stroke="none" xml:space="preserve">
      </text>
      <rect x="134" y="4" clip-path="url(#clipPath1)" width="7" rx="2.5" ry="3.5" height="13" stroke="none" />
      <text x="134" y="14" clip-path="url(#clipPath1)" fill="rgb(51,51,153)" stroke="none" xml:space="preserve">N
      </text>
      <text font-size="7" x="151" y="28" clip-path="url(#clipPath1)" fill="rgb(51,51,153)" stroke="none" xml:space="preserve">
      </text>
      <rect x="167" y="27" clip-path="url(#clipPath1)" width="15" rx="5" ry="3.5" height="13" stroke="none" />
      <rect x="181" y="33" clip-path="url(#clipPath1)" width="4" rx="1.5" ry="3" height="10" stroke="none" />
      <text x="167" y="37" clip-path="url(#clipPath1)" fill="black" stroke="none" xml:space="preserve">CH
      </text>
      <text font-size="7" x="181" y="41" clip-path="url(#clipPath1)" fill="black" stroke="none" xml:space="preserve">3
      </text>
      <text font-size="7" x="140" y="51" clip-path="url(#clipPath1)" fill="black" stroke="none" xml:space="preserve">
      </text>
      <text font-size="7" x="113" y="85" clip-path="url(#clipPath1)" fill="black" stroke="none" xml:space="preserve">
      </text>
      <text font-size="7" x="106" y="110" clip-path="url(#clipPath1)" fill="black" stroke="none" xml:space="preserve">
      </text>
    </g>
  </g>
</svg>

**Comment by mrbean-bremen** [comment]
Closing this due to missing data and feedback.
