### ISSUE TITLE
SvgText wrong position in some scenario

### ISSUE THREAD

**Issue by francois-dorin** [vvvv/SVG#473]
### Scenario
In some scenario, the position of an SvgText element can be incorrect. Example : 
```CSharp
SvgText text = new SvgText("Hello world!");
text.X.Add(new SvgUnit(text.Bound.Width));
text.Y.Add(new SvgUnit(200));
```
The text will be rendered at 0,0, whatever are the values for X and Y.

### Workaround
A workaround is to instanciate new coordinates like bellow: 
```CSharp
text.X = new SvgUnitCollection() { new SvgUnit(text.Bound.Width)) };
text.Y = new SvgUnitCollection() { new SvgUnit(200)); }
```

### Explanation 
I investigate to find twhat cause the bug. In fact, using the `Bound` property put some data in cache (the `_path` attribute). Setting a new collection for X and/or Y invalidates the cache, whereas adding new elements does not.

### Possible fixes
Several approches can be used to fix this issue.

#### Using a read only collection
X and Y properties can be changed for read-only collection. No Add method, no bug! But it break compatibility and can have a large impact on existing code.

#### Using an `ObservableCollection`
Using an `ObservableCollection` for `SvgUnitCollection` instead of a `List` will allow to be notified when the underlying collection is modified (and then invalidates the cache)

#### Disabling cache
Disabling the cache will avoid this issue, but can lead to performance issues.

According to you, what is the best approach to fix this issue? I believe using an `ObservableCollection` is the better one, but I would like confirmation before submitting a PR

**Comment by mrbean-bremen** [comment]
Thanks - `ObservableCollection` sounds like a sensible way to fix this, a respective PR would be very nice!

**Comment by francois-dorin** [comment]
Thank you for your feedback. I will make a PR a soon as possible!
