### ISSUE TITLE
SVG re-throws ArgumentException due to bounds zero and if opacity is not one

### ISSUE THREAD

**Issue by NMGo** [vvvv/SVG#479]
Svg.dll will re-throw an ArgumentException from CBitmap if rendering a path where the bounds width or height is zero and opacity is not one (the default).

The above is reproducible using master at commit 80674303f5abebcc247a3c4dbe4d6bb2de1bf2cd. SVGViewer can be used to verify the bug.

The original exception is thrown by the CBitmap constructor in line 154 of Source\Basic Shapes\SvgVisualElement.cs

Test svg:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="200" height="200">
  <g id="Layer 1">
    <path d="M100,50 L100,150" stroke="black" opacity="0.5" />
  </g>
</svg>
```

Expected result:
![line_opacity](https://user-images.githubusercontent.com/49908665/58982609-c209a180-87cc-11e9-89b2-aed2ea9bdded.png)

**Comment by H1Gdev** [comment]
Thanks.
I try to fix this issue.

**Comment by H1Gdev** [comment]
Calculation of Bounds in `SvgPath` seems to be wrong.

**Comment by mrbean-bremen** [comment]
@H1Gdev - are you still working on this?

**Comment by H1Gdev** [comment]
@mrbean-bremen 

Yes.I am still working.

I know direct cause of this issue.
But I need to check many of `<path>`.

After attribute consolidation is over, I will fix this issue.

**Comment by mrbean-bremen** [comment]
Thank you!
