### ISSUE TITLE
Error when render node "text" with nested node "tspan"

### ISSUE THREAD

**Issue by SergeMul** [vvvv/SVG#48]
If SVG-node "text" contains more then 1 node "tspan", the rendered text is overlayed. In the sample the result text must be "E1/1".
![error_svg](https://f.cloud.github.com/assets/6252804/2134441/cdd12dea-92e4-11e3-933d-3ee8d252193f.jpg)

**Comment by mrbean-bremen** [comment]
This specific problem seems to be gone, though there may still be some issues with tspan.
Closing.
