### ISSUE TITLE
class css attribute

### ISSUE THREAD

**Issue by lroye** [vvvv/SVG#481]
hi, i want to add a class to th path when i create it with codebehind.
How can i add customattribute to the path?

thanks

**Comment by mrbean-bremen** [comment]
Can you elaborate a bit what you are doing? What path are you speaking about - an SVG path? Do you create an SVG programatically? Thanks

**Comment by lroye** [comment]
sorry, yes i create a path:
- create a SvgDocument
      set SvgDocument.ID
      set SvgDocument.Width
- create a SvgViewBox
-create a path
        set path.ID
        set ...

i want to add a class attribute to the path when i create it in c#. I know i can add on with javascript but i want add class attribute with codebehind.

**Comment by mrbean-bremen** [comment]
Ah, ok, thanks! I'm not sure, but I think this is currently not possible - #404 may be a related issue. I may have a closer look later tonight...

**Comment by mrbean-bremen** [comment]
Ok, the custom attributes actually are publicly accessible (`SvgElement.CustomAttributes`) , so I guess it should be possible to add one, e.g.:
```C#
    element.CustomAttributes[attributeName] = attributeValue;
```

**Comment by lroye** [comment]
thanks it's work fine.
