### ISSUE TITLE
Null Reference Exception when using .Draw() function

### ISSUE THREAD

**Issue by cbarker0** [vvvv/SVG#485]
I am trying to "draw" an SVGDocument type to bitmap so i can, save it to memorystream as a png and in turn a base64 string so the code can be run on a server via a http call.

       var Image = sDoc.Draw();
        MemoryStream m = new MemoryStream();
        Image.Save(m, ImageFormat.Png);
        string Base64String = Convert.ToBase64String(m.ToArray());

Unfortunately the code returns a Null Reference Exception

for the line

"var Image = sDoc.Draw();"

sDoc is referenced correctly and definitely contains the SVG as the return function "sDoc.GetXML()" works as expected and if converted looks correct. Any ideas?

The Full Code for the function which declares and draws the SVG is as follows;

        //Draw and export image
    private static string DrawSystemGraphicsToSVG(Hangar HangarI)
    {
        int OuterListLength = HangarI.Planes.Count();

        float deltax = Convert.ToSingle(HangarI.Length);
        float deltay = Convert.ToSingle(HangarI.Depth);

        float scalefactorx = 2400 / deltax;
        float scalefactory = 2400 / deltay;

        float scalefactor = Math.Min(scalefactorx, scalefactory);

        float x1 = Convert.ToSingle(HangarI.XMin) * scalefactor + 300;
        float y1 = Convert.ToSingle(HangarI.YMin) * scalefactor + 300;

        SvgDocument sDoc = new SvgDocument
        {
            Width = 3000,
            Height = 3000,
        };

        //(0,0) is top left corner of the panel
        sDoc.ViewBox = new SvgViewBox(-50, -50, 3000, 3000);

        //Create a group to add all elements to
        SvgGroup group = new SvgGroup();
        sDoc.Children.Add(group);

        //Draw the Hangar wall 
        SVG.rectangle(x1, y1, deltax * scalefactor, deltay * scalefactor, group);
        SVG.rectangle(x1 - 2 * scalefactor, y1 - 2 * scalefactor, (deltax + 4) * scalefactor, (deltay + 4) * scalefactor, group);

        //Draw dimension line Y
        SVG.dimensionLine(x1 + deltax*scalefactor + 100, y1, x1 + deltax*scalefactor + 100, y1 + deltay*scalefactor, Convert.ToString(Math.Round((HangarI.Depth),0)), group, sDoc);

        //Draw dimension line X
        SVG.dimensionLine(x1, y1 + deltay*scalefactor + 100, x1 + deltax*scalefactor, y1 + deltay*scalefactor + 100, Convert.ToString(Math.Round((HangarI.Length),0)), group, sDoc);

        //Draw Planes 
        int NoOfPlanes = HangarI.Planes.Count();

        for(int k = 0; k < NoOfPlanes; k++)
        {
            //Plane PAths
            SVG.path(HangarI.Planes[k].Points.X, HangarI.Planes[k].Points.Y, group, scalefactor);

            //Plane Names 
            float nameXcoor = (float)(HangarI.Planes[k].CenterX * scalefactor + 300);
            float nameYcoor = (float)(HangarI.Planes[k].CenterY * scalefactor + 300);
            SVG.standardText(HangarI.Planes[k].Type, nameXcoor, nameYcoor, group, false, 90);
        }

       var Image = sDoc.Draw();
        MemoryStream m = new MemoryStream();
        Image.Save(m, ImageFormat.Png);
        string Base64String = Convert.ToBase64String(m.ToArray());

        //return Base64String;

        return sDoc.GetXML();
    }

**Comment by mrbean-bremen** [comment]
Hm, difficult to say without knowing what your SVG class actually does. Some of the rendering obviously fails. I guess there is not callstack from the exception? Have you tried to comment out parts of your drawing code to narrow down where the problem comes from?

**Comment by cbarker0** [comment]
Message ---
Object reference not set to an instance of an object.

HelpLink ---


Source ---
Svg

StackTrace ---
   at Svg.SvgMarkerElement.RenderStroke(ISvgRenderer renderer) in C:\Dev\vvvv\SVG\Source\Basic Shapes\SvgMarkerElement.cs:line 63
   at Svg.SvgVisualElement.RenderFillAndStroke(ISvgRenderer renderer) in C:\Dev\vvvv\SVG\Source\Basic Shapes\SvgVisualElement.cs:line 216
   at Svg.SvgVisualElement.Render(ISvgRenderer renderer, Boolean renderFilter) in C:\Dev\vvvv\SVG\Source\Basic Shapes\SvgVisualElement.cs:line 145
   at Svg.SvgVisualElement.Render(ISvgRenderer renderer) in C:\Dev\vvvv\SVG\Source\Basic Shapes\SvgVisualElement.cs:line 129
   at Svg.SvgElement.RenderChildren(ISvgRenderer renderer) in C:\Dev\vvvv\SVG\Source\SvgElement.cs:line 800
   at Svg.SvgVisualElement.Render(ISvgRenderer renderer, Boolean renderFilter) in C:\Dev\vvvv\SVG\Source\Basic Shapes\SvgVisualElement.cs:line 168
   at Svg.SvgGroup.Render(ISvgRenderer renderer) in C:\Dev\vvvv\SVG\Source\Document Structure\SvgGroup.cs:line 55
   at Svg.SvgElement.RenderChildren(ISvgRenderer renderer) in C:\Dev\vvvv\SVG\Source\SvgElement.cs:line 800
   at Svg.SvgVisualElement.Render(ISvgRenderer renderer, Boolean renderFilter) in C:\Dev\vvvv\SVG\Source\Basic Shapes\SvgVisualElement.cs:line 168
   at Svg.SvgGroup.Render(ISvgRenderer renderer) in C:\Dev\vvvv\SVG\Source\Document Structure\SvgGroup.cs:line 55
   at Svg.SvgElement.RenderChildren(ISvgRenderer renderer) in C:\Dev\vvvv\SVG\Source\SvgElement.cs:line 800
   at Svg.SvgElement.Render(ISvgRenderer renderer) in C:\Dev\vvvv\SVG\Source\SvgElement.cs:line 790
   at Svg.SvgFragment.Render(ISvgRenderer renderer) in C:\Dev\vvvv\SVG\Source\Document Structure\SvgFragment.cs:line 169
   at Svg.SvgDocument.Draw(Bitmap bitmap) in C:\Dev\vvvv\SVG\Source\SvgDocument.cs:line 526
   at Svg.SvgDocument.Draw() in C:\Dev\vvvv\SVG\Source\SvgDocument.cs:line 506
   at HangarAutomationLibrary.HangarAutomation.DrawSystemGraphicsToSVG(Hangar HangarI, Boolean whiteBackground) in C:\Users\chris-x.barker\Documents\Coding Stuff\MRO_Hanger_Automation_Repo\HangerAutomationLibrary\HangerAutomationLibrary\HangarAutomation.cs:line 752

**Comment by cbarker0** [comment]
From commenting out the code the rendering issue would seem to stem from; 

            public static void dimensionLine(double startX, double startY, double endX, double endY, string text, SvgGroup group, SvgDocument doc, double offset = 10)
        {
            SvgPath endPath = new SvgPath();
            endPath.PathData = SvgPathBuilder.Parse(@"M0,0 L0,4 L9,2 z");
            endPath.Fill = new SvgColourServer(Color.Black);

            var endMarker = new SvgMarker()
            {
                ID = "endMarkerArrow",
                MarkerUnits = Svg.DataTypes.SvgMarkerUnits.StrokeWidth,
                MarkerWidth = 2,
                MarkerHeight = 5,
                RefX = 9,
                RefY = 2,
                Orient = new SvgOrient() { IsAuto = true },
                Children = { endPath },
                Overflow = SvgOverflow.Inherit //this is important for some reason!
            };

            SvgPath startPath = new SvgPath();
            startPath.PathData = SvgPathBuilder.Parse(@"M0,0 L0,-4 L-9,-2 z");
            startPath.Fill = new SvgColourServer(Color.Black);

            var startMarker = new SvgMarker()
            {
                ID = "startMarkerArrow",
                MarkerUnits = Svg.DataTypes.SvgMarkerUnits.StrokeWidth,
                MarkerWidth = 2,
                MarkerHeight = 5,
                RefX = -9,
                RefY = -2,
                Orient = new SvgOrient() { IsAuto = true },
                Children = { startPath },
                Overflow = SvgOverflow.Inherit
            };

            //Add markers to defs table so that they are available for use bot not shown in the
            //rendered image
            addToDefs(startMarker, doc);
            addToDefs(endMarker, doc);

            //Draw line in local coordinates, then transform to suit
            double deltaX = endX - startX;
            double deltaY = endY - startY;
            double length = Math.Sqrt(Math.Pow(deltaX, 2) + Math.Pow(deltaY, 2));

            SvgLine s = new SvgLine();
            s.StartX = new SvgUnit(SvgUnitType.Pixel, Convert.ToSingle(0));
            s.StartY = new SvgUnit(SvgUnitType.Pixel, Convert.ToSingle(-offset));
            s.EndX = new SvgUnit(SvgUnitType.Pixel, Convert.ToSingle(length));
            s.EndY = new SvgUnit(SvgUnitType.Pixel, Convert.ToSingle(-offset));
            s.StrokeWidth = 1;
            s.Stroke = new SvgColourServer(Color.Black);
            s.MarkerStart = new Uri($"url(#{startMarker.ID})", UriKind.Relative);
            s.MarkerEnd = new Uri($"url(#{endMarker.ID})", UriKind.Relative);

            //Group to allow tranforms to be applied to line and text simultaneously
            SvgGroup g = new SvgGroup();

            //Define where text should go relative to baseline
            int textOffset = -5;
            if (offset < 0)
                textOffset = 5;
            standardText(text, length / 2, -offset + textOffset, g, true, 0);

            //Transform whole line + text group
            double midX = (startX + endX) / 2;
            double midY = (startY + endY) / 2;
            double rotation = AngleBetweenPoints(startX, startY, endX, endY);

            g.Children.Add(s);

            //Note that transformations are performed in reverse order i.e. translate, then rotate for the below
            g.Transforms = new Svg.Transforms.SvgTransformCollection()
            {
                new Svg.Transforms.SvgRotate((float)rotation, (float)startX, (float)startY),
                new Svg.Transforms.SvgTranslate((float)startX, (float)startY)
            };

            group.Children.Add(g);
        }

**Comment by mrbean-bremen** [comment]
The crash seems to happen because a start marker has no `OwnerDocument`, meaning that it does not have a (direct or indirect) parent relationship with the SvgDocument.

**Comment by mrbean-bremen** [comment]
Can it be that the definitions it is added to in `addToDefs` do not have a parent?

**Comment by H1Gdev** [comment]
@cbarker0 

I do not know `addToDefs` method, but I think that to succeed If you add `SvgDefinitionList` instance.

```cs
var def = new SvgDefinitionList();
doc.Children.Add(def);

def.Children.Add(startMarker);
def.Children.Add(endMarker);
```

**Comment by mrbean-bremen** [comment]
I guess that is what is done in `addToDefs`, maybe with adding the definition list to the document missing.

**Comment by mrbean-bremen** [comment]
@cbarker0 - did you get anywhere with your problem?

**Comment by mrbean-bremen** [comment]
Closing as stale - please reopen if this is still an issue and you have new information.
