### ISSUE TITLE
Code renders a black rectangle - should be a chart

### ISSUE THREAD

**Issue by damonwildercarr** [vvvv/SVG#499]
#### Description

Using the following code and the SVG data below I get back a black rectangle, nothing more. You can see what I get back at the end of this item:

            Bitmap bitmap = null;
            var byteArray = Encoding.ASCII.GetBytes(svgString);
            using (Stream stream = new MemoryStream(byteArray))
            {
                var svgDocument = SvgDocument.Open<SvgDocument>(stream);
                bitmap = svgDocument.Draw();
                var tempPath = Path.GetTempFileName() + ".png";
                bitmap.Save(tempPath, ImageFormat.Png);
            }

You can paste the SVG code below into a viewer site like https://www.rapidtables.com/web/tools/svg-viewer-editor.html and it works fine.

#### Example data

`<svg xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" class="highcharts-root"
                        style="font-family:ProximaNova, &quot;Helvetica Neue&quot;, sans-serif;font-size:12;letter-spacing:0.5;
                        " xmlns="http://www.w3.org/2000/svg" width="600" height="400" viewBox="0 0 600 400">
                        <desc>Created with Highcharts 7.0.3</desc><defs><clipPath id="highcharts-ly9fan1-282">
                        <rect x="0" y="0" width="520" height="354" fill="none"></rect></clipPath></defs>
                        <rect fill="#ffffff" class="highcharts-background" x="0" y="0" width="600" height="400" rx="5" ry="5"></rect>
                        <rect fill="none" class="highcharts-plot-background" x="10" y="10" width="520" height="354"></rect>
                        <g class="highcharts-grid highcharts-xaxis-grid " data-z-index="1">
                        <path fill="none" data-z-index="1" class="highcharts-grid-line" d="M 53.5 10 L 53.5 364" opacity="1"></path>
                        <path fill="none" data-z-index="1" class="highcharts-grid-line" d="M 175.5 10 L 175.5 364" opacity="1"></path>
                        <path fill="none" data-z-index="1" class="highcharts-grid-line" d="M 297.5 10 L 297.5 364" opacity="1"></path>
                        <path fill="none" data-z-index="1" class="highcharts-grid-line" d="M 416.5 10 L 416.5 364" opacity="1"></path>
                        </g><rect fill="none" class="highcharts-plot-border" data-z-index="1" x="10" y="10" width="520" height="354">
                        </rect>
                        <g class="highcharts-grid highcharts-yaxis-grid " data-z-index="1">
                        <path fill="none" stroke="#D7D8DA" stroke-width="1" data-z-index="1" class="highcharts-grid-line"
                        d="M 10 364.5 L 530 364.5" opacity="1"></path><path fill="none" stroke="#D7D8DA" stroke-width="1"
                        data-z-index="1" class="highcharts-grid-line" d="M 10 325.5 L 530 325.5" opacity="1"></path>
                        <path fill="none" stroke="#D7D8DA" stroke-width="1" data-z-index="1" class="highcharts-grid-line"
                        d="M 10 285.5 L 530 285.5" opacity="1"></path><path fill="none" stroke="#D7D8DA" stroke-width="1"
                        data-z-index="1" class="highcharts-grid-line" d="M 10 246.5 L 530 246.5" opacity="1"></path>
                        <path fill="none" stroke="#D7D8DA" stroke-width="1" data-z-index="1" class="highcharts-grid-line"
                        d="M 10 207.5 L 530 207.5" opacity="1"></path><path fill="none" stroke="#D7D8DA" stroke-width="1"
                        data-z-index="1" class="highcharts-grid-line" d="M 10 167.5 L 530 167.5" opacity="1"></path>
                        <path fill="none" stroke="#D7D8DA" stroke-width="1" data-z-index="1" class="highcharts-grid-line"
                        d="M 10 128.5 L 530 128.5" opacity="1"></path><path fill="none" stroke="#D7D8DA" stroke-width="1"
                        data-z-index="1" class="highcharts-grid-line" d="M 10 89.5 L 530 89.5" opacity="1"></path>
                        <path fill="none" stroke="#D7D8DA" stroke-width="1" data-z-index="1" class="highcharts-grid-line"
                        d="M 10 49.5 L 530 49.5" opacity="1"></path><path fill="none" stroke="#D7D8DA" stroke-width="1"
                        data-z-index="1" class="highcharts-grid-line" d="M 10 9.5 L 530 9.5" opacity="1"></path></g>
                        <g class="highcharts-axis highcharts-xaxis " data-z-index="2"><path fill="none"
                        class="highcharts-axis-line" data-z-index="7" d="M 10 364.5 L 530 364.5"></path></g><g class="highcharts-axis
                        highcharts-yaxis " data-z-index="2"><text x="574.859375" data-z-index="7" text-anchor="middle"
                        transform="translate(0,0) rotate(90 574.859375 187)" class="highcharts-axis-title"
                        style="color:#1A65B9;fill:#1A65B9;" y="187"><tspan>OAS (bp/yr)</tspan></text><path fill="none"
                        class="highcharts-axis-line" stroke="#1A65B9" stroke-width="1" data-z-index="7" d="M 530.5 10 L 530.5 364">
                        </path></g><g class="highcharts-series-group" data-z-index="3"><g data-z-index="0.1"
                        class="highcharts-series highcharts-series-0 highcharts-line-series " transform="translate(10,10) scale(1 1)"
                        clip-path="url(#highcharts-ly9fan1-282)"><path fill="none" d="M 5.0980392156863 238.32066666666668 L
                        9.0705373058314 239.89400000000006 L 10.39470333588 239.57933333333332 L 11.718869365928 242.6866666666666
                        L 13.043035395977 235.528 L 14.367201426025 247.99666666666673 L 18.33969951617 250.396 L 19.663865546218
                        249.05866666666662 L 20.988031576267 257.27933333333334 L 22.312197606315 245.0073333333333 L
                        23.636363636364
                        250.5926666666667 L 27.608861726509 237.57333333333338 L 28.933027756557 244.02399999999997 L
                        30.257193786606
                        233.56133333333332 L 31.581359816654 228.44800000000004 L 32.905525846702 216.60866666666664 L
                        36.878023936847
                        205.24133333333336 L 38.202189966896 211.14133333333336 L 39.526355996944 200.56066666666672 L
                        40.850522026993
                        187.65933333333336 L 42.174688057041 209.64666666666673 L 46.147186147186 209.4106666666667 L
                        47.471352177235
                        207.87666666666667 L 48.795518207283 208.07333333333335 L 50.119684237331 227.1893333333333 L
                        51.44385026738 217.946 L 55.416348357525 226.8353333333333 L 56.740514387573 238.24199999999996 L
                        58.064680417622 229.4706666666667 L 59.38884644767 221.84000000000003 L 60.713012477718 238.6746666666667 L
                        64.685510567864 231.43733333333336 L 66.009676597912 233.75800000000004 L 67.33384262796
                        234.19066666666663 L 68.658008658009 237.21933333333334 L 69.982174688057 233.168 L 73.954672778202
                        233.60066666666663 L 75.278838808251 247.4066666666667 L 76.603004838299 250.0026666666667 L
                        77.927170868347 255.43066666666667 L 79.251336898396 250.71066666666673 L 83.223834988541
                        255.54866666666666 L 84.548001018589 266.95533333333333 L 85.872167048638 268.0173333333333 L
                        87.196333078686 274.54666666666674 L 88.520499108734 266.79800000000006 L 92.49299719888
                        288.0773333333334 L 93.817163228928 292.5613333333333 L 95.141329258976 279.26666666666665 L
                        96.465495289025 249.13733333333334 L 97.789661319073 234.19066666666663 L 101.76215940922 224.1213333333333
                        L 103.08632543927 251.65466666666663 L 104.41049146932 252.8346666666667 L 105.73465749936 253.10999999999999
                        L 107.05882352941 252.36266666666666 L 111.03132161956 253.73933333333332 L 112.35548764961
                        261.3306666666667 L 113.67965367965 249.21600000000007 L 115.0038197097 238.5566666666667 L
                        116.32798573975 241.03466666666668 L 120.3004838299 255.70599999999996 L 121.62464985994 247.564
                        L 122.94881588999 253.26733333333328 L 124.27298192004 233.99400000000003 L 125.59714795009
                        223.6886666666667 L 129.56964604023 223.964 L 130.89381207028 233.40400000000002 L 132.21797810033
                        221.48600000000002 L 133.54214413038 243.23733333333337 L 134.86631016043 236 L 138.83880825057
                        248.39000000000004 L 140.16297428062 257.83000000000004 L 141.48714031067 259.4033333333333 L
                        142.81130634072 259.836 L 144.13547237077 280.8793333333333 L 148.10797046091 269.55133333333333
                        L 149.43213649096 279.65999999999997 L 150.75630252101 277.8113333333333 L 152.08046855106
                        302.8273333333334 L 153.40463458111 292.32533333333333 L 157.37713267125 282.256 L
                        158.7012987013 262.0386666666667 L 160.02546473135 284.4193333333333
                      L 161.3496307614 292.6793333333333 L 162.67379679144 283.082 L 166.64629488159 278.87333333333333 L
                      167.97046091164 277.8113333333333 L 169.29462694169 286.15 L 170.61879297173 276.828 L 171.94295900178
                      275.56933333333336 L 175.91545709193 271.91133333333335 L 177.23962312198 281.98066666666665 L
                      178.56378915202 273.3666666666667 L 179.88795518207 256.9253333333333 L 181.21212121212 256.532 L
                      185.18461930227 259.91466666666673 L 186.50878533231 260.38666666666666 L 187.83295136236
                      266.79800000000006 L 189.15711739241 269.04 L 190.48128342246 274.94000000000005 L 194.45378151261
                      273.48466666666667 L 195.77794754265 269.70866666666666 L 197.1021135727 278.40133333333335 L
                      198.42627960275 259.01 L 199.7504456328 254.05400000000003 L 203.72294372294 259.6786666666667 L
                      205.04710975299 250.0026666666667 L 206.37127578304 244.4566666666667 L 207.69544181309
                      254.40800000000002 L 209.01960784314 254.05400000000003 L 213.04727951787 271.1246666666667 L
                      214.37144554792 270.4953333333334 L 215.69561157796 278.40133333333335 L 217.01977760801 271.636
                      L 218.34394363806 247.4066666666667 L 222.31644172821 255.46999999999997 L 223.64060775825
                      228.09400000000005 L 224.9647737883 222.43000000000006 L 226.28893981835 195.99800000000005
                      L 227.6131058484 200.87533333333332 L 231.58560393855 180.65800000000004 L 232.90976996859
                      236.59000000000003 L 234.23393599864 239.73666666666662 L 235.55810202869 237.29800000000006
                      L 236.88226805874 238.3993333333334 L 240.85476614888 228.56600000000006 L 242.17893217893
                      235.13466666666667 L 243.50309820898 248.23266666666672 L 244.82726423903 191.98600000000002
                      L 246.15143026908 189.94066666666666 L 250.12392835922 195.56533333333334 L 251.44809438927
                      163.90199999999996 L 252.77226041932 163.15466666666663 L 254.09642644937 129.328 L 255.42059247942
                      130.78333333333333 L 259.39309056956 149.15199999999996 L 260.71725659961 159.4573333333333 L
                      262.04142262966 166.93066666666667 L 263.36558865971 174.91533333333334 L 264.68975468975
                      199.18399999999994 L 268.6622527799 166.14400000000003 L 269.98641880995 174.36466666666672
                       L 271.31058484 149.15199999999996 L 272.63475087005 139.83000000000007 L 273.95891690009
                      106.35733333333332 L 277.93141499024 92.98399999999998 L 279.25558102029 88.382 L
                      280.57974705034 90.62399999999997 L 281.90391308038 123.93933333333331 L 283.22807911043
                      79.88600000000002 L 287.20057720058 90.03399999999993 L 289.84890926067 92.66933333333338
                      L 291.17307529072 64.54599999999999 L 292.49724132077 45.430000000000064 L 296.46973941092
                      90.50599999999997 L 297.79390544096 120.8713333333333 L 299.11807147101 111.11666666666667
                      L 300.44223750106 133.26133333333334 L 301.76640353111 144.5106666666667 L 305.73890162125
                      98.37266666666665 L 307.0630676513 130.54733333333334 L 308.38723368135 139.67266666666663
                      L 309.7113997114 174.60066666666663 L 311.03556574145 200.56066666666672 L 315.00806383159
                      198.86933333333334 L 316.33222986164 203.4713333333333 L 317.65639589169 215.46800000000002
                      L 318.98056192174 209.7253333333333 L 320.30472795179 227.15 L 324.27722604193 225.69466666666665
                      L 325.60139207198 205.43799999999996 L 326.92555810203 247.9573333333333 L 328.24972413208
                      245.67600000000004 L 329.57389016213 278.5586666666666 L 333.54638825227 252.20533333333336
                      L 334.87055428232 260.62266666666665 L 336.19472031237 264.04466666666667 L 337.51888634242 227.9366666666666
                      L 338.84305237246 227.03199999999998 L 342.81555046261 225.61600000000007 L 344.13971649266
                      227.58266666666674 L 345.46388252271 252.75599999999997 L 346.78804855275 248.50800000000004
                      L 348.1122145828 237.92733333333337 L 352.08471267295 238.0846666666667 L 353.408878703
                      243.15866666666665 L 354.73304473304 230.57200000000003 L 356.05721076309 240.24800000000005 L
                      357.38137679314 238.51733333333328 L 361.35387488329 249.76666666666665 L 362.67804091334
                      254.2113333333333 L 364.00220694338 245.5186666666666 L 365.32637297343 227.85800000000003
                      L 366.65053900348 245.36133333333333 L 370.62303709363 230.69000000000003 L 371.94720312367 247.446
                      L 373.27136915372 240.56266666666664 L 374.59553518377 228.21200000000005 L 375.91970121382
                      225.26200000000006 L 379.83702571938 236.66866666666664 L 381.16119174943 227.66133333333332
                      L 382.48535777948 226.08799999999997 L 383.80952380952 209.29266666666672 L 385.13368983957
                      230.72933333333333 L 389.10618792972 231.67333333333335 L 390.43035395977 230.72933333333333
                      L 391.75451998981 245.47933333333333 L 393.07868601986 243.08000000000004 L 394.40285204991
                      203.314 L 398.37535014006 207.56200000000004 L 399.6995161701 194.464 L 401.02368220015
                      193.51999999999995 L 402.3478482302 198.71200000000005 L 403.67201426025 198.59400000000005
                      L 407.64451235039 213.38333333333335 L 408.96867838044 212.2033333333333 L 410.29284441049
                      220.18799999999996 L 411.61701044054 231.39800000000005 L 412.94117647059 232.4993333333334
                      L 416.91367456073 251.85133333333334 L 418.23784059078 258.34133333333335 L 419.56200662083
                      248.5473333333333 L 420.88617265088 264.31999999999994 L 422.21033868093 278.79466666666667
                      L 426.18283677107 282.09866666666665 L 427.50700280112 281.62666666666667 L 428.83116883117
                      277.2213333333333 L 430.15533486122 268.6466666666667 L 431.47950089127 253.10999999999999
                      L 435.45199898141 257.4366666666666 L 436.77616501146 270.8886666666667 L 438.10033104151
                      242.80466666666663 L 439.42449707156 249.60933333333338 L 440.7486631016 258.53799999999995
                      L 444.72116119175 248.036 L 446.0453272218 248.78333333333336 L 447.36949325185 174.60066666666663
                      L 448.69365928189 169.40866666666665 L 450.01782531194 181.44466666666665 L 453.99032340209
                      77.70800000000003 L 455.31448943214 158.00199999999995 L 456.63865546218 144.078 L 457.96282149223
                      144.4713333333333 L 459.28698752228 146.9886666666667 L 463.25948561243 121.69733333333335
                      L 464.58365164248 123.78200000000001 L 465.90781767252 116.46600000000007 L 467.23198370257
                      126.81066666666672 L 468.55614973262 113.16200000000006 L 472.52864782277 150.214 L 473.85281385281
                      170.11666666666667 L 475.17697988286 157.84466666666665 L 476.50114591291 140.18399999999997 L
                      477.82531194296 136.44733333333335 L 481.7978100331 135.3853333333333 L 483.12197606315
                      138.3746666666667 L 484.4461420932 155.16999999999996 L 485.77030812325 153.0853333333333
                      L 487.0944741533 152.21999999999997 L 491.06697224344 169.84133333333338 L 492.39113827349
                      176.7246666666667 L 493.71530430354 184.66999999999996 L 495.03947033359 201.78000000000006
                      L 496.36363636364 202.21266666666665 L 500.33613445378 199.6953333333334 L 501.66030048383
                      203.6286666666667 L 502.98446651388 198.79066666666665 L 504.30863254393 193.12666666666667
                      L 505.63279857398 175.58399999999995 L 509.60529666412 190.92399999999998 L 510.92946269417
                      200.4033333333333 L 512.25362872422 205.20199999999997 L 513.57779475427 214.52399999999997
                      L 514.90196078431 212.75400000000002" class="highcharts-graph" data-z-index="1" stroke="#1A65B9"
                      stroke-width="2" stroke-dasharray="none"></path></g><g data-z-index="0.1" class="highcharts-markers
                      highcharts-series-0 highcharts-line-series " transform="translate(10,10) scale(1 1)" clip-path="none">
                      </g></g><text x="40" text-anchor="start" class="highcharts-title" data-z-index="4"
                      style="color:grey;font-size:18px;fill:grey;" y="24"></text><text x="300" text-anchor="middle"
                      class="highcharts-subtitle" data-z-index="4" style="color:#666666;fill:#666666;" y="24"></text>
                      <g class="highcharts-axis-labels highcharts-xaxis-labels " data-z-index="7"><text x="54.43680502504"
                      style="color:#A9A9A9;cursor:default;font-size:11px;fill:#A9A9A9;" text-anchor="middle"
                      transform="translate(0,0)" y="383" opacity="1"><tspan>Jul '18</tspan></text><text x="298.08335455394"
                      style="color:#A9A9A9;cursor:default;font-size:11px;fill:#A9A9A9;" text-anchor="middle"
                      transform="translate(0,0)" y="383" opacity="1"><tspan>Jan '19</tspan></text><text x="176.26007978949"
                      style="color:#A9A9A9;cursor:default;font-size:11px;fill:#A9A9A9;" text-anchor="middle"
                      transform="translate(0,0)" y="383" opacity="1"><tspan>Oct '18</tspan></text><text x="417.2582972583"
                      style="color:#A9A9A9;cursor:default;font-size:11px;fill:#A9A9A9;" text-anchor="middle"
                      transform="translate(0,0)" y="383" opacity="1"><tspan>Apr '19</tspan></text></g>
                      <g class="highcharts-axis-labels highcharts-yaxis-labels " data-z-index="7"><text x="545"
                      style="color:#1A65B9;cursor:default;font-size:11px;fill:#1A65B9;" text-anchor="start"
                      transform="translate(0,0)" y="369" opacity="1">140</text><text x="545"
                      style="color:#1A65B9;cursor:default;font-size:11px;fill:#1A65B9;" text-anchor="start"
                      transform="translate(0,0)" y="329" opacity="1">150</text><text x="545"
                      style="color:#1A65B9;cursor:default;font-size:11px;fill:#1A65B9;" text-anchor="start"
                      transform="translate(0,0)" y="290" opacity="1">160</text><text x="545"
                      style="color:#1A65B9;cursor:default;font-size:11px;fill:#1A65B9;"
                      text-anchor="start" transform="translate(0,0)" y="251" opacity="1">170</text>
                      <text x="545" style="color:#1A65B9;cursor:default;font-size:11px;fill:#1A65B9;" text-anchor="start"
                      transform="translate(0,0)" y="211" opacity="1">180</text><text x="545"
                      style="color:#1A65B9;cursor:default;font-size:11px;fill:#1A65B9;" text-anchor="start"
                      transform="translate(0,0)" y="172" opacity="1">190</text><text x="545"
                      style="color:#1A65B9;cursor:default;font-size:11px;fill:#1A65B9;" text-anchor="start"
                      transform="translate(0,0)" y="133" opacity="1">200</text><text x="545"
                      style="color:#1A65B9;cursor:default;font-size:11px;fill:#1A65B9;" text-anchor="start"
                      transform="translate(0,0)" y="93" opacity="1">210</text><text x="545"
                      style="color:#1A65B9;cursor:default;font-size:11px;fill:#1A65B9;" text-anchor="start"
                      transform="translate(0,0)" y="54" opacity="1">220</text><text x="545"
                      style="color:#1A65B9;cursor:default;font-size:11px;fill:#1A65B9;" text-anchor="start"
                      transform="translate(0,0)" y="15" opacity="1">230</text></g></svg>`

`
#### Used Versions

Version 3.0.0.0 (3.0.3-gecdc54b12b pre-release Nuget release) as well as last production NuGet release 

![tmpEDAF tmp](https://user-images.githubusercontent.com/8672606/60059053-b6a8e800-969f-11e9-876c-aa41f51eb561.png)

**Comment by tebjan** [comment]
`var byteArray = Encoding.ASCII.GetBytes(svgString);` is there a particular reason for using ASCII? does it work if you use UTF8?

**Comment by damonwildercarr** [comment]
I've modified the code to load from an actual SVG file and get the same result,

`      var svgPath = Path.GetTempPath() + Guid.NewGuid() + ".svg";
       File.WriteAllText(svgPath, svgString);
       var svgDocument = SvgDocument.Open<SvgDocument>(svgPath);
`

**Comment by damonwildercarr** [comment]
When I change the SVG to the following it works great, so there must be something unsupported that is being used in the SVG above.

`<svg height="100" width="100">
  <circle cx="50" cy="50" r="40" stroke="black" stroke-width="3" fill="red" />
</svg> `

**Comment by mrbean-bremen** [comment]
Hm, this is what I get using the SVGViewer in master:
![grafik](https://user-images.githubusercontent.com/4623701/60120780-e7614e00-9781-11e9-8030-d4476042e92d.png)
This uses basically the same code:
```c#
    var byteArray = Encoding.UTF8.GetBytes(textBox1.Text);
    using (Stream stream = new MemoryStream(byteArray))
    {
        stream.Position = 0;
        var svgDocument = SvgDocument.Open<SvgDocument>(stream);
       svgImage.Image = svgDoc.Draw();
    }
```
I will also check with the pre-release version...

**Comment by mrbean-bremen** [comment]
I presume you are testing under Windows using .NET, right?

**Comment by damonwildercarr** [comment]
Correct - Windows 7 .NET 4.5.2

**Comment by mrbean-bremen** [comment]
Hm, I'm using Window 10 with the same .NET version, this should not be the issue. Are you able to clone the code locally and check if it works using the SVGViewer for you?

**Comment by damonwildercarr** [comment]
I'll check now.

**Comment by damonwildercarr** [comment]
Interesting - it works, even when I use the NuGet package version. I'll dig in from here.

![image](https://user-images.githubusercontent.com/8672606/60122586-629f1180-973a-11e9-91f7-04e5f24470ed.png)

**Comment by mrbean-bremen** [comment]
Ok, thanks - let us know if you find something!

**Comment by damonwildercarr** [comment]
I think the issue is I am doing this purely in code - the image is never getting rendered. My use case is I am converting SVG to PNG and placing it on the clipboard. More to come...

**Comment by mrbean-bremen** [comment]
Hm, it should still work, as the rendering happens in `Draw()` - I replaced the SVGViewer code with your code (e.g. only render into a bitmap and save as jpeg), and it still works for me.

**Comment by damonwildercarr** [comment]
I'm creating a WPF version of SVGViewer to see if I can reproduce.

**Comment by mrbean-bremen** [comment]
Ok, WPF... I don't have any experience there.

**Comment by damonwildercarr** [comment]
This is something specific to my project. I created a new WPF project and it worked fine. Anyway there is no issue here for you.

**Comment by mrbean-bremen** [comment]
Ok, thanks anyway for digging into it!
