### ISSUE TITLE
NullReferenceException in SvgNodeReader.ResolveEntity when opening SVG with entity definitions

### ISSUE THREAD

**Issue by danlyons-softek** [vvvv/SVG#518]
#### Description
My team uses SVG images in a handful of places within our product, and we've recently run into issues trying to use rebranded images from the marketing department.  After some troubleshooting, we tracked down the underlying issue to a NullReferenceException coming from [SvgNodeReader.ResolveEntity, Line 144](https://github.com/vvvv/SVG/blob/9b7d130a1cba516452ae5dd5b79759b0682d1150/Source/SvgNodeReader.cs#L144).

*Note: a quick-and-dirty fix is to reference `Entities` rather than `_entities`*
*Side note: it may also be preferable to use `TryGetValue` over a `ContainsKey` and indexer*

#### Example data
It looks like the issue is triggered by a bunch of garbage entities added by Adobe Illustrator.

I attached (and renamed to .txt due to GitHub's attachment filter) a minimal reproduction SVG.
[header_branding.txt](https://github.com/vvvv/SVG/files/3408608/header_branding.txt)

#### Used Versions
I originally encountered this in SVG 2.2.1.39233, then reproduced it in the latest nuget package, 2.4.3.29446, then pulled a copy of master and reproduced it there as well.

I am currently running on .NET Framework 4.7.2.

**Comment by mrbean-bremen** [comment]
Thanks for the report!
Can you say how you open and render the file? I cannot reproduce this using the SVGViewer, which basically does a `SvgDocument.Draw`, and  the reader seems to skip over the `DOCTYPE` declaration.
I can see the problem in the code if `_entities` is `null`, which is easy to fix, as you wrote (and clearly a bug), but I would like to be able to reproduce the problem first.

**Comment by danlyons-softek** [comment]
We render images with the following bit of code:

```csharp
public static Image RasterizeVectorImage(Size size, string path)
{
    var xmlDoc = GetEmbeddedDocument(path);
    var doc = SvgDocument.Open(xmlDoc);
    doc.Height = size.Height;
    doc.Width = size.Width;
    return doc.Draw();
}
```
where `GetEmbeddedDocument` pulls the SVG from the assembly's embedded resources and returns it as a `System.Xml.XmlDocument`

**Comment by mrbean-bremen** [comment]
Ok, thanks - this explains it, I can reproduce it now! 
I'll check again, but probably just fix it the way you did (somewhere later this weekend).
