### ISSUE TITLE
i am fix call FontLoaderCallback add commit

### ISSUE THREAD

**Issue by CSerX** [vvvv/SVG#528]
Never called FontLoaderCallback, i am fix it. I use this function to load self fonts.
```
Source/SvgFontManager.cs
@@ -50,10 +50,10 @@
         {
             if (name == null) return null;
             FontFamily ff = null;
-            if (SystemFonts.TryGetValue(name.ToLower(), out ff)) return ff;
+            if (SystemFonts.TryGetValue(name.ToLower(), out ff) && ff != null) return ff;
             if (FontLoaderCallback == null) return null;
             var ff2 = FontLoaderCallback(name);
-            SystemFonts.Add(name.ToLower(), ff2);
+            if (ff2 != null) SystemFonts.Add(name.ToLower(), ff2);
             return ff2;
         }
     }
```

**Comment by mrbean-bremen** [comment]
Thanks - the diff had been garbled by the formatting, so I didn't understand this first...
Though I don't understand the chane yet.
```c#
  if (SystemFonts.TryGetValue(name.ToLower(), out ff)) return ff;
```
This returns only, if  font was found - so the second check for `ff` is not needed, as far as I can see.
The second check to avoid adding a null font makes sense to me, but I still don't understand why `FontLoaderCallback` was not called in the first place.

**Comment by CSerX** [comment]
I don't know why, result is true and ff is null.
And if FontLoaderCallback return null then it can't be added to SystemFonts.

**Comment by mrbean-bremen** [comment]
Sorry for the delay!
Strange... I would really like to understand what is going on here before adding this - maybe there is a bug elsewhere. Can you check the value of `SystemFonts` before that call? Can it be that somehow there is a `null` as value in the dictionary?

**Comment by CSerX** [comment]
Sorry, i am undestend. First check not needed, second is required. Beсause FontLoaderCallback can return null, after this dictionary contains null :) (i am debug after first execution)

**Comment by mrbean-bremen** [comment]
Ok, thanks - that makes sense then! I'll add the second check in this case.
