### ISSUE TITLE
Not all properties should be inherited

### ISSUE THREAD

**Issue by wieslawsoltes** [vvvv/SVG#541]
#### Description

Not all properties should be inherited: https://www.w3.org/TR/SVG11/propidx.html

#### Example data

`SvgElementStyle.cs`

https://github.com/vvvv/SVG/blob/f21eebf029e27967587180853ae22d978502cfe1/Source/SvgElementStyle.cs#L148

https://github.com/vvvv/SVG/blob/f21eebf029e27967587180853ae22d978502cfe1/Source/SvgElementStyle.cs#L158

https://github.com/vvvv/SVG/blob/f21eebf029e27967587180853ae22d978502cfe1/Source/SvgElementStyle.cs#L188

https://github.com/vvvv/SVG/blob/f21eebf029e27967587180853ae22d978502cfe1/Source/SvgElementStyle.cs#L238

`SvgVisualElement.cs`

https://github.com/vvvv/SVG/blob/f21eebf029e27967587180853ae22d978502cfe1/Source/Basic%20Shapes/SvgVisualElement.cs#L52

https://github.com/vvvv/SVG/blob/f21eebf029e27967587180853ae22d978502cfe1/Source/Basic%20Shapes/SvgVisualElement.cs#L82

`SvgVisualElementStyle.cs`

https://github.com/vvvv/SVG/blob/f21eebf029e27967587180853ae22d978502cfe1/Source/Basic%20Shapes/SvgVisualElementStyle.cs#L26

https://github.com/vvvv/SVG/blob/f21eebf029e27967587180853ae22d978502cfe1/Source/Basic%20Shapes/SvgVisualElementStyle.cs#L42

`SvgGradientStop.cs`

https://github.com/vvvv/SVG/blob/f21eebf029e27967587180853ae22d978502cfe1/Source/Painting/SvgGradientStop.cs#L63

https://github.com/vvvv/SVG/blob/f21eebf029e27967587180853ae22d978502cfe1/Source/Painting/SvgGradientStop.cs#L73

#### Used Versions

SVG 1.1 (Second Edition) – 16 August 2011

**Comment by H1Gdev** [comment]
@wieslawsoltes 

`opacity` attribute requires ` inherit`.(`filter`, too.)

In which case is problem happening ?

**Comment by wieslawsoltes** [comment]
When using filter on `g` or `use`.

**Comment by wieslawsoltes** [comment]
Sample for `opacity`
```svg
  <g transform="translate(80, 80)"                    opacity="0.5">
    <rect x="10" y="10" width="40" height="40"/>
    <rect x="30" y="30" width="40" height="40"/>
  </g>
```

**Comment by wieslawsoltes** [comment]
Repro for `use`:
```svg
<svg width="100%" height="100%" viewBox="0 0 150 360"
    preserveAspectRatio="xMidYMid meet"
    xmlns="http://www.w3.org/2000/svg"
    xmlns:xlink="http://www.w3.org/1999/xlink">

  <!-- ref -->
  <defs>
    <g id="circles">
      <circle cx="30" cy="30" r="20" fill="blue" fill-opacity="0.5" />
      <circle cx="20" cy="50" r="20" fill="green" fill-opacity="0.5" />
      <circle cx="40" cy="50" r="20" fill="red" fill-opacity="0.5" />
    </g>
  </defs>
  <use href="#circles" />
  <text x="70" y="50">Reference</text>

  <!-- matrix -->
  <filter id="colorMeMatrix">
    <feColorMatrix in="SourceGraphic"
        type="matrix"
        values="0 0 0 0 0
                1 1 1 1 0
                0 0 0 0 0
                0 0 0 1 0" />
  </filter>
  <use href="#circles" transform="translate(0 70)" filter="url(#colorMeMatrix)" />
  <text x="70" y="120">matrix</text>

  <!-- saturate -->
  <filter id="colorMeSaturate">
    <feColorMatrix in="SourceGraphic"
        type="saturate"
        values="0.2" />
  </filter>
  <use href="#circles" transform="translate(0 140)" filter="url(#colorMeSaturate)" />
  <text x="70" y="190">saturate</text>

  <!-- hueRotate -->
  <filter id="colorMeHueRotate">
    <feColorMatrix in="SourceGraphic"
        type="hueRotate"
        values="180" />
  </filter>
  <use href="#circles" transform="translate(0 210)" filter="url(#colorMeHueRotate)" />
  <text x="70" y="260">hueRotate</text>

  <!-- luminanceToAlpha -->
  <filter id="colorMeLTA">
    <feColorMatrix in="SourceGraphic"
        type="luminanceToAlpha" />
  </filter>
  <use href="#circles" transform="translate(0 280)" filter="url(#colorMeLTA)" />
  <text x="70" y="320">luminanceToAlpha</text>
</svg>
```

**Comment by wieslawsoltes** [comment]
Looks like unless you specify explicitly `filter` or `opacity` property value to `inherit` than it should not be inherited from it's parent.
https://www.w3.org/TR/2008/REC-CSS2-20080411/cascade.html#value-def-inherit

**Comment by H1Gdev** [comment]
I know that Attribute implementations is very strange, including `inherit` behavior.
(Especially if using `<use>`.)

I have organized it in several PRs, but it is still halfway.
This issue will be fixed in the future, but please be patient.

**Comment by wieslawsoltes** [comment]
> I know that Attribute implementations is very strange, including `inherit` behavior.
> (Especially if using `<use>`.)
> 
> I have organized it in several PRs, but it is still halfway.
> This issue will be fixed in the future, but please be patient.

@H1Gdev Thank you for your effort, I can wait no problem here.

**Comment by H1Gdev** [comment]
Fixed one of inherit issues with #575.

**Comment by H1Gdev** [comment]
@wieslawsoltes

Are you solving these issues ?

**Comment by wieslawsoltes** [comment]
@H1Gdev Currently not.

**Comment by H1Gdev** [comment]
@mrbean-bremen 
@wieslawsoltes 

Please close this issue.
