### ISSUE TITLE
Error Converting SVG

### ISSUE THREAD

**Issue by ksoftinformatik** [vvvv/SVG#554]
I have an svg-Tag, that was created by the C3-Chart-library and produces a rendering error. The reason: 
In SvgVisualElements.cs on line 159 the Bitmap-Constructor is called with Bounds(0, 0);
When i make an 
if ((Bounds.Width > 0) && (Bounds.Height > 0))
{
...
}
around that code, the rendering works and the result ist correct.

[test.zip](https://github.com/vvvv/SVG/files/3491412/test.zip)

**Comment by H1Gdev** [comment]
This SVG file contains the following:
```svg
<text class="c3-text c3-empty" text-anchor="middle" dominant-baseline="middle" x="199" y="89" style="opacity: 0;" />
```
- text: none
- opacity: 0

**Comment by ksoftinformatik** [comment]
I know, but this is allowed. The svg is created by the c3 chart lib and all browsers show it correct.

**Comment by H1Gdev** [comment]
@ksoftinformatik 

Sorry.I didn't explain it enough.
I don't want you to modify SVG file.
Added the cause of this issue.

**Comment by H1Gdev** [comment]
@mrbean-bremen 

I think need to check length of text somewhere(SvgTextBase ??).
like SvgRectangle.
https://github.com/vvvv/SVG/blob/d1cd781a66abfd2812c66539b23463b03c9fd339/Source/Basic%20Shapes/SvgRectangle.cs#L221.

**Comment by ksoftinformatik** [comment]
I explained a possible solution in SvgVisualElements.Render(...) already:

```
        private void Render(ISvgRenderer renderer, bool renderFilter)
        {
            if (Visible && Displayable && (!Renderable || Path(renderer) != null))
            {
                if (!(renderFilter && RenderFilter(renderer)))
                {
                    try
                    {
                        if (PushTransforms(renderer))
                        {
                            SetClip(renderer);

                            if (Renderable)
                            {
                                var opacity = Math.Min(Math.Max(Opacity, 0f), 1f);
                                if (opacity == 1f)
                                    RenderFillAndStroke(renderer);
                                else
                                {
                                    IsPathDirty = true;
                                    var bounds = Bounds;
                                    IsPathDirty = true;

if ((Bounds.Width > 0) && (Bounds.Height > 0))
{
                                    using (var canvas = new Bitmap((int)Math.Ceiling(bounds.Width), (int)Math.Ceiling(bounds.Height)))
                                    {
                                        using (var canvasRenderer = SvgRenderer.FromImage(canvas))
                                        {
                                            canvasRenderer.SetBoundable(renderer.GetBoundable());
                                            canvasRenderer.TranslateTransform(-bounds.X, -bounds.Y);

                                            RenderFillAndStroke(canvasRenderer);
                                        }
                                        var srcRect = new RectangleF(0f, 0f, bounds.Width, bounds.Height);
                                        renderer.DrawImage(canvas, bounds, srcRect, GraphicsUnit.Pixel, opacity);
                                    }
}
                                }
                            }
                            else
                                RenderChildren(renderer);

                            ResetClip(renderer);
                        }
                    }
                    finally
                    {
                        PopTransforms(renderer);
                    }
                }
            }
        }

```

This solution works for my problem.
Another solution is to remove empty text-Tags before rendering.

**Comment by mrbean-bremen** [comment]
@ksoftinformatik - thanks, your solution looks good to me. Will you make a PR, or shall we add the change ourselves?

**Comment by H1Gdev** [comment]
@ksoftinformatik 
@mrbean-bremen 

If you do this check, I think you should change the location.
For example:
```cs
            if (Visible && Displayable && (!Renderable || Path(renderer) != null))
            {
                    // here...
```

and use `bounds` variable.

**Comment by ksoftinformatik** [comment]
You can make the changes yourselves. Thank you.

**Comment by mrbean-bremen** [comment]
> If you do this check, I think you should change the location.

Agreed.

> You can make the changes yourselves.

Ok, I'll commit it then.

**Comment by H1Gdev** [comment]
@mrbean-bremen 

617f75eac96b79857e7515a80f98dab5d0b09eb6 prevents the test from passing.
It seems that you need to revert and review it.
I think that this is because handling of `GraphicsPath` of each `SvgElement` is different.

**Comment by mrbean-bremen** [comment]
Argh - thanks! I don't have the time to check this (will not have much time in the next weeks generally), but I'll revert and reopen the issue.
