### ISSUE TITLE
Drawing svg to bitmap shows up empty on Win Forms Devexpress.PictureEdit in SVG 3

### ISSUE THREAD

**Issue by fkorak** [vvvv/SVG#578]
Hello,

I'm currently loading in several SVG-Files, which I am adding to Devexpress.PictureEdits (just a display for a picture in WinForms).
 
    SvgDocument SvgLogo1 = SvgDocument.Open($@{AppDomain.CurrentDomain.BaseDirectory}\Test1.svg");       
    SvgDocument SvgLogo2 = SvgDocument.Open($@{AppDomain.CurrentDomain.BaseDirectory}\Test2.svg");

    pictureEditLogo1.Image = SvgLogo1.Draw();
    pictureEditLogo2.Image = SvgLogo2.Draw();

This works up to Nuget 2.4.3. Using 3.0.49 nothing gets drawn. There are no compiler warnings and debugging doesn't show me anything helpful.

I'm using .Net 4.6.2 set to Any CPU, Devexpress 19.1 .

Thank you for your help!

**Comment by fkorak** [comment]
Sure:

[SVG_logo.zip](https://github.com/vvvv/SVG/files/3635958/SVG_logo.zip)

As far as I can tell our marketing created this file using Illustrator. If necessary I could share details about used versions and stuff.

**Comment by mrbean-bremen** [comment]
Ok, this is a regression, but not really a bug, due to the incorrect mime extension used in the image (`img/png` instead of `image/png`). As this seems to be written sometimes, we shall fix this anyway.
