### ISSUE TITLE
SvgTextBase.GetXML does not include position collection attributes

### ISSUE THREAD

**Issue by natebarnett** [vvvv/SVG#591]
This may be the expected behavior, if so I already have an override on my side to make it work the way I want.

SvgText element = new SvgText();
element.Text = "Test";
element.X.Add(20);
element.GetXML();

I would expect:
`<text x="20">Test</text>`

What I get:
`<text>Test</text>`

I'd be happy to have someone tell me a better way of doing text element positioning or I'd be happy to fix the issue.

**Comment by mrbean-bremen** [comment]
As far as I can see, this is not expected. What would work in your case is:
```c#
  SvgText text = new SvgText();
  text.Text = "Test";
  text.X = new SvgUnitCollection() { 20 };
```
but I think your case should also work. I fix would be much appreciated!
