### ISSUE TITLE
Converting from SVG to PNG doesn't include embedded image

### ISSUE THREAD

**Issue by kkozler** [vvvv/SVG#592]
When an SVG with an embedded image is converted to a PNG, the PNG doesn't display the embedded image.

SVG image:
[svg-with-image.zip](https://github.com/vvvv/SVG/files/3735732/Laydown-Map_10-14-2019.zip)

PNG image:
![png-without-image](https://user-images.githubusercontent.com/56650703/66944683-ab494600-f01b-11e9-89c0-d1993a567e6f.png)

Versions:
SVG version: 2.4.3 (I tried with the latest version as well)
.NET Framework: 4.3.3

**Comment by mrbean-bremen** [comment]
Looks like this is not supported - @H1Gdev, can you have a look? You fixed some issues with referenced images.

**Comment by H1Gdev** [comment]
@kkozler 
@mrbean-bremen 

Looks like SVG file is missing.

```svg
<image x="0" y="0" width="726.8" height="362.85" xlink:href="../../img/Seaspan-Map.svg" xml:space="default" />
```

**Comment by mrbean-bremen** [comment]
Yeah, I noticed that, but I don't think the concrete image is important - I just provided my own image and made sure that it shows up in the browser. It didn't work for me anyway.

**Comment by H1Gdev** [comment]
Position is not correct...
It seems that `transform` is not done correctly.

I will analyze this issue.
