### ISSUE TITLE
Drop support for .NET 3.5

### ISSUE THREAD

**Issue by mrbean-bremen** [vvvv/SVG#597]
Support for 3.5 is cumbersome, and I don't think it is really needed for the next version.
While Microsoft supports 3.5 until 2024 (with extended support until 2028), as has been pointed out before, every supported Windows OS is shipped with a newer version, so the support is meant for legacy applications only. 
The next supported version is 4.5.2, which would be the minimum version of .NET we would support (also the version which would ExCSS_Core support, if we add a respective PR).

I think we don't have to support 3.5 in the next release of SVG.NET, but maybe I'm overlooking something. What do you think?

Ping @HockeyJustin for opinion.

**Comment by tebjan** [comment]
ok, let's release one nuget with latest state and then merge this and increase the version number.

**Comment by mrbean-bremen** [comment]
Well, there's the Netstandard support which is not complete (e.g. the usage of some classes that are not in the standard) - I didn't look into this lately. If this is a problem, we could take that target out for the release. 
The other thing that is the warnings we currently get from the Fizzler library, as that one is build again Netstandard 1.0 and 2.0, which is not fully compatible with .Net 4.5.2 (though not a real problem in our case, just not nice to get the warnings). I was under the impression that someone is looking into this, but I'm not sure (@gvheertum, @wieslawsoltes ?). 
So probably not ready for release yet...

**Comment by H1Gdev** [comment]
@mrbean-bremen 

> The other thing is the warnings we currently get from the Fizzler library, as that one is build against Netstandard 1.0 and 2.0, which is not fully compatible with .Net 4.5.2 (though not a real problem in our case, just not nice to get the warnings).

I created this PR #567. 
So would you like me to upgrade it ?

**Comment by tebjan** [comment]
great. so let me know which build i should release.

**Comment by mrbean-bremen** [comment]
> I created this PR #567.
> So would you like me to update Fizzler from 1.1.0 to 1.2.0 ?

This would make sense after this one is merged, as it also removed 3.5 support - though that would not get rid of the warnings. I have thought about adding .NET support back to Fizzler to fix this, but I'm not sure what we can do with the warnings meanwhile. I will be traveling for a week now, so I won't have access to a computer - but maybe someone else can have a look.
As I said, these are just warnings, but not nice in a released version...

> @mrbean-bremen we can also try the auto-publish for a release branch. i think this only requires some update of the appveyor script.

Sure, that sounds great!
As for the release time - @H1Gdev is ongoing with bug fixes, maybe he wants to add some more PRs first.

**Comment by mrbean-bremen** [comment]
> So would you like me to update Fizzler from 1.1.0 to 1.2.0 ?

@H1Gdev: I made a mistake while testing this, sorry. This is indeed the way to fix the warning (Netstandard 1.0 is supported by .NET 3.5.2). The only problem is that we cannot do this for the current release due to missing 3.5 support. 

So we have 2 options:
- leave the warning in the released version
- temporary revert the change that moved out Fizzler before the release

@tebjan - what do you think? 
@H1Gdev - provided we have decided that, is there anything else you want to see in the release?
