### ISSUE TITLE
3.0.49 breaking change: Visibility of SvgImage.GetImage(uriString:string)

### ISSUE THREAD

**Issue by dittodhole** [vvvv/SVG#602]
I've introduced following changes in 5727f42e3bc04432b119bba092de37fe39e82c50:

- Added `SvgImage.GetImage()`
- Made `SvgImage.GetImage(string uriString)` public

This was changed with 15ba214250771e45c70dc133d23b885c91ec077f.

What are the reasons for this breaking change?
Any chance for a (partial) revert?

**Comment by mrbean-bremen** [comment]
I just checked - this has been a refactoring, and we just overlooked the breaking change, as far as I can see.
@H1Gdev - can you comment on that? I think we have to add back the old API, or at least provide an equivalent alternative.

**Comment by H1Gdev** [comment]
@dittodhole 
@mrbean-bremen 

Sorry.
I misleaded.
I will revert old API soon.

I have just one question.
Why this method become public ?
`public object GetImage(string uriString)`

**Comment by H1Gdev** [comment]
@dittodhole

I do not know need to be in public method that takes an arbitrary string as an argument.

This issue has been closed, but please response my question.

**Comment by dittodhole** [comment]
@H1Gdev the reason behind is, that one of my contrib projects (https://github.com/dittodhole/dotnet-Svg.Contrib.Render) needs to have access to the underlaying `Image`. Making the `string uriString` overload public is imho an overkill for my scenario, but could be used to place the extraction logic in a static, reusable method.

Best
Andreas

**Comment by H1Gdev** [comment]
@dittodhole 

Thanks for your response.
I understand the background.

> Making the string uriString overload public is imho an overkill for my scenario, but could be used to place the extraction logic in a static, reusable method.

This usage is tricky...
I think that it is necessary to consider in the future.
