### ISSUE TITLE
Some observations I made

### ISSUE THREAD

**Issue by Injac** [vvvv/SVG#61]
First of all, thanks for all the improvements :)
1. When I have multiple layers within an SVG created with Inkscape, the text layers are not rendered when using svgDoc.Draw() (Talking about text within a layer). I have to add this text manually, adding new SVG-Documents. If I have just one layer and within that layer a rectangle for example, it works.
2. If I try to assign base64 encoded images to an SvgImage.Href, that is not possible, because the Uri class does accept URI's only to a specific length. If there is any other way to accomplish that, please let me know. (I thought about to read the xml of the svg and replace the content manually)

**Comment by mrbean-bremen** [comment]
@Injac - This is quite old, do you know if this is still an issue?
If yes, could you provide any failing example data?
(cleaning up old issues)

**Comment by mrbean-bremen** [comment]
Closing this now. Please reopen if there is still an issue.
