### ISSUE TITLE
Require Fizzler 1.2.0 for .NETStandard and .NETCoreApp targets in nuget package

### ISSUE THREAD

**Issue by 0x084E** [vvvv/SVG#612]
Since Fizzler 1.1.0 has no .NETStandard or .NETCoreApp target you get a compile time warning if you don't reference Fizzler 1.2.0 explicitly

```
warning NU1701: Package 'Fizzler 1.1.0' was restore
d using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=
v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,
Version=v3.0'. This package may not be fully compatible with your project.
```

**Comment by mrbean-bremen** [comment]
This is a known issue (documented in the release notes) and should be fixed in master.

**Comment by 0x084E** [comment]
Sorry for not reading the release notes! I only searched the releases page for it...
Closed.

**Comment by mrbean-bremen** [comment]
The release notes on the nuget site are a bit difficult to read due to formatting issues... so no wonder you didn't see it.
