### ISSUE TITLE
Fizzler 1.2.0 (Package 'Fizzler 1.1.0' was restored using '.NETFramework')

### ISSUE THREAD

**Issue by MauricioArroyo** [vvvv/SVG#623]
Hi,

Any chance to update the package with the Fizzler using .net standard?

Thanks!!

**Comment by mrbean-bremen** [comment]
This is already done in master and will be in the next release (though I don't know about the release date...)

**Comment by MauricioArroyo** [comment]
Thanks mrbean. I guess I would wait, hopefully it will happen soon.
