### ISSUE TITLE
docs wrong: http://vvvv.github.io/SVG/doc/Q&A.html#how-to-render-an-svg-document-to-a-bitmap-in-another-size wrong

### ISSUE THREAD

**Issue by GeneThomas** [vvvv/SVG#633]
http://vvvv.github.io/SVG/doc/Q&A.html#how-to-render-an-svg-document-to-a-bitmap-in-another-size

claims to render the .svg as a given size but the method provided `SvgDocument.Draw(int rasterWidth, int rasterHeight).` just renders the SVG insde that size, i.e. cropping or padding. If you want to scale the image to fit one needs to:

```Bitmap Resize(SvgDocument svg, Size origSize, Size size) {
    svg.Transforms = new SvgTransformCollection();
    svg.Transforms.Add(new Svg.Transforms.SvgScale(size.Width / (float)origSize.Width, size.Height / (float)origSize.Height));

    svg.X = 0;
    svg.Width = size.Width;
    svg.Y = 0;
    svg.Height = size.Height;

    return svg.Draw();
}

#### Used Versions

3.0.84

**Comment by GeneThomas** [comment]
my mistake

**Comment by mrbean-bremen** [comment]
good to know someone is actually reading the docs 😛
