### ISSUE TITLE
Parameter is not valid

### ISSUE THREAD

**Issue by silv2015** [vvvv/SVG#664]
I want to transform a SVG coming from MatJax library in javascript.

I'm using Asp.Net and I have my controller that receives the SVG.

But when I call ..Draw(), I get an error 'Parameter is not valid'

[test.svg.txt](https://github.com/vvvv/SVG/files/4168015/test.svg.txt)

I'm using the latest version on NuGet.

Basically, I just want a PNG image from my SVG... here is acopy of my code:

`                var svgDoc = SvgDocument.FromSvg<SvgDocument>(equation.Svg);

                var image = svgDoc.Draw();

                using (MemoryStream m = new MemoryStream())
                {
                    image.Save(m, image.RawFormat);
                    byte[] imageBytes = m.ToArray();

                    equation.Png = Convert.ToBase64String(imageBytes);
                }
`

Am I missing something? 

Thanks!

**Comment by H1Gdev** [comment]
This is SVG library issue.

Image will be created by removing empty `d` attribute \<path\> as shown below.
```svg
<path id="MJX-1-TEX-N-20" d=""></path>
```

```svg
<path id="MJX-1-TEX-N-A0" d=""></path>
```

This issue will be fixed in next version.

**Comment by silv2015** [comment]
@H1Gdev Thanks for the quick reply!

I will do what you propose and remove all empty d attribute in my SVG.

I'll let you know...
