### ISSUE TITLE
Text doesn't render at all.

### ISSUE THREAD

**Issue by cmoya212b** [vvvv/SVG#674]
Neither text nor textflow elements are rendered. The latter renders as a blackbox. 

[drawing-3.txt](https://github.com/vvvv/SVG/files/4208302/drawing-3.txt)

**Comment by mrbean-bremen** [comment]
Seems to be a problem with the viewBox in combination with the width/height in mm - the rendering is done outside the viewbox.

**Comment by H1Gdev** [comment]
As far as I was confirmed, it seems to be rendered correctly.

```svg
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
   xmlns:dc="http://purl.org/dc/elements/1.1/"
   xmlns:cc="http://creativecommons.org/ns#"
   xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
   xmlns:svg="http://www.w3.org/2000/svg"
   xmlns="http://www.w3.org/2000/svg"
   id="svg8"
   version="1.1"
   viewBox="0 0 210 297"
   height="297mm"
   width="210mm">
  <defs
     id="defs2" />
  <metadata
     id="metadata5">
    <rdf:RDF>
      <cc:Work
         rdf:about="">
        <dc:format>image/svg+xml</dc:format>
        <dc:type
           rdf:resource="http://purl.org/dc/dcmitype/StillImage" />
        <dc:title></dc:title>
      </cc:Work>
    </rdf:RDF>
  </metadata>
  <!-- add for check. -->
  <rect x="0mm" y="0mm" width="210mm" height="297mm" fill="lightgray" />
  <g
     id="layer1">
    <text
       id="text4536"
       y="27.301525"
       x="19.886719"
       style="font-style:normal;font-weight:normal;font-size:10.58333302px;line-height:1.25;font-family:sans-serif;letter-spacing:0px;word-spacing:0px;fill:#000000;fill-opacity:1;stroke:none"
       xml:space="preserve"><tspan
         y="27.301525"
         x="19.886719"
         id="tspan4534">Why does this text not render?</tspan></text>
  </g>
</svg>
```

![drawing-3 background](https://user-images.githubusercontent.com/11144112/75207758-00147e80-57bd-11ea-9176-4be725e60390.png)

**Comment by H1Gdev** [comment]
@cmoya212b 

Please tell me issue occurs runtime of details(environment).

**Comment by cmoya212b** [comment]
@H1Gdev Sorry I posted the wrong file... that I got working by manually replacing flowPara with text element. Here is the Inkscape generated one that does not work.

[drawing-4.txt](https://github.com/vvvv/SVG/files/4247765/drawing-4.txt)
(Note this was saved as "Plain SVG" not Inkscape SVG)

**Comment by cmoya212b** [comment]
I suppose this isnt exactly a bug since many utilities don't even support flowRoot/flowText etc.

**Comment by H1Gdev** [comment]
> I suppose this isnt exactly a bug since many utilities don't even support flowRoot/flowText etc.

This library does not support `flowed text`.

Use SVG text as described [here](https://wiki.inkscape.org/wiki/index.php?title=Frequently_asked_questions#What_about_flowed_text.3F).

**Comment by cmoya212b** [comment]
Thank you @H1Gdev for working this through and pointing out the docs.
