### ISSUE TITLE
Support for <animate

### ISSUE THREAD

**Issue by asdf23** [vvvv/SVG#695]
#### Description
<animate is recognized as a SvgUnknownElement object

#### Example data
`<svg version="1.1" viewBox="0 0 210 297" xmlns="http://www.w3.org/2000/svg">
	
	<g>
		<rect x="37" y="74" width="87" height="67" style="fill:black;opacity:1;paint-order:markers fill stroke;stroke-linecap:round;stroke-linejoin:round;stroke-width:0;stroke:#000">
			<animate
				attributeName="width" 
				from="87" 
				to="200" 
				begin="0s"
				dur="5s" 
				repeatCount="indefinite"
			/>
		</rect>
	
	</g>
</svg>`

#### Used Versions
.Net 3.0.102

**Comment by H1Gdev** [comment]
\<animate\> is not supported.

However, I think that we can get information even `SvgUnknownElement`.
(use `CustomAttributes`, `Content`, ...)

What do you expect ?

**Comment by asdf23** [comment]
What I was planning to use this tool for was to parse multiple similar SVG documents and then add an animation to transition between them.  To do this I wanted to programmatically add elements.. I need a SetAttribute feature to get this working. Unfortunately don't think this tool will fit my particular needs. Thanks!
