### ISSUE TITLE
Compile constant `Net4` missing

### ISSUE THREAD

**Issue by oerpli** [vvvv/SVG#696]
There's the `RegisterEvents` method which is only compiled if the target is Net4 ([see here](https://github.com/vvvv/SVG/blob/d7a767942de86a0263941dd3e7cd4f939709f036/Source/SvgElement.cs#L1066)) but the compile constant is not set ([see here](https://github.com/vvvv/SVG/blob/master/Source/Svg.csproj#L56)).

A few other methods are also affected: [Link](https://github.com/vvvv/SVG/search?q=net4&unscoped_q=net4)

Should I open a PR that adds the compile constant to the `.csproj`?

**Comment by mrbean-bremen** [comment]
> Should I open a PR that adds the compile constant to the .csproj?

Sure, go ahead! Thanks!
