### ISSUE TITLE
.Draw() is not based on actual value of SVG objects 

### ISSUE THREAD

**Issue by asdf23** [vvvv/SVG#703]
.Draw() is not based on actual value of SVG objects but rather the original file.

#### Description
The following code opens an SVG file change a node in memory and then renders it to a PNG. The object gives no indication that this is impossible (readonly properties). The resulting file is the original file without the modifications.

C#:
			FileInfo fi1 = new FileInfo(@"SomeFile.svg");
			string path = @"c:\temp\someImage.png";
			Svg.SvgDocument svgDoc1 = Svg.SvgDocument.Open(fi1.FullName);
			svgDoc1.ShapeRendering = Svg.SvgShapeRendering.Auto;
			Svg.SvgTextSpan tSpan = svgDoc1.GetElementById<Svg.SvgTextSpan>("tspanIssueCount");
			tSpan.Content = "5 Issues";
			Bitmap bmp = svgDoc1.Draw(72, 72);
			bmp.Save(path, ImageFormat.Png);
SVG:
<svg width="72" height="72" version="1.1" viewBox="0 0 19 19" xmlns="http://www.w3.org/2000/svg">
	<text x="1.8066406" y="16.99362" style="fill:#000000;font-family:sans-serif;font-size:11px;letter-spacing:0px;line-height:1.25;stroke-width:0;word-spacing:0px" xml:space="preserve"><tspan x="1.8066406" y="16.99362" style="stroke-width:0"><tspan id="tspanIssueCount" x="1.8066406" y="16.99362" style="fill:#ffffff;font-size:4px;stroke-width:0">3 issues</tspan></tspan></text>
</svg>

#### Used Versions
Latest released version

**Comment by H1Gdev** [comment]
use `Text` property.

**Comment by asdf23** [comment]
Yes I see that works, thank you
