### ISSUE TITLE
Problems with entities/styles

### ISSUE THREAD

**Issue by ChristinaFaur** [vvvv/SVG#707]
Hallo,

I have a problem with styles, for texts and rectangles, which are defined as entities in documenttype.
How can I get the refenced name of a style from a svgelement (text, rectangle).

I get for this text the attributes without style.

![EntitiesStyles](https://user-images.githubusercontent.com/63300027/78676450-bd2ee600-78e6-11ea-9e31-a561113d3a94.png)

**Comment by H1Gdev** [comment]
Can you paste SVG text ?

**Comment by ChristinaFaur** [comment]
Hello, here  the needed files.

![V20000000](https://user-images.githubusercontent.com/63300027/78750937-8baf2c80-7971-11ea-92fc-00c7748f8316.PNG)

[V20000000.txt](https://github.com/vvvv/SVG/files/4448557/V20000000.txt)

**Comment by ChristinaFaur** [comment]
Hi, do you see any chance to solve my problem?

**Comment by H1Gdev** [comment]
I have no time to check yet.
This SVG does not be displayed correctly in major browsers.

**Comment by ChristinaFaur** [comment]
Thanks for your answer.

Which browser do you mean? Our clients seem not have a problem with such svg's.
I have to evaluate svg.net for our purpose and it is the only problem I have found.

**Comment by H1Gdev** [comment]
> Which browser do you mean? 

I checked Chrome and Firefox.

**Comment by ChristinaFaur** [comment]
ok, sorry. I'm not a web programmer. we have our own browser control.

**Comment by H1Gdev** [comment]
> This SVG does not be displayed correctly in major browsers.

This problem is due to missing image in \<image\>.

```svg
<image transform="matrix(2.08085 -0 0 2.08085 0.176179 -0.176179)" style="&st3;" width="400.135" height="283.125" id="V20000000" xlink:href="V20000000.PNG"/>
```

**Comment by H1Gdev** [comment]
As far as I was checked `style` appears to have been applied correctly.

I changed `fill` color to make it easier to understand.
```svg
<!ENTITY st1 "fill:red;stroke:#ffffff;stroke-width:0;">
<!ENTITY st2 "fill:blue;stroke:#000000;stroke-width:0;">
```
These styles has been applied.

**Comment by ChristinaFaur** [comment]
thanks for your answer.
I have figured out that styles aren't applied when SvgDocument.Open ist called with parameter XmlDocument. If I call this method with filePath it seems to work.

**Comment by H1Gdev** [comment]
I will fix this issue.
