### ISSUE TITLE
data-uri schemes do not support SVG data-uris

### ISSUE THREAD

**Issue by rwdalpe** [vvvv/SVG#71]
Commit https://github.com/planetclegg/SVG/commit/6f53360e477d3b9b72f09e2b862ca1baedf29520 added basic support for data-uri schemes for the image tag. It is also possible for an SVG to be embedded via data-uri as well.

For example, shown both encoded and not encoded (obviously only the encoded version would be valid)

```
xlink:href='data:image/svg+xml;charset=utf-8,&lt;?xml version='1.0' encoding='UTF-8' ?&gt;&lt;svg ...

xlink:href='data:image/svg+xml;charset=utf-8,<?xml version='1.0' encoding='UTF-8' ?><svg ...
```

This should be functionally the same as specifying a path to an SVG document containing that content.

**Comment by mrbean-bremen** [comment]
@rwdalpe - this is quite old, did you end up adding that support?

**Comment by rwdalpe** [comment]
Unfortunately we wound up not having time to implement this. Sorry for
leaving this thread hanging for so long.

**Comment by mrbean-bremen** [comment]
Thanks - just cleaning up old issues. I haven't really looked into this one, so I leave it open for now.

**Comment by H1Gdev** [comment]
Unescaped **<**, **>**, etc. not allowed in attributes values.

Error on Firefox, Chrome, Edge.
