### ISSUE TITLE
element.RenderElement() example?

### ISSUE THREAD

**Issue by foxmichaels** [vvvv/SVG#712]
Per Issue #403, it says to use this RenderElement() function. Is there an example of that function's usage anywhere?

**Comment by burak1000** [comment]
You can render specific element with this.

            Bitmap mbmp = new Bitmap(1000, 1000);    
            ISvgRenderer mrenderer = SvgRenderer.FromImage(mbmp);
            retval.RenderElement(mrenderer);   //render image  in your bitmap

**Comment by mrbean-bremen** [comment]
Closing as answered.

**Comment by Cohote** [comment]
@mrbean-bremen  - Thank you! Not sure why, but I never got a notification when you answered back earlier this year.

Much appreciated!

**Comment by mrbean-bremen** [comment]
The thanks goes to @burak1000 - he answered the question :)
