### ISSUE TITLE
SvgVisualElement.Bounds always returning "0"

### ISSUE THREAD

**Issue by foxmichaels** [vvvv/SVG#714]
#### Description
Trying to get the Bounds for a "SvgTextBase" in v2.4.1 and before would return valid data. Starting with v2.4.2 (and up to and including v3.0.102), Bounds always seems to return "0" for everything. (Height, Width, X, and Y.)

If this is expected, that's fine, but would be curious then how to get sizes of Elements before rendering.

#### Example data
````
internal static RectangleF CompileObject(SvgVisualElement obj) {
		SvgDocument doc = new SvgDocument();
		doc.ID = "test";
		doc.Overflow = SvgOverflow.Visible;
		doc.Ppi = Vars.SIZE_DPI;
		doc.ViewBox = new SvgViewBox(0, 0, 5, 5);
		doc.Width = new SvgUnit(SvgUnitType.User, 5);
		doc.Height = new SvgUnit(SvgUnitType.User, 5);
		doc.Children.Add(obj);

		//And get the bounds.
		RectangleF retValue = obj.Bounds;

		return retValue;
}
````
In v2.4.1, The above code, when `SvgVisualElement` being a `SvgText` object, will return proper H and W, X and Y values. (Latter is unimportant here, as it's relative to the temporary document breated above.) The object needs to be added to the Document before these values are populated.

in v2.4.2 (and above, including v3.0.102), the same above code will always return Bounds of Height=0, and Width=0. 

#### Used Versions
v2.4.1, v2.4.2+, .NET 4.8.

**Comment by H1Gdev** [comment]
@foxmichaels 

As far as I checked, I can get `Width` and `Height` values other than 0.

Please tell me test code that can be reproduced.

**Comment by foxmichaels** [comment]
Sorry for the delay. Through together a solution that reproduces the issue. If I did something wrong (entirely possible), let me know. It threw me because of different results between v2.4.1 and v2.4.2+.
[ClassLibrary1.zip](https://github.com/vvvv/SVG/files/4548415/ClassLibrary1.zip)

**Comment by H1Gdev** [comment]
This difference is due to #414.
(I think you have too many changes to understand...)

If you make the following changes, you will get expected behavior.

- before
```cs
tspan.Nodes.Add(new SvgContentNode { Content = "LINE TEXT" });
```
- after
```cs
tspan.Text = "LINE TEXT";
```

**Comment by foxmichaels** [comment]
Okay - yup. Getting rid of the `SvgContentNode` usage fixed that. Fantastic to know. I started this project back on v2.0, and never needed to touch it until recently. A LOT of thing changes since then. 

> (I think you have too many changes to understand...)

If you see anyhting else that looks *wrong* please let me know. Otherwise, good - it works as expected.
