### ISSUE TITLE
how to convert SVG to Image containing arabic text?

### ISSUE THREAD

**Issue by MuhamedRa2fat** [vvvv/SVG#718]
#### Description
I have an SVG file containing arabic text in it and want to convert this file to jpg or png image, i tried to use those lines of codes :
            var svgDoc = SvgDocument.Open<SvgDocument>(SVGPATH, null);
            Bitmap bitmap = svgDoc.Draw();
            bitmap.Save(PATH, ImageFormat.Jpeg);
 but the generated image make the arabic word each letter is splitted from each other.
 
#### Example data
![101](https://user-images.githubusercontent.com/28951671/79978853-e0d65c80-84a0-11ea-9700-d2e841729a52.jpg)
"محمد" word appear into the jpg image exported like this " م ح م د"

#### Used Versions
latest version

**Comment by mrbean-bremen** [comment]
Can you please add the SVG itself? Also, by latest version you mean the version from NuGet, or the current master?
