### ISSUE TITLE
Could i add PNG image into my SVG file ?

### ISSUE THREAD

**Issue by MuhamedRa2fat** [vvvv/SVG#719]
#### Description
I facing a problem that i want to insert an jpg/png image into the SVG file and then generate it to JPG, i made the second part which convert svg file to jpg but i don't know how to inject my jpg image into the SVG.
Is there any solution for this ?

#### Example data
i have -> image.jpg &
               svgFile.svg
i need -> jpg image containing image.jpg into svgFile.svg

**Comment by zamoldar** [comment]
you can embed the image to svg file, with  base64 text value:

```
 string base64String = Convert.ToBase64String(item.ImageData);

                        SvgImage svgImage = new SvgImage() { X = (float)item.Left, Y = (float)item.Top, Width = (float)item.Width, Height = (float)item.Height, Href = $"data:image/bmp;base64,{base64String}",AspectRatio=new SvgAspectRatio(SvgPreserveAspectRatio.none), Opacity = (float)item.Opacity };
                        svgdocument.Children.Add(svgImage);
```

**Comment by MuhamedRa2fat** [comment]
@zamoldar It works great, thank you
