### ISSUE TITLE
fill-style is not applied correctly on exported bitmap

### ISSUE THREAD

**Issue by niempi2** [vvvv/SVG#731]
#### Description
When a fill style is applied to svg element programmatically and the document is exported  to bitmap the fill style is not applied correctly.

#### Example data
[Program.cs.txt](https://github.com/vvvv/SVG/files/4667475/Program.cs.txt)

#### Used Versions
.NET Framework 4.7.2 
Svg 3.1.1

**Comment by H1Gdev** [comment]
There are two ways to solve this issue.

1. Call `FlushStyles` method
```cs
            SvgDocument doc = new SvgDocument();
            var element = new SvgRectangle() { Width = 100, Height = 100 };
            element.AddStyle("fill", "red",0);
            doc.Children.Add(element);
            doc.FlushStyles(true);    // Add this !!
```
2. Use Fill property
```cs
            SvgDocument doc = new SvgDocument();
            var element = new SvgRectangle() { Width = 100, Height = 100 };
            // Change to this.
            element.Fill = new SvgColourServer(System.Drawing.Color.Red);
            doc.Children.Add(element);
```

**Comment by niempi2** [comment]
Calling FlushStyles solves this.
