### ISSUE TITLE
Directory Samples/RuntimeUpdates should be Samples/SvgSample

### ISSUE THREAD

**Issue by Psycho7** [vvvv/SVG#773]
#### Description

Just as the title suggests. I believe the folder name does not make much sense.

**Comment by mrbean-bremen** [comment]
The sample has been added with the comment "Adding runtime style changing example" (2010, so this is quite old), so the names makes some sense. It shall show how to access and alter an element of the SVG source tree at run-time.
`SvgSample` would be a too generic name IMO.

**Comment by Psycho7** [comment]
@mrbean-bremen Thanks for the quick reply. Your argument looks solid to me.

Then how about updating the name in [the document](http://vvvv.github.io/SVG/doc/Samples.html#svgsample)? I was looking for `SvgSample` but found no folder with this name, confused for some time.

**Comment by mrbean-bremen** [comment]
Yes, that makes sense, thanks!
