### ISSUE TITLE
BUG: SVG images with Gradients are not rendered correctly

### ISSUE THREAD

**Issue by Emasoft** [vvvv/SVG#82]
SVG images with gradients are not rendered correctly.

![Balloons.svg](https://cloud.githubusercontent.com/assets/713559/3559953/c07745b2-0954-11e4-9f32-660a813bf6dd.png)

You can download the balloons.svg file from this fiddle:
http://jsfiddle.net/EmanueleS/d2VzQ/

**Comment by mrbean-bremen** [comment]
This is from current master:
![grafik](https://user-images.githubusercontent.com/4623701/50376924-a17dce80-0614-11e9-9533-823f4d522b7d.png)
While there are still some discrepancies, I think this is good enough - closing this.
