### ISSUE TITLE
BUG: SVG images with Patterns are not rendered correctly

### ISSUE THREAD

**Issue by Emasoft** [vvvv/SVG#84]
SVG images with patterns, like this upper tab with a wood tile pattern fill, are not rendered correctly by the library. Some text is missing. Shadows and gradients are also broken.

![UpperTab.svg](https://cloud.githubusercontent.com/assets/713559/3560176/3eb2189c-095c-11e4-877a-ea500ed31173.png)

Here you can download the UpperTab.svg file:  http://www.yourfilelink.com/get.php?fid=942948&dv=1

**Comment by H1Gdev** [comment]
In #280, issue of pattern is solved.
