### ISSUE TITLE
Break of portability due to included WPF references in the last commit

### ISSUE THREAD

**Issue by Emasoft** [vvvv/SVG#91]
I've just tried to compile the library after the last pull ( https://github.com/vvvv/SVG/pull/90 ), and after deleting the dead reference to the SvgReader class (not a serious problem), I've found another problem.
There are some added references to the PresentationCore assembly (a WPF component) that give me errors compiling (in example: in SvgUnit.cs you are using System.Windows.Media.FontFamily instead of System.Drawing.FontFamily). This is because WPF is not portable and it is not supported by Mono. I'm using Mono on Mac OSX. I think we should stick to making a true portable library (Win, OSX, Linux) and avoid using proprietary frameworks like WPF.

P.S.
Of course this refers only to the SVG project itself, not to the various examples included. Samples can be in different versions (Win, OSX, Linux, etc.) and using system specific libraries like WPF. But the main SVG library should remain portable.

**Comment by mrbean-bremen** [comment]
WPF dependency has been removed in next commit - closing.
