### ISSUE TITLE
Compatibility with .NET 3.5 of the Nuget package

### ISSUE THREAD

**Issue by MCKLMT** [vvvv/SVG#94]
Hi,

The recent changes broke the compatibility with .NET 2.0 (and 3.5) of the last nuget package. I downloaded the last sources and builded myself the assemblies and all is fine. However, I prefer using a package to benefit the future evolutions you'll make.

Is it possible to publish a new Nuget package to fix that please?

Thanks

**Comment by mrbean-bremen** [comment]
This is resolved with the later nuget packages.
